### ISSUE TITLE
zsh completion for `tea +pkg`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#109]
The results can be obtained with:

```sh
cd $(tea --prefix)/tea.xyz/var/pantry/projects
find * -name package.yml -type f -exec dirname {} \;
```

**Comment by jhheider** [comment]
My brain thinks this is the same as:

`find $(tea --prefix)/tea.xyz/var/pantry/projects -name package.yml -type f -exec surname {} \;`

**Comment by mxcl** [comment]
Provided it operates in a subshell the `cd` is safe. I prefer doing *less* and relying on `sed` with its platform specific quirks seems riskier.

**Comment by jhheider** [comment]
Yeah, agreed. The _final form_ might be profitably added to the client as `tea --completions`.

**Comment by mxcl** [comment]
Closing in lieu of #591
