### ISSUE TITLE
`curl dist.tea.xyz` should download the latest tea.xyz tarball

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#112]
We have this in the `README` it's a neat idea.

Needs a lambda on our cloudfront to do it, and it should only do it for `cURL` so we can provide the web listing for the whole of `dist.tea.xyz` like I keep asking @jhheider to do.

**Comment by jhheider** [comment]
<img width="972" alt="Screenshot 2022-11-10 at 18 37 29" src="https://user-images.githubusercontent.com/13246308/201228424-aaa6c614-f6bd-46ce-92cc-e1696d56d42d.png">

@Xercesblu3 I think that's what we can do for now. If we want to alter language in the future, that's simple enough (it's a lambda)

**Comment by mxcl** [comment]
This is good. Job done!
