### ISSUE TITLE
tea REPL should be clearly a tea REPL

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#124]
possibly: `export PS1=${PS1%%}- tea-REPL %`

**Comment by mxcl** [comment]
We do for `zsh`: https://github.com/teaxyz/cli/blob/main/src/app.exec.ts#L276

I imagine Keith uses zsh, but all the same this needs expanding for sure.

**Comment by mxcl** [comment]
Yeah so he is using zsh and we set `PS1`

<img width="687" alt="image" src="https://user-images.githubusercontent.com/58962/200577445-ec120db7-97e4-4afa-a855-20bae53aafc7.png">

So I'm confused, will need to dig deeper

**Comment by mxcl** [comment]
Maybe his zsh isn't at that path? @keith

**Comment by mxcl** [comment]
@jhheider pls add the same code for `fish`.

**Comment by jhheider** [comment]
Possibly .zshrc or other file is clobbering the PS1 as he thinks. Definitely worth seeing about `fish`; it doesn't try to be POSIX which can make such interop... interesting.

**Comment by mxcl** [comment]
well `--no-rcs` and `--no-global-rcs` presumably should prevent the clobbering? But I'll be honest, I don't know all the intricacies of how shells load their configuration. It's surprisingly complex.

**Comment by mxcl** [comment]
>  it doesn't try to be POSIX which can make such interop... interesting.

all we need is to set a PROMPT basically, so the user knows they are in a REPL rather than thinking it failed like @Keith did.

**Comment by magnusviri** [comment]
I don't know if I will use this, but if I did, I've put a lot of work into customizing my prompt, and I'd like to keep it in the REPL. Python virtual environments modify the prompt by putting the name of the virtual environment in parenthesis before the normal prompt, something like this.

```
export PS1="($name) $PS1"
```

Can tea do something like that? Maybe `export PS1="(tea) $PS1"`

**Comment by mxcl** [comment]
Closing this since we don’t know how to reproduce and haven't heard this issue again.
