### ISSUE TITLE
tea command doesn't execute python scripts

### ISSUE THREAD

**Issue by RyanSinger** [teaxyz/cli#132]
The README says tea can be used to run scripts, it it doesn't work. 
```

➜  stable-diffusion git:(main) ls
LICENSE                           ldm
README.md                         main.py
Stable_Diffusion_v1_Model_Card.md models
assets                            notebook_helpers.py
configs                           scripts
data                              setup.py
environment.yaml
➜  stable-diffusion git:(main) tea setup.py
tea: command not found: setup.py
➜  stable-diffusion git:(main) 

```

**Comment by magnusviri** [comment]
Try `tea -X python setus.py`. I'm not sure if it will work. This might work also. `tea +python.org ./setup.py`  The idea is one needs to tell tea what dependencies are needed. The first one does it with -X python, basically saying to add python's dependencies. The second one does it by specifying the dependency, +python.org.

**Comment by mxcl** [comment]
`tea setup.py` should work yeah. Let me see if we accidentally broke this.

**Comment by mxcl** [comment]
0.11.7 is being built. You should be able to upgrade with `sh <(curl tea.xyz)` in about 20 mins.

Please LMK how using it for stable-diffusion goes. My intent is to support python and pypa modules first class including pre-building any binaries for modules required, but my experience with Python is relatively limited so I'll need pointers. 🙏
