### ISSUE TITLE
panic:Not a directory (os error 20), stat '/usr/local/bin/php/git

### ISSUE THREAD

**Issue by byronrode** [teaxyz/cli#142]
```
Error: Not a directory (os error 20), stat '/usr/local/bin/php/git'
    at Object.statSync (deno:runtime/js/30_fs.js:322:9)
    at Path.isFile (file:///opt/tea.xyz/src/v0.11.10/src/vendor/Path.ts:100:25)
    at Path.isExecutableFile (file:///opt/tea.xyz/src/v0.11.10/src/vendor/Path.ts:119:19)
    at find_git (file:///opt/tea.xyz/src/v0.11.10/src/hooks/useSync.ts:12:18)
    at install (file:///opt/tea.xyz/src/v0.11.10/src/hooks/useSync.ts:64:27)
    at update (file:///opt/tea.xyz/src/v0.11.10/src/hooks/useSync.ts:145:18)
    at file:///opt/tea.xyz/src/v0.11.10/src/app.ts:25:15
```

## System Info

macOS Ventura - 13.0
ZSH Shell
Use Mackup for dot file/app prefs backups, but .tea not currently symlinked
Python environments are run via `pyenv`

## Additional Notes

Initially I attempted to install v0.11.4 but that never prompted for the symlink for `tea` to be added. I first installed v0.11.10 just by running the install command, but to make sure I wasn't using anything that could have conflicted, I deleted the `.tea` folder and reset `.zhsrc` and deleted the symlink and then reinstalled again.

It mentions that it is preinstalling the pantries, but running `tea -S` is what causes this issue above, and if I try and run `tea +gnu.org/wget wget -qO- tea.xyz/white-paper | tea +charm.sh/glow glow -` I get the following:

```
error: not-found in pantry: charm.sh/glow/package.yml (spilt-tea-101)
your time to shine? we’ll see you on GitHub…

    https://github.com/teaxyz/pantry.extra#how-to-contribute
error: not-found in pantry: gnu.org/wget/package.yml (spilt-tea-101)
your time to shine? we’ll see you on GitHub…

    https://github.com/teaxyz/pantry.extra#how-to-contribute
```

**Comment by mxcl** [comment]
Errors suggest that your git installation is broken.

* Is `/usr/local/bin/php/git` is file?
*Does it run? 
* What does `which git` say?
* How about `git --version`?

**Comment by byronrode** [comment]
Perhaps also worth noting is that all git commits are GPG-signed, not that I think it would be an issue.

**Comment by byronrode** [comment]
> k our pathing library appears to be throwing because a directory is in your `PATH` that doesn't exist. Will fix.

Let me check my `PATH` setup, might also be something lingering there. Would it help if I shared current `PATH`?

**Comment by mxcl** [comment]
Nah it's cool, I have hacked `Path.ts` to just infer any kinds of errors mean return false, which for now is fine honestly, it's a fail safe.

When we have time we'll fill out the test suite and be more careful.

Update coming up.

**Comment by mxcl** [comment]
> Initially I attempted to install v0.11.4 but that never prompted for the symlink for tea to be added

I think I have fixed these issues yesterday. Hopefully 🤞

Thank you so much for the detailed report. LMK if not fixed in ~20 mins

**Comment by byronrode** [comment]
Epic.

Additionally, there was the following `export PATH=/usr/local/bin/php:$PATH` in my `.zshrc` but removing it and starting a new shell session didn't change the outcome. Outside of the above, it is very likely that I have something in my `PATH` that is way past it's sell-by date ;)

**Comment by mxcl** [comment]
> Additionally, there was the following export PATH=/usr/local/bin/php:$PATH in my .zshrc but removing it and starting a new shell session didn't change the outcome

Oh is it the same error? As I'm not sure where it would find `/usr/local/bin/php` if not from your `PATH`.

**Comment by mxcl** [comment]
Even so, 0.11.11 should fix that specific issue by not throwing if the `Path` contains directories that don’t exist when checking if something is a file 🤦‍♂️

**Comment by byronrode** [comment]
> Even so, 0.11.11 should fix that specific issue by not throwing if the `Path` contains directories that don’t exist when checking if something is a file 🤦‍♂️

I saw the changes, but it was definitely on my side 🤒  iTerm was holding onto something in the session somewhere, and `source` as well as fresh shell didn't help, but after restarting iTerm and running `tea -S` it worked with no issues.

Thanks for the quick assist.

**Comment by mxcl** [comment]
well `tea` *must* be resilient to incorrect environments. We have to just work! So definitely appreciate the ticket. 👊
