### ISSUE TITLE
inside venv, `tea --help` lists available targets

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#145]

**Comment by miles170** [comment]
I would like to work on this. Would you mind giving more context?

**Comment by jhheider** [comment]
@miles170 if I might employ a little psi::ESP, I believe this means:

"If `tea --help` is run in a directory with a README.md file, parse the README are look for possibly build targets, as usable by [useExecutableMarkdown](https://github.com/teaxyz/cli/blob/main/src/hooks/useExecutableMarkdown.ts). If found, add this information to a new section in the `--help` output, indicating that those are runnable targets for the environment (possibly including text context, if present, from the README)."

At least, that's where I'd start my attack. ;)

**Comment by mxcl** [comment]
yep @jhheider has it.

You can `useVirtualEnv` to see if there is a virtual-env, and if so after tea’s help list the available targets. We define targets as:

```markdown
# TargetName

Description of this target’s purpose.

\`\`\`sh
the commands the target runs
\`\`\`
```

`useExecutableMarkdown.ts` is where the code should go

**Comment by miles170** [comment]
How can I consider a markdown header a valid target?
If I use `teaxyz/cli README.md` as a sample, it will treat `treattea/cli 0.13.0` as a target, but the code block is not a valid `sh` code.

**Comment by mxcl** [comment]
fair point. Originally when devising this system I figured we should have a magic comment of some kind to indicate that a given code block is exe/md, and this indeed confirms that.

Now to field ideas…

**Comment by miles170** [comment]
Would it be a good idea to use code block language?

```md
# TargetName

Description of this target’s purpose.

\`\`\`tea
the commands the target runs
\`\`\`
```

**Comment by jhheider** [comment]
Keeping the block spec will enable tools to keep syntax highlighting. Maybe a regex that matches `^\`\`\`.\*\n(#|//)\s\*tea$`?

**Comment by miles170** [comment]
> Keeping the block spec will enable tools to keep syntax highlighting. Maybe a regex that matches `^\```.*\n(#|//)\s*tea$`?

Something like

```md
## TargetName 

Description of this target’s purpose.

\`\`\`sh
# MAGIC KEYWORD HERE?
echo "Hello World"
\`\`\`
```

**Comment by jhheider** [comment]
Yeah, I might go that way. It's a little less magic, but more reliable.

**Comment by miles170** [comment]
What magic keyword should we use?

**Comment by jhheider** [comment]
I can think of two easy options (or maybe they're the same option):

`^(#|//)\s+tea`, or possibly `^(#|//)\s+tea.$extension` to indicate the script's language (tea.ts, tea.rb, tea.py, etc).

**Comment by miles170** [comment]
There is one big problem: we simply use `^#+\\s+(.*)\\s*$` to match markdown headers, which will cause comments inside code blocks to be misidentified as headers.

```md
\`\`\`sh
# THIS SHOULD NOT BE TAKEN AS A HEADER
\`\`\`
```

**Comment by jhheider** [comment]
might have to. it's the standard "process C multiline comments" issue. I think we've package flex and bison? Maybe? So, it might be possible to use one of those. Not cheap though.

**Comment by miles170** [comment]
By the way, what formatter do you guys use? I can't find a good way to format code.

**Comment by miles170** [comment]
> might have to. it's the standard "process C multiline comments" issue. I think we've package flex and bison? Maybe? So, it might be possible to use one of those. Not cheap though.

I couldn't find the Flex or Bison packages in the code repository.,

**Comment by jhheider** [comment]
(flex)[https://github.com/teaxyz/pantry/tree/main/projects/github.com/westes/flex]
(bison)[https://github.com/teaxyz/pantry/tree/main/projects/gnu.org/bison]

I disabled my code formatter since it was fighting with whatever Max was doing (VSCode default, maybe? Anything other than that should be in `.vscode/settings.json`.

**Comment by miles170** [comment]
> [github.com/westes/flex](https://github.com/teaxyz/pantry/tree/main/projects/github.com/westes/flex) [gnu.org/bison](https://github.com/teaxyz/pantry/tree/main/projects/gnu.org/bison)
> 
> I disabled my code formatter since it was fighting with whatever Max was doing (VSCode default, maybe? Anything other than that should be in `.vscode/settings.json`.

Both are 404 not found.

**Comment by jhheider** [comment]
Oops. I linked to the prior, private version of the pantry. Fixing.

[github.com/westes/flex](https://github.com/teaxyz/pantry.core/tree/main/projects/github.com/westes/flex)
[gnu.org/bison](https://github.com/teaxyz/pantry.core/tree/main/projects/gnu.org/bison)

**Comment by miles170** [comment]
> Oops. I linked to the prior, private version of the pantry. Fixing.
> 
> [github.com/westes/flex](https://github.com/teaxyz/pantry.core/tree/main/projects/github.com/westes/flex) [gnu.org/bison](https://github.com/teaxyz/pantry.core/tree/main/projects/gnu.org/bison)

Before I get started, I'd like to confirm: should I use `repl` to run Flex or Bison inside the temporary sandbox and then return the results to deno?

**Comment by jhheider** [comment]
Well, I don't even know that flex/bison is the right parser for what you want to do, but they are venerable. In general, if you needed a tool within the CLI that is provided by tea, you'd call install for the package, then use `run()` or `backticks()` to execute it. See [Unarchiver.ts](https://github.com/teaxyz/cli/blob/main/src/utils/Unarchiver.ts) for a tool that requires its own packages.

Obviously, if you need a different tool to construct a Markdown AST, you'll probably want to PR it to pantry.extra.

**Comment by mxcl** [comment]
> Shouldn't we first convert markdown to AST?

For sure we should. The regex tokenization is a quick and dirty effort that should be replaced with a real markdown parser. Since deno can use npm modules now we may want to import one.

**Comment by miles170** [comment]
> > Shouldn't we first convert markdown to AST?
> 
> For sure we should. The regex tokenization is a quick and dirty effort that should be replaced with a real markdown parser. Since deno can use npm modules now we may want to import one.

Please check PR https://github.com/teaxyz/cli/pull/212.
I have imported https://esm.sh/marked@4.2.4 to convert markdown into AST.

**Comment by mxcl** [comment]
I think one solution is to require projects to explicitly declare a dependency on `tea.xyz/exe/md` in their dependencies. I'm noodling how this might work and then we can make exe/md a `tea/cmd` and then `tea` itself becomes leaner, where exe/md is just a package choice like any other.

**Comment by mxcl** [comment]
We removed exe/md. Sorry for the wasted efforts 😔
