### ISSUE TITLE
Specify custom or local distribution

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#153]
I'm working on creating a package (isc.org/dhcp). I would like to create a REPL with the dependencies that my package requires so that I can debug the build commands. I don't know if there is a way to do this already, but I kind of instinctively thought the following might work, but it didn't (the error is shown).

```
# tea +isc.org/dhcp
error: http (spilt-tea-404)
404-not-found: https://dist.tea.xyz/isc.org/dhcp/linux/aarch64/versions.txt
```

Is there a way I can open a REPL with the dependencies that my local package requires? Maybe instead of `tea +isc.org/dhcp` I could do something like `tea +file://path_to/isc.org/dhcp`?

**Comment by magnusviri** [comment]
Ok, I figured out that pantry/src/build.sh contains all of the path stuff. That's probably good enough for now.

**Comment by jhheider** [comment]
Just to answer your question: you probably want your REPL to contain your dependencies, if you're working directly on the package, e.g.: `tea +invisible-island.net/ncurses +sourceware.org/bzip2 +tea.xyz/gx/cc +gnu.org/make`.

**Comment by magnusviri** [comment]
Yeah, that was what I meant. I didn't know I could specify multiple +pkg's. This, in combination with the build script is good enough. I'll close this issue.
