### ISSUE TITLE
semver providing unreasonable ranges

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#171]
https://github.com/teaxyz/pantry.core/actions/runs/3499494977/jobs/5861124248:

```
Uncaught (in promise) Error: invalid semver range: >=5<Infinity.Infinity.Infinity
        if (!match) throw new Error(`invalid semver range: ${input}`)
```

**Comment by mxcl** [comment]
lol

**Comment by mxcl** [comment]
this is what happens when you let copilot write ur code

**Comment by mxcl** [comment]
I managed to repro *once* then when I tried again it wouldn't happen anymore :/

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry.core/actions/runs/3499494977/jobs/5916979362#step:7:1

**Comment by mxcl** [comment]
Do we need a release or is this bug not impacting any pantry ops?

**Comment by jhheider** [comment]
I only saw it impacting the PR that updated all the missing provides; technically that doesn't need to be built anyway.

**Comment by mxcl** [comment]
cool, I'll release a point release at the next bug fix then
