### ISSUE TITLE
Segmentation fault during install

### ISSUE THREAD

**Issue by DrReD** [teaxyz/cli#178]
I tried to install on Fedora Linux 36 and this is what happens:
```
[davide@dave ~]$ sh <(curl https://tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9259  100  9259    0     0  28365      0 --:--:-- --:--:-- --:--:-- 28401
Errore di segmentazione (core dump creato)
[davide@dave ~]$ env LANG=C sh <(curl https://tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9259  100  9259    0     0  31043      0 --:--:-- --:--:-- --:--:-- 31175
Errore di segmentazione (core dump creato)
```

[core.sh.1000.2eb108b9349c4a9ca1df1d106c8dfe13.1572353.1668961576000000.tar.gz](https://github.com/teaxyz/cli/files/10050179/core.sh.1000.2eb108b9349c4a9ca1df1d106c8dfe13.1572353.1668961576000000.tar.gz)

**Comment by Grynn** [comment]
Segfault on install macOS Ventura too...

**Comment by mxcl** [comment]
> Segfault on install macOS Ventura too...

I imagine the is `gum` segfaulting. Try:

```sh
VERBOSE=1 sh <(curl https://tea.xyz)
```

**Comment by mxcl** [comment]
I really gotta make that `brew` formula…

**Comment by Grynn** [comment]
It does seem related to gum - some kind of infinite loop - 

```
xxx@mbp2019 ~ % VERBOSE=1 sh <(curl https://tea.xyz) 2>&1 | head -n 50
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9259  100  9259    0     0   165k      0 --:--:-- --:--:-- --:--:--  192k
+ test 0 -eq 0
+ MODE=install
++ uname
++ uname -m
+ HW_TARGET=Darwin/x86_64
+ ZZ=gz
+ case $HW_TARGET in
+ ZZ=xz
+ MIDFIX=darwin/x86-64
++ uname
+ test Darwin = Darwin
++ sw_vers -productVersion
++ cut -d . -f 1
+ MAJOR=13
+ test 13 -lt 11
+ test xz = gz
+ case "$ZZ" in
+ TAR_FLAGS=xJ
+ test -n '' -a -f '/tea.xyz/v*/bin/tea'
+ test -z ''
+ which tea
+ test -z ''
+ test install = exec
+ TEA_PREFIX=/Users/xxx/.tea
+ test -z ''
+ which curl
+ CURL='curl -Ssf'
+ get_gum
+ test '!' -t 1 -o '' = 0
+ GUM=gum_no_tty
+ test install = install -a -z ''
+ welcome
+ gum format --
+ case "$1" in
+ gum_no_tty format --
+ cmd=format
+ test format '!=' --
+ shift
+ test -- '!=' --
+ shift
+ case "$cmd" in
+ echo

+ echo

+ gum confirm 'how about it?' '--affirmative=install tea' --negative=cancel
+ case "$1" in
+ test -n ''
+ gum_no_tty confirm 'how about it?' '--affirmative=install tea' --negative=cancel
+ cmd=confirm

```

![t-rec](https://user-images.githubusercontent.com/212880/202919933-95a78069-034b-41d9-9f03-e0a95979198f.gif)

**Comment by mxcl** [comment]
WOW! k, I'll try to figure this out.

**Comment by jascha030** [comment]
@Grynn @mxcl I was facing this issue as well, In my case I resolved this issue by removing my install of gum (installed with go) from my path.

**Comment by Grynn** [comment]
Next issue 😔 

```
vishal@mbp2019 ~ % VERBOSE=1 tea +gnu.org/wget
/Users/vishal/.tea/tea.xyz/v0.13.5/bin/tea
tea: resolving package graph
{
  readYAML: "/Users/vishal/.tea/tea.xyz/var/pantry/projects/gnu.org/wget/package.yml"
}
{
  readYAML: "/Users/vishal/.tea/tea.xyz/var/pantry/projects/gnu.org/wget/package.yml"
}
{
  readYAML: "/Users/vishal/.tea/tea.xyz/var/pantry/projects/openssl.org/package.yml"
tea: openssl.org@1.1.118 locking
tea: openssl.org@1.1.118 querying
{
  src: URL {
    href: "https://dist.tea.xyz/openssl.org/darwin/x86-64/v1.1.118.tar.xz",
    origin: "https://dist.tea.xyz",
    protocol: "https:",
    username: "",
    password: "",
    host: "dist.tea.xyz",
    hostname: "dist.tea.xyz",
    port: "",
    pathname: "/openssl.org/darwin/x86-64/v1.1.118.tar.xz",
    hash: "",
    search: ""
  },
  dst: ~/.tea/tea.xyz/var/www/openssl.org-1.1.118+darwin+x86-64.tar.xz
}
tea: openssl.org@1.1.118 downloading
tea: openssl.org@1.1.118 downloading 2.24 MiB
error: http (spilt-tea-404)
No such file or directory (os error 2), open '/Users/vishal/.tea/tea.xyz/var/www/openssl.org-1.1.118+darwin+x86-64.tar.xz'
```

**Comment by mxcl** [comment]
@Grynn update, just fixed that (`sh <(curl tea.xyz)`)

Sorry about these issues.

**Comment by mxcl** [comment]
k! thanks for the tip about `brew`’d `gum`, I have repro’d and will fix. 🙏

**Comment by mxcl** [comment]
Fix deploying https://github.com/teaxyz/setup/actions/runs/3523456579

**Comment by DrReD** [comment]
Even worse:
now "sh <(curl https://tea.xyz)" goes in a loop, fills my 20GB of Ram + 8GB of swap, until stuff eventually gets OOM killed by the kernel. (I purposefully disabled all other OOM handlers)

**Comment by DrReD** [comment]
Also strange, running with VERBOSE=1 gives different outputs whether or not you redirect it to a file...

**Comment by DrReD** [comment]
Even just redirecting <stderr> without "VERBOSE" gives strange errors:

```
[davide@dave ~]$ LANG=C sh <(curl https://tea.xyz) > text.txt
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
^C
[davide@dave ~]$ cat  text.txt               # file is empty
[davide@dave ~]$ # no output, because the file is empty
```

 
```
[davide@dave ~]$ LANG=C sh <(curl https://tea.xyz) 2>&1 | head -n10 > text.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9201  100  9201    0     0  51350      0 --:--:-- --:--:-- --:--:-- 51402
[davide@dave ~]$ cat  text.txt  


/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range
/dev/fd/63: line 124: shift: shift count out of range

```
And we still get output on the console even if we're piping everything through "head"?

**Comment by DrReD** [comment]
`$ LANG=C VERBOSE=1 sh <(curl https://tea.xyz)` 2>&1 

loops on:
`' 'esac;' '$GUM' '"$@"' '}' '()' '{' case '"$1"' in 'confirm)' if test -n '"$YES";' then 'return;' fi ';;' 'spin)' if test -n '"$VERBOSE";' then gum_no_tty '"$@";' 'return;' fi ';;' 'esac;' '$GUM' '"$@"' '}' '()' '{' case '"$1"' in 'confirm)' if test -n '"$YES";' then 'return;' fi ';;' 'spin)' if test -n '"$VERBOSE";' then gum_no_tty '"$@";' 'return;' fi ';;' 'esac;' '$GUM' '"$@"' '}' '()' '{' case '"$1"' in 'confirm)' if test -n '"$YES";' then 'return;' fi ';;' 'spin)' if test -n '"$VERBOSE";' then gum_no_tty '"$@";' 'return;' fi ';;' 'esac;' '$GUM' '"$@"' '}' '()' '{' case '"$1"' in 'confirm)' if test -n '"$YES";' then 'return;' fi ';;' 'spin)' if test -n '"$VERBOSE";' then gum_no_tty '"$@";' 'return;' fi ';;' 'esac;' '$GUM' '"$@"' '}' '()' '{' case '"$1"' in '`

while
`$ LANG=C VERBOSE=1 sh <(curl https://tea.xyz)  2>&1 | grep "GUM"`

finds only:
`+ GUM=gum_no_tty`

in the very first lines, before the stream of:
`/dev/fd/63: line 124: shift: shift count out of range`

**Comment by jhheider** [comment]
```sh
gum_no_tty() {
	cmd="$1"
	while test "$1" != --; do
		shift
	done
	shift  # remove the --
	case "$cmd" in
	format|style)
		echo "$@";;
	confirm)
		if test -n "$YES"; then
			echo "tea: error: no tty detected, re-run with \`YES=1\` set" >&2
			return 1
		fi;;
	*)
		"$@";;
	esac
}
```

Suggests that it's falling through to the default, which is simply calling the function again. So, a better question is _which call is malformed?_ I'll see what catches my eye.

**Comment by jhheider** [comment]
It's possibly `gum ... -- spin`. I'll make a docker image and see what I can do.

**Comment by jhheider** [comment]
Not able to reproduce with `docker run -it fedora:36`... trying a VM to see if I can trigger the non-tty path that's looping (are you running under SSH?).

**Comment by jhheider** [comment]
This is suggestive:
```sh
$ ssh root@[IP]
The authenticity of host '[IP] ([IP])' can't be established.
ED25519 key fingerprint is SHA256:[REDACTED].
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[IP]' (ED25519) to the list of known hosts.
Web console: https://fedora:9090/ or https://[IP]:9090/

[root@[IP] ~]# sh <(curl tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9201  100  9201    0     0  60368      0 --:--:-- --:--:-- --:--:-- 60532
Connection to [IP] closed by remote host.
Connection to [IP] closed.
```

**Comment by DrReD** [comment]
> Not able to reproduce with `docker run -it fedora:36`... trying a VM to see if I can trigger the non-tty path that's looping (are you running under SSH?).

I'm using a local terminal and bash as a a shell. But I have a default ED25519 ssh key in ~/.shh:
```ssh-ed25519 [...]w7o8Sw8y4NAdMo2D```

Picking that up within the install scripts may cause some authentication failures...

**Comment by DrReD** [comment]
Uhmpf, I was hopeful, but I got the same results trying from a different user with no ~/.ssh.

**Comment by jhheider** [comment]
@DrReD can you confirm that this fixes it?
```sh
sh <(curl https://raw.githubusercontent.com/teaxyz/setup/26a1ad5cc1b6a8546a5850544665b7ec721c64e2/install.sh)
```

I think `which gum` was picking up the internal `gum()` function in the script on Fedora, which was causing the loop.

**Comment by DrReD** [comment]
> @DrReD can you confirm that this fixes it?
> 
> ```shell
> sh <(curl https://raw.githubusercontent.com/teaxyz/setup/c69c9d97e9748436fae3b3272383a2e0e8f9ccc5/install.sh)
> ```
> 
> I think `which gum` was picking up the internal `gum()` function in the script on Fedora, which was causing the loop.

Yes it fixes it both in Fedora 36 and Fedora 37.
