### ISSUE TITLE
Future support: (jailbroken) iOS?

### ISSUE THREAD

**Issue by The-SamminAter** [teaxyz/cli#182]
Currently, the only common package managers available for iOS's CLI are apt and pip. While pip is great for cross-platform stuff (as python on one platform will work similarly to python on another), apt isn't. Furthermore, pip is Python-specific/centered. Therefore, I propose adding support/compiling a binary for iOS in the future. The platform isn't too different than arm64-macOS, and tea on iOS would provide great value to tweak and other homebrew developers.

Just my two cents, please do consider my proposal though.

**Comment by timothytlewis** [comment]
iOS is 100% on the roadmap.

**Comment by mxcl** [comment]
yep, totally going to happen. Totally faster if we can get some help or tips here. I'm not very familiar with the current jailbreak scene, where do we start?

**Comment by The-SamminAter** [comment]
Honestly, there's not really any all-encompassing resource or page about it, but this isn't terrible: https://www.reddit.com/r/jailbreak_/wiki/index/. There's also this: https://www.theiphonewiki.com/wiki/Jailbreak.

Furthermore, the Wikipedia entry on jailbreaking isn't bad for an overview, but it doesn't mention palera1n or fugu15, the only public iOS 15 jailbreaks out there currently (it should be noted that fugu15 is a developer jailbreak).

If you have more specific questions I can try to either answer them or direct you to resources for them, but

**Comment by mxcl** [comment]
Closing in lieu of #607
