### ISSUE TITLE
Plan to register as a homebrew formula?

### ISSUE THREAD

**Issue by solzard** [teaxyz/cli#184]
Does `tea` has a plan to register on homebrew formulae in the future? It would be nice to install it with `brew install`.

**Comment by mxcl** [comment]
Yes, I should be submitting it shortly

**Comment by mxcl** [comment]
https://github.com/Homebrew/homebrew-core/pull/116323/files

**Comment by mxcl** [comment]
Note that this is stalled because we cannot figure out why CI is failing for the completed formula.

**Comment by lino-levan** [comment]
You said that you were going to make a tap for tea? Have you already done this?

**Comment by solzard** [comment]
Don't you mention `brew install teaxyz/pkgs/tea-cli` in README?

**Comment by mxcl** [comment]
I have a version coming soon (today perhaps) that adds this yes.
