### ISSUE TITLE
Inclusivity: replace "--muggle" with "--no-magic"

### ISSUE THREAD

**Issue by diddledani** [teaxyz/cli#198]
While reading the README.md file I was getting interested in the project and its functionality. However, I was unprepared to see a term associated with Harry Potter used as a command line switch. While I, myself, am able to cope with seeing this term, many trans people will be upset and hurt by the use of this term (see the background in the next paragraph). To ensure that the project is inclusive, and not alienating people from a marginalised community, please consider replacing `--muggle` with something more benign such as `--no-magic`.

For background, JKR has been very vocally anti-trans, supporting far-right activists who call for our elimination, and using her platform to viciously attack us on a regular basis. For the majority of the trans community any mention of her, the wizarding world, or references to the wizarding world are deeply offensive or triggering of trauma.

I may not personally be able to contribute much, or anything, to this project (I still need to learn Rust to fulfil the "trans girl does Rust" meme 🤪) I would appreciate the change in term to avoid harming anyone else who is more capable to contribute from my community.

**Comment by mxcl** [comment]
Thanks for pointing this out—I'm ashamed to say I got so caught up in “being clever” I hadn’t thought through what else it may mean.

**Comment by mxcl** [comment]
v0.14.1 is being deployed.
