### ISSUE TITLE
wiki for the cli?

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#211]
I've been making [notes](https://github.com/magnusviri/tea-notes) on the tea cli usage under my github, but I kind of wished that you guys looked at it and could correct things I get wrong. If there were a wiki for the cli, then I could move my notes over to it.

Also, do you guys get notified when the wiki is updated? And do you know anyone can edit it? I've been editing https://github.com/teaxyz/pantry.zero/wiki.

**Comment by mxcl** [comment]
Enabled, go wild. Thanks @magnusviri
