### ISSUE TITLE
tea --version and tea -v are different:

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#214]
```sh
$ tea --help                                     16:31:12
...
aliases:
  --help,-h                   --dump=usage
  --version,-v                --dump=version                            𐄂
...
$ tea --version
tea 0.14.5
$ tea -v
/Users/jacob/.tea/tea.xyz/v0.14.5/bin/tea
```

**Comment by pedrocruzio** [comment]
On [line 169](https://github.com/teaxyz/cli/blob/65a2bc4f9ea84e80e32193035c347fd15fd88ac9/src/hooks/useFlags.ts#L169) in `useFlags.ts`, case: 'v' does not output the version. 

There may be a conflict between the version and verbose flags.

**Comment by mxcl** [comment]
I was copying Python where `-v` is show version and then be verbose. Which I think is the most pleasant interpretation.

But yeah the version output should be the same as `--version` I guess.

**Comment by mxcl** [comment]
Like, what I did was make the output *more verbose*. So it outputs the path as well since this includes the version.

Note that in “sources mode” the output is totally different but this is ok since it is sources mode for hackers like us only.

**Comment by mxcl** [comment]
But yeah, it should only do what it does now for `-vv` or verbosity: loud
