### ISSUE TITLE
Feature request: if symlink, then readlink, and if it begins with "tea", then add the rest as args

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#219]
This is the second half of [parse argv[0] and do the same with it as -X arg ](https://github.com/teaxyz/cli/issues/167).

For symlinks, I think I figured out, not just how to specify a version, but also how to specify a package and more. If argv0 is a symlink, then read the link. If it is another symlink with a name that matches "tea (.+)", then parse $1 as you would args. So you can create a symlink to tea named "tea +gnu.org grep" and then create *any* symlink you want to that symlink and it will run gnu.org's grep. You can also create a symlink to tea named "tea +freebsd.org grep" and then create *any* symlink you want to that symlink and it will run freebsd.org's version (assuming it gets added--there are people who have built this for Linux). So I can name the 2 symlinks "goodgrep" and "badgrep" and it doesn't matter because the second symlink is the actual symlink.

And I suppose you could go insane and create symlinks like "tea +gnu.org grep -r some pattern /some/path" or worse, "tea -X find path -name somename -other criteria -exec go crazy commands \{\} \;" and it's kind of crazy but someone could do it with this... Maybe it would create a support nightmare? IDK, I was just trying to figure out how to have 2 packages that provide the same tool and be able to have a symlink choose between them without having a config file for tea. And this does go along with the idea of having symlinks act as the "database" (or in this case, the config lol).

**Comment by magnusviri** [comment]
On second thought, maybe allowing any arg would be too much. Maybe by default it would just parse "tea +package[op-version] command". And there could be a tea config that switch that allowed the crazy behavior, which is off by default.

**Comment by mxcl** [comment]
This is possibly going too far.

Would it not be better served with aliases `alias foo=tea +foo/bar foo` or simple shell scripts† at this point?

† ```sh
#!/bin/sh
exec tea +foo/bar foo "$@"
```

**Comment by magnusviri** [comment]
Oh blah. Yeah, you're right. IDK why I was trying so hard to make the symlinks work. Broken symlinks are pretty hard to debug and having 2 would make it a nightmare. But an alias or shell script would be fairly easy. And in the case of an alias, the shell rc file would basically act as the config file. And not to mention the character limit in a name, and the special characters... Anyway... 🤪
