### ISSUE TITLE
extract the tarball while downloading

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#220]
pipe the data to an instance of tar, extract as we download.

**Comment by jhheider** [comment]
failure cases:
- download doesn't complete
- sig/checksum verification doesn't match

those seem like risks that will be harder to mitigate. thoughts?

**Comment by jonchang** [comment]
I feel like pipelining of downloads (such that all download+extract steps occur in parallel) is probably "good enough", and in general most tarballs are not as big as e.g. LLVM.

**Comment by mxcl** [comment]
> download doesn't complete

delete extraction is sufficient I assume

> sig/checksum verification doesn't match

same…?

unless I'm missing something.

**Comment by mxcl** [comment]
my goals here are for us to be suppppper fast

parallel downloads/verify/extract being a next step, but I'm worried about the UI for that so plan to do it myself. Since I wrote the current TUI for it.

**Comment by jhheider** [comment]
I suppose I'm worrying about the case where we're replacing existing/working bins, but that's mostly only on build, so deletion of the target directory might be sufficient.

**Comment by mxcl** [comment]
> replacing existing/working bins

`tea` in usual use can't do this currently. build is certainly different and I'd like us to work better here but currently don't have any great solutions (bar two tea prefixes, which is maybe the best bet, but a little tricky to engineer).

**Comment by mxcl** [comment]
also we should be able to resume downloads that fail eventually. Not too hard in this modern HTTP world. Currently we cannot and in fact “trying again” fails and deletes the tarball.

**Comment by mxcl** [comment]
This in 0.25
