### ISSUE TITLE
When installing a new package version, remove the old one

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#225]
I'm writing documentation in the [wiki](https://github.com/teaxyz/cli/wiki/Basics) and I can see something that people will probably be annoyed by. I'm sure there are many users who will only want the latest version of the software. My understanding is that currently, tea will only add and doesn't clean up old installs.

I haven't got any idea how to do this, but I've heard several times that the community could write a cli extension to do this type of thing. I'm thinking maybe the tool should be called "pm" for package manager.

**Comment by mxcl** [comment]
Yeah, tea/cmd will satisfy this.

**Comment by magnusviri** [comment]
Sounds good. I'll close this. I didn't know about tea/cmd. I'll wait to see what it can do.

**Comment by Kapelianovych** [comment]
@mxcl hello. Unfortunately, the link to **tea/cmd**, you provided, is not accessible anymore. I have checked the presence of the package in the current organisation, but it does not exist here either. Is there another way to cleanup cached packages?

**Comment by jhheider** [comment]
I believe that repo has become https://github.com/pkgxdev/mash.

**Comment by Kapelianovych** [comment]
Okay. I had to get my hands a little bit dirty. For those who are like myself and don't understand or see an easy way to manage the cache (automatically installed packages), there is a one command to do that.
```sh
pkgx mash pkgx/cache <ls|upgrade|prune>
```
It allows you to:
- `ls` - lists all locally available packages which are cached (I believe those which are not `install`ed).
- `upgrade` - checks for newest version of all locally available packages and downloads them if available.
- `prune` - retains only the newest version of every locally available package.

> Apparently this command was created a long time ago but for some reason its existence is not very obvious for some people (including myself) who stumbles upon this awesome tool for the first time. Unless you carefully read the whole README, understand the concept of the `mash` and check the repo.
>
> Well, it might be understandable since `mash` is in its very early stage at the moment of writing.

**Comment by jhheider** [comment]
removing all packages including the latest one should be as simple as `rm -r ${PKGX_DIR:-~/.pkgx}` (use with caution).

**Comment by mxcl** [comment]
pkgx mash pkgx/cache prune
