### ISSUE TITLE
-w (or something) for which

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#226]
Please implement a tea "which" or dry run command. It should print out what tea would do without it present but not actually do it.

**Comment by mxcl** [comment]
Not enough? `tea +foo.com which foo`

**Comment by jhheider** [comment]
But a `tea -n` could be useful: spit out the resolved deps, which would be installed, and then display the computed run script, probably.

**Comment by magnusviri** [comment]
`tea +foo.com which foo` and `tea which foo` work but `tea -X which foo` doesn't. As I've set up the symlinks and a modified PATH that includes my symlinks, ~/.tea_bin, sometimes I've been confused over what `-X foo` was going to execute, especially if there exists something like /opt/homebrew/bin/foo.

```
> tea +stedolan.github.io/jq which jq
/opt/tea/stedolan.github.io/jq/v1.6.0/bin/jq
> tea -X which jq
error: not-found: tea -X: arg0 (spilt-tea-001)
couldn’t find a pkg to provide: `which'

you could be the one to add it to `tea`:

    https://github.com/teaxyz/pantry.zero#contributing

> tea which jq
/Users/james/.tea_bin/jq
```

BTW, `tea jq` works.

**Comment by mxcl** [comment]
FYI `tea -X foo` no longer searches the `PATH`, so it will only execute any `tea` provided tool.

**Comment by mxcl** [comment]
> But a tea -n could be useful: spit out the resolved deps, which would be installed, and then display the computed run script, probably.

This is basically a variant of `--dump` but with `--format` flag where the default dump format is `shell`

**Comment by mxcl** [comment]
I'm noodling all of this in order to figure out what is the correct set of trade offs.

To be clear: I agree, we either shouldn't be confusing or we should provide something like what is proposed here.

**Comment by mxcl** [comment]
Having said this, since `-X` no longer goes to the `PATH` and `tea which foo` works, it seems we’re actually good here?
