### ISSUE TITLE
Bad yml

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#238]
I was working on a package and the yml was malformed and it produced this error:

```
> ./pantry.core/scripts/build.ts lame.sourceforge.io
~/Github/Tea/pantry.extra_mag/projects/lame.sourceforge.io/package.yml
error: parser: pantry: package.yml (spilt-tea-102)
pantry entry invalid. please report this bug!

    https://github.com/teaxyz/pantry.core/issues/new
```

I tried to figure it out but it looks like the error is in the cli when it tries to read all of the yml files.

**Comment by mxcl** [comment]
We need to tease the underlying error out of the YAML parser.

But also, would be nice if we knew this was not a bug to report. Not sure how we can know that this file is *new* without checking git.

**Comment by mxcl** [comment]
0.16.1 has better error handling in 4f1fb57

**Comment by magnusviri** [comment]
I was thinking of just having it say "couldn't load /path/to/file.yml".

**Comment by mxcl** [comment]
It now says it cannot parse the YAML with a reason. LMK if this is good enough in 0.16.1

**Comment by magnusviri** [comment]
Yes! This is great! Thank you!
