### ISSUE TITLE
If there’s a `VERSION` file, coerce the version out of it

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#24]
Eg. go.dev has a VERSION file that contains eg. `go1.18.3`

**Comment by Xercesblu3** [comment]
@calvinyee is this something you can do? Should be your next focus.

**Comment by calvinyee** [comment]
Sure, Just to make sure I get the details right. My understanding is that if there is a VERSIONS file at the root, the TS code for teaxyz/cli should use what is in the VERSIONS file instead of what is in the code now ?

**Comment by jhheider** [comment]
I would say:

"If a directory contains /^VERSIONS?(\.(txt|md))?$/i, pass its contents through the GitHub tag parsing logic to check if it produces a parsable semver."

**Comment by mxcl** [comment]
If there's a `VERSION` file `useVirtualEnv.ts` uses that for the `version` key.

**Comment by Xercesblu3** [comment]
@calvinyee disregard this for now, my bad. Will discuss priorities in DM.
