### ISSUE TITLE
Consider using package-url as input

### ISSUE THREAD

**Issue by pombredanne** [teaxyz/cli#240]
This would be well traveled, mostly universal way to identify a package
See https://github.com/package-url/purl-spec

and for instance https://github.com/kdeldycke/meta-package-manager or https://gist.github.com/pombredanne/d3585617882f91d9316be5ce5eddf190

**Comment by mxcl** [comment]
Thanks, but I like our choices.

**Comment by pombredanne** [comment]
> Thanks, but I like our choices.

Fair enough, your call: that's eventually you against the rest of the world :)

**Comment by mxcl** [comment]
I don’t mind supporting that in addition tho.
