### ISSUE TITLE
Make tea magic hook work on fish

### ISSUE THREAD

**Issue by pkmuldoon** [teaxyz/cli#245]
Looks like a great project! However, when using fish, after install I get

```
  want magic?

  tea’s shell magic works via a simple hook function in fish
  it’s not required, but we do recommend it.

  │ docs https://github.com/teaxyz/cli#usage-as-an-environment-manager
sh: line 362: ~/.config/fish/config.fish: No such file or directory
```

The file `~/.config/fish/config.fish` does exist and is writeable. This is on Mac OS Ventura 13.0.1 on the ARM M1 Max with fish shell version 3.5.1

I'm running asdf but that doesn't seem to be impacting. BTW to get the install script to work on Fish, I had to do: `sh < (curl https://tea.xyz | psub)`

Thanks for all of your awesome work!

**Comment by mxcl** [comment]
Did https://github.com/teaxyz/setup/pull/103 fix this per chance? This is merged so running the install line again should use this fix.

> `sh < (curl https://tea.xyz | psub)`

interesting. Is that what you have been using @jhheider? Either way we should add this to the README.

**Comment by jhheider** [comment]
yep. i thought we had documented the psub syntax somewhere, but it might have just been in a ticket.

**Comment by mxcl** [comment]
I believe we’re done here. Reopen if I'm wrong!
