### ISSUE TITLE
Please support nushell

### ISSUE THREAD

**Issue by evelant** [teaxyz/cli#273]
https://www.nushell.sh/ is a fantastic modern take on a shell. It's feature rich and stable enough that I love using it as a daily driver.  It would be really nice to use tea with nushell!

**Comment by jhheider** [comment]
This should be reasonably easy; a quick search of `fish` suggests that the following spots would need attention:

- cli:README.md
  - install directions
  - command not found hook
- cli:app.dump.ts
  - environment set commands (if not POSIX)
- cli:app.exec.ts
  - REPL-specific flags and prompt
- steup:install.sh
  - shell hook
- pantry.extra:packages/nushell.sh/package.yml
  - (OPTIONAL) package `nushell` for `tea`

**Comment by mxcl** [comment]
We'll support all shells that are easy, and eventually all shells that are hard too.

PR welcome, otherwise we'll get to it when we get a moment.

**Comment by lino-levan** [comment]
It looks like nushell can't be fully supported yet since they don't have process substitution. Actually installing tea works fine. I haven't looked at the magic hooks.

**Comment by mxcl** [comment]
Usually you can pipe instead, that doesn't work?

**Comment by lino-levan** [comment]
As I mentioned in #393, you are able to install tea using a pipe but you don't get the magic properties of the install command that way.

**Comment by jasonmorganson** [comment]
This is what I have for my Nushell config:

[~/.cache/tea/init.nu](https://github.com/jasonmorganson/dotfiles/blob/main/dot_cache/tea/init.nu)
```nu
def "parse tea vars" [] {
  $in | lines | parse "{name}={value}" | where name != 'undefined'
}

def-env "update tea env" [] {
  for $var in $in {
    let-env $var.name = $"($var.value)"
  }
}
  
def-env tea_hook [] {
  tea --env --silent
    | parse tea vars
    | update tea env
}

export-env { tea_hook }
```

[~/.config/nushell/config.nu](https://github.com/jasonmorganson/dotfiles/blob/main/dot_config/nushell/config.nu)
```nu
source ~/.cache/tea/init.nu

let-env config = {
    hooks: {
        pre_prompt: [{
            code: { ||
                tea_hook
            }
        }]
        pre_execution: [{
            code: { ||
                tea_hook
            }
        }]
        env_change: {
            PWD: [{
                code: { ||
                    tea_hook
                }
            }]
        }
    }
}
```

This works with the latest version (`v0.78.0`).

**Comment by mxcl** [comment]
Closing in lieu of #704
