### ISSUE TITLE
`$ tea . $args` is doing something expected but should it be different?

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#274]
Recreation Steps:
have the ff files
README.md
```
## Dependencies

| Project    | Version |
|------------|---------|
| nodejs.org |  >=16   |
| pnpm.io    |  >=7.18.2 |

# Getting Started
\```sh
pnpm install
\```

# Build

\```sh
echo "hello"
\```
```

Issue:
`$ tea . build` is turning into `$ pnpm install build`

**Comment by mxcl** [comment]
`tea .` instructs tea to run `# Getting Started` passing `build` as a parameter.

Did our docs suggest this would be otherwise? If so our docs are wrong.

Now, should this behave differently? Quite possibly.

**Comment by getneil** [comment]
now im curious which would be the better implementation.
should i adopt the Getting Started to be something more like this to accommodate the potential future usage?
```sh
pnpm install
if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
  else
    pnpm $@
fi
```

Im not sure which would be more intuitive on the part of the dev users
a. `tea . build` is equal to `tea build`
b. `tea . $arg` is equal to whatever the repo engineers build it to be and handle it themselves

**Comment by getneil** [comment]
changed the title for better accuracy.

**Comment by jhheider** [comment]
I fear I've opened a can worms by [having fixated something incorrect in my mind](https://github.com/teaxyz/cli/discussions/270#discussioncomment-4443405).

**Comment by mxcl** [comment]
IMO getting started (`tea .`) should run the web-app, and build should create the `.app`.

**Comment by mxcl** [comment]
But yeah I'm not sure about `tea .`, the behavior is somewhat like `make` where `make` by itself does the default target. However I shied from `tea` by itself doing that as it just seems too magical.

Honestly I'm starting to wonder if exe/md as we are using it makes a lot of sense and if it fits into what tea is trying to accomplish. I'm having a crisis on all this stuff RN.

**Comment by mxcl** [comment]
We removed exe/md (sorry Neil, after all that too…)
