### ISSUE TITLE
Automagic determination of a source control directory does not work within a git worktree

### ISSUE THREAD

**Issue by hisaac** [teaxyz/cli#277]
When determining if a directory is a source control directory (`SRCROOT`), `tea` looks specifically for an item named ".git", ".svn", or ".hg", and then checks if it is a directory:

https://github.com/teaxyz/cli/blob/6164c6bac7296e1da03f9bba80faf06630d47e12/src/hooks/useVirtualEnv.ts#L31-L43

This works in most cases, but when using a [git worktree](https://git-scm.com/docs/git-worktree), git replaces the `.git` directory with a text file named `.git` that contains a pointer to the original repo's location on disk. ([more info](https://git-scm.com/docs/git-worktree#_details))

Here's an example of what that file contains:

```
gitdir: /Users/hisaac/Developer/mine/hisaac.net/.git/worktrees/hisaac.net-eleventy
```

Would it be reasonable to skip the `.isDirectory()` check for items named .git? Or perhaps if an item is found with name .git that is not a directory, you could check for the existence of the text `gitdir: `?

**Comment by mxcl** [comment]
Yes, we should operate the same as `.git` would for sure.

**Comment by jhheider** [comment]
At the cost of another exec:

```typescript
try {
  await run({ cmd: ["git", "status"] })
} catch {
  // doesn't appear to be a repo
}
```

**Comment by hisaac** [comment]
Until this is fully addressed, is there a way to force `tea` to use the current working directory as the `SRCROOT`?

**Comment by jhheider** [comment]
Obviously, in the immediate term, you can change `.isDirectory()` to `.exists()` and build local. I have a hard time imaging that breaking without a malicious attempt to break it. Local testing with `TEA_DIR=. tea -d` shows that it works without VCS detection.

**Comment by hisaac** [comment]
Ah there we go, `TEA_DIR=.` was the ticket. I didn't know about that env variable. Thanks!

**Comment by mxcl** [comment]
Yeah we need to document `TEA_DIR`.

**Comment by hisaac** [comment]
Could be nice to have the option of a "marker file" of some sort to tell `tea` that the current directory is one that it can/should run in. Like in addition to looking for `.git`, `.svn`, and `.hg` directories, it could look for a file named `.tea_dir` or something.

**Comment by mxcl** [comment]
This should be fixed, we now determine the dev-env from all the “project” like files we find.

**Comment by hisaac** [comment]
Thank you for the fix, and the follow up 🙏
