### ISSUE TITLE
Error using executables from Rubygems packages

### ISSUE THREAD

**Issue by gettalong** [teaxyz/cli#282]
I wanted to try out tea and installed Ruby:

~~~ shell
$ tea +ruby-lang.org
~~~

Rubygems was also installed as dependency, so all good. However, when installing a gem that contains an executable that executable cannot be run:

~~~ shell
# In the shell open by the above tea command
$ gem install hexapdf
Fetching hexapdf-0.28.0.gem
Fetching cmdparse-3.0.7.gem
Fetching geom2d-0.3.1.gem
Successfully installed geom2d-0.3.1
Successfully installed cmdparse-3.0.7
Successfully installed hexapdf-0.28.0
3 gems installed
$ hexapdf -v
/home/thomas/.tea/ruby-lang.org/v3.1.2/bin/ruby: no Ruby script found in input (LoadError)
~~~

This works just fine when installing Ruby and Rubygems normally

**Comment by mxcl** [comment]
oh ok, a relocatability issue, I'll fix and add a test for this to ensure it doesn’t break again. Many thanks for the report.

**Comment by gettalong** [comment]
Wow - thanks for the fast reply! :smile: 

I'm not very familiar with Typescript but if there are other things to do to make sure Ruby has great support by tea, please let me know!

**Comment by mxcl** [comment]
K should work now, if you `tea --sync +ruby-lang.org` it’ll download the latest build (I fixed the issue stopping us from auto-building new ruby’s also, so we now have 3.2.0 and will build new versions immediately going forwards).

If you need 3.1.2 then I am rebuilding that currently, but to get it you will need to delete the existing install first as we don’t yet have a “force update” mechanism. (`rm -rf ~/.tea/ruby-lang.org/v3.1.2`)

**Comment by gettalong** [comment]
Thanks - works as expected!

**Comment by mxcl** [comment]
> if there are other things to do to make sure Ruby has great support by tea, please let me know!

let us know if things aren't working as expected or if things can be improved and we'll fix them! thanks.
