### ISSUE TITLE
Execution sequence of tea pipelines not as expected

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#285]
I'm running these two chained commands with `tea`

```sh
tea -X wget -O test.ts https://gist.githubusercontent.com/mfts/b470b1608834e78fdddb78217aeee6d8/raw/a6cf6746628582ab39e7df97613d7f6472469f55/happy-new-year.ts | tea -X bun run test.ts
```

I expect that that `wget` gets the file **AND THEN** pipes it to the second command `tea -X bun run test.ts` 
However, it seems that both commands get executed at roughly the same time and therefore the second command throws an error because `test.ts` does not exist.

**Error message**
```sh
error: missing script "test.ts"
--2023-01-05 11:17:17--  https://gist.githubusercontent.com/mfts/b470b1608834e78fdddb78217aeee6d8/raw/a6cf6746628582ab39e7df97613d7f6472469f55/happy-new-year.ts
Resolving gist.githubusercontent.com... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to gist.githubusercontent.com|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 63 [text/plain]
Saving to: 'test.ts'

test.ts                       100%[=================================================>]      63  --.-KB/s    in 0s      

2023-01-05 11:17:17 (5.01 MB/s) - 'test.ts' saved [63/63]
```

Surprisingly, it works as expected when the first command is not using `tea`
```sh
wget -O test.ts https://gist.githubusercontent.com/mfts/b470b1608834e78fdddb78217aeee6d8/raw/a6cf6746628582ab39e7df97613d7f6472469f55/happy-new-year.ts | tea -X bun run test.ts
```
Using system-installed `wget`
```sh
$ which wget
/usr/local/bin/wget
```

**Comment by mxcl** [comment]
Yes, both commands are instantiated at once and pipe their stdout to the stdin of the next one in the chain. This is a feature of UNIX and the shell and not something tea can control.

If you need one to wait for the other you use `&&`:

```sh
tea -X wget -O test.ts https://gist.githubusercontent.com/mfts/b470b1608/happy-new-year.ts && tea -X bun run test.ts
```

bun *should* support stdin (it's an interpreter and this is expected) but apparently it doesn’t.

This will probably work instead:

```sh
tea -X bun run <(tea -X wget -O test.ts https://gist.githubusercontent.com/mfts/b470b1608/happy-new-year.ts)
```
