### ISSUE TITLE
`--silent` over-writing current line

### ISSUE THREAD

**Issue by johnallen3d** [teaxyz/cli#287]
I've noticed that when I use `git` via a symlink to `tea` with some integrations they are picking up some of the chatter from `tea`. I think `--silent` can help with this but while I was testing it out I noticed this odd behavior where the current line of my shell is (partially) replaced with the commands output.

A picture/video can explain this one better.
![CleanShot 2023-01-08 at 15 00 33](https://user-images.githubusercontent.com/184915/211216341-85c31c6f-2bab-4eb7-8c19-fb908f13f06a.gif)

FWIW — I'm using Fish shell with the Starhip prompt.

**Comment by mxcl** [comment]
interesting, I can reproduce (zsh) but only with `--silent`. I'll investigate.

**Comment by mxcl** [comment]
Closing in the hope this fixed it. But you cannot easily test until I push a point release.

**Comment by johnallen3d** [comment]
Can confirm that this resolved the issue, thanks!
