### ISSUE TITLE
Dynamically execute different versions

### ISSUE THREAD

**Issue by Marcisbee** [teaxyz/cli#291]
Hello, I just read through the readme and tried tea cli myself. Looks cool.
The thing that came to mind in my workflow would be to execute package with specific version via cli, something like `tea node@18 server.js`.

About my usecase, in day to day life I work with a lot of node/deno projects. And quite often I need to run specific version of node in specific project (to debug other developer issues for example). So in 1 project I would love to run `tea node server.js` (the latest or project specified version) and `tea node@16 server.js` to debug in that version.

I didn't really find anything like this in readme so is this already possible or would be a great feature to add?

**Comment by jhheider** [comment]
Already possible! We're currently updating a bunch of docs, but `tea +nodejs.org^18 node server.js` or `tea -X node^18 server.js` or even `sudo ln -s tea /usr/local/bin/node^18; node^18 server.js; sudo ln -s node^18 /usr/local/bin/node; node server.js` should work (can't think of any others off-hand).
