### ISSUE TITLE
Add a tea cup to the prompt inside dev-envs if magic is enabled

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#296]

**Comment by lino-levan** [comment]
Could you elaborate on this one?

**Comment by mxcl** [comment]
Currently there is no user-feedback when tea activates a dev-env (when stepping into it with `cd` in the Terminal).

The idea is to add a tea-cup to the prompt indicating this fact in the manner of other extensions, like adding the git branch and diff status.

The tea-cup emoji is kinda ugly, but as a first step I'd like to see what it will look/feel like.

**Comment by mxcl** [comment]
I’ll get to this without keeping this ticket open.
