### ISSUE TITLE
Packaging won't work if pkg version is shorter than 3 parts

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#297]
I tried to package `nmap.org`, which has a two-part version: 7.93 
Changelog with all versions: https://nmap.org/changelog.html 
Latest tarball: https://nmap.org/dist/nmap-7.93.tgz

Trying to build the package throws the following error:
```sh
Error: too short to parse without a `v` prefix: 7.93
      if (!tolerant && parts.length < 3 && !vprefix) throw new Error(`too short to parse without a \`v\` prefix: ${input}`)
```

**Comment by jhheider** [comment]
See the remarks in https://github.com/teaxyz/pantry.core/pull/98

**Comment by mxcl** [comment]
Yeah this is a regression. pantry yaml for the `versions` key should be fine with 2 part versions IMO.

**Comment by mxcl** [comment]
It's hard for me to locate where this is happening since you didn’t include enough of the build log for me to know what part of the build is failing :/
