### ISSUE TITLE
magic exceptions

### ISSUE THREAD

**Issue by tnxz** [teaxyz/cli#309]
`gofmt` - `command not found`
`tea gofmt` - `command not found`

**Comment by mxcl** [comment]
can you add what is missing to the `provides` key here? https://github.com/teaxyz/pantry.core/blob/main/projects/go.dev/package.yml

Thank you!

**Comment by tnxz** [comment]
sorry about the earlier pull request didn't know what I was doing. Finally figured out to send a pull-request https://github.com/teaxyz/pantry.core/pull/104#issue-1535203366
