### ISSUE TITLE
error: permission denied (os error 13)

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#313]
executing `$ tea .` results in `os error 13`

<img width="380" alt="Screenshot 2023-01-17 at 7 56 04 AM" src="https://user-images.githubusercontent.com/7913978/212782079-c7145a45-c5f6-4335-bbd7-4fb2c62a8bdf.png">
<img width="303" alt="Screenshot 2023-01-17 at 7 56 09 AM" src="https://user-images.githubusercontent.com/7913978/212782084-a7ac223b-23f4-42c4-8d8e-cc0e7ed79b38.png">
<img width="337" alt="Screenshot 2023-01-17 at 7 56 23 AM" src="https://user-images.githubusercontent.com/7913978/212782085-7cfda51d-becc-4bc8-9038-f053c5be24f6.png">

issue was recreated in mac m1 and ubuntu:22.04 m1(docker).

but with ubuntu:latest x86x64 seems to be ok via github actions.

**Comment by getneil** [comment]
but `tea -SE .` works

**Comment by jhheider** [comment]
Hm.

```sh
tea .
error: permission denied (os error 13)
tea -SE .
pantries sync’d ⎷
error: permission denied (os error 13)
tea --version
tea 0.19.2
```

**Comment by mxcl** [comment]
```sh
node .
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/Users/mxl/tea/cli'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by mxcl** [comment]
Ruby does well:

```sh
$ ruby .
ruby: Is a directory -- . (LoadError)
```

**Comment by mxcl** [comment]
Another question would be “what were you expecting to happen?”.

`tea .` used to be interpreted as run `Getting Started` in executable markdown, however we removed that in 0.19, which you know since we've been talking about it on Slack for over a week.

**Comment by mxcl** [comment]
```sh
$ tea .
tea: is directory: .
```

k now does the above.
