### ISSUE TITLE
add-zsh-hook:1: TEA_MAGIC: parameter not set

### ISSUE THREAD

**Issue by chakravarthi-bb** [teaxyz/cli#314]
I am trying to install tea on my M1 Mac and whenever i restart the shell I see this error message

Shell: zsh
command: sh <(curl https://tea.xyz)

**Comment by mxcl** [comment]
Does your `.zshrc` `set -u` or something?

**Comment by chakravarthi-bb** [comment]
Hey @mxcl Thanks for the `set -u` command, I learnt something new today.

I have a few parameters that are not set because of oh-my-zsh, I just moved tea to the top of the file and can use it.

**Comment by mxcl** [comment]
I'm glad to have helped, did this fix it? Or did you remove that line?

I want to make sure other people don’t have the same problem as you

**Comment by chakravarthi-bb** [comment]
I have to comment out a few oh-my-zsh plugins though, but I am able to use **tea**

> Or did you remove that line?

If you are referring to tea, no I haven't removed it.

**Comment by chakravarthi-bb** [comment]
I just tested out `0.19.3` and it's working fine with all zsh plugins

Thanks a lot for the quick fix
