### ISSUE TITLE
symlinked `tea` interferes with other installed command-line packages like `code`

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#319]
I symlinked `tea` because I want to execute a script with `tea ./acme-script.sh` 

After doing that it couldn't find `code` the VSCode command-line tool.
```sh
$ ls -la /usr/local/bin/code
lrwxr-xr-x 1 mfts admin 68 Dec 12  2018 /usr/local/bin/code -> '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code'
``` 

```sh
$ code .
tea: command not found: code
```

If I remove the symlink of tea `rm /usr/local/bin/tea` then, `code` can be found again

using tea v0.19.4

**Comment by mfts** [comment]
It's a confusing issue, because I don't need a symlink with `tea` since v0.19.0`, so I'm closing this issue for now

**Comment by mxcl** [comment]
tea’s magic only adds to your `PATH` it doesn’t take away

```sh
$ tea --magic
# this file is generated and should not be edited

function command_not_found_handler {
  if [ "${TEA_MAGIC:-}" != 0 -a -x "/Users/mxl/.tea/tea.xyz/v*/bin"/tea ]; then
    "/Users/mxl/.tea/tea.xyz/v*/bin"/tea -- $*
  fi
}

add-zsh-hook -Uz chpwd() {
  if [ "${TEA_MAGIC:-}" != 0 -a -x "/Users/mxl/.tea/tea.xyz/v*/bin"/tea ]; then
    source <("/Users/mxl/.tea/tea.xyz/v*/bin"/tea --env --keep-going --silent --dry-run=w/trace)
  fi
}

# if the user put tea in eg. /usr/local/bin then don’t pollute their PATH
# if ! tea true 2>&1 >/dev/null; then
  export PATH="/Users/mxl/.tea/tea.xyz/v*/bin:$PATH"
# fi
```

^^ eg. that's what I get for `tea --magic`. The `PATH` that is added is based on `TEA_PREFIX` so it wouldn’t add eg. `/usr/local/bin` which would explain what you were seeing.

Basically I don’t see how you could have been seeing what you saw, nor how `tea` could be responsible.

**Comment by mfts** [comment]
> Basically I don’t see how you could have been seeing what you saw, nor how tea could be responsible.

I can only explain it that it was an old shell that didn't have the `source <($HOME/.tea/tea.xyz/v*/bin/tea --magic --slient)` and something fishy was going on.
