### ISSUE TITLE
`tea` is installing `deno` after installing tea 0.19.6

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#326]
After installing tea on my system, I open a new shell to start using `tea` 

First thing that is installed is deno before my prompt starts. 
<img width="306" alt="Screenshot 2023-01-20 at 17 42 50" src="https://user-images.githubusercontent.com/4049052/213755430-3ed7eac2-9106-4f15-b221-81f907a7fa97.png">

It's not an issue per se, but something I don't expect as a user.

**Comment by mxcl** [comment]
Cannot reproduce.

1. I deleted tea
2. I resinstalled tea
3. I opened a new terminal

**Comment by mxcl** [comment]
All I can think of is that something in your shell rc file tries to use `deno` for some reason and this causes tea to install it.

**Comment by mxcl** [comment]
Or potentially a `tea` exists in your PATH that is the old script that executed the source checkout of tea using deno.

**Comment by mxcl** [comment]
k figured it out. the command not found handler was created before we then checked if tea was in the PATH, thus tea installed tea.
