### ISSUE TITLE
`tea --sync` failing v0.21.0

### ISSUE THREAD

**Issue by johnallen3d** [teaxyz/cli#339]
I was getting some errors after upgrading to `v0.21.0` when using symlinks:

```sh
error: not-found: arg (spilt-tea-008)
`--dry-run=w/trace` isn't a valid flag.
```

I thought, "why not try a full re-install, what could go wrong". 🤷‍♂️ 

```
❯ tea --sync
fetching pantries…



panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Acmd+failed%3A+1%3A+%2FUsers%2Fjohn.allen%2Fbin%2Fgit+clone+--bare+--depth%3D1+https%3A%2F%2Fgithub.com%2Fteaxyz%2Fpantry.core+%2FUsers%2Fjohn.allen%2F.tea%2Ftea.xyz%2Fvar%2Fpantries%2Fteaxyz%2Fpantry.core

----------------------------------------------------->> attachment begin
Error: cmd failed: 1: /Users/john.allen/bin/git clone --bare --depth=1 https://github.com/teaxyz/pantry.core /Users/john.allen/.tea/tea.xyz/var/pantries/teaxyz/pantry.core
    at run (file:///opt/tea.xyz/src/v0.21.0/src/utils/index.ts:212:34)
    at async Promise.all (index 0)
    at async clone (file:///opt/tea.xyz/src/v0.21.0/src/hooks/useSync.ts:114:9)
    at async file:///opt/tea.xyz/src/v0.21.0/src/hooks/useSync.ts:76:17
    at async lock (file:///opt/tea.xyz/src/v0.21.0/src/hooks/useSync.ts:52:16)
    at async install (file:///opt/tea.xyz/src/v0.21.0/src/hooks/useSync.ts:72:20)
    at async update (file:///opt/tea.xyz/src/v0.21.0/src/hooks/useSync.ts:152:12)
    at async sync (file:///opt/tea.xyz/src/v0.21.0/src/app.sync.ts:6:5)
    at async file:///opt/tea.xyz/src/v0.21.0/src/app.ts:26:9
<<----------------------------------------------------- attachment end
```

Just to be sure I tried on both ZSH and Fish shells.

I'm basically dead in the water at this point. Is there a straightforward option to revert?

**Comment by mxcl** [comment]
Hmm sorry about this. I'll try and figure it out. I always do a full reinstall after updating (just to be sure it all works!).

To be clear, you did `rm -rf ~/.tea` ?

**Comment by mxcl** [comment]
Is `/Users/john.allen/bin/git` a symlink to tea?

I added code to try and protect against this scenario (we shouldn’t use that `git` since it will then fail because there is no pantry yet). But maybe I didn't do it well enough.

**Comment by johnallen3d** [comment]
OK, I'm back in business thanks @mxcl!

- yes, I had done an `rm -rf ~/.tea`
- I have been using a shell script for `git` to wrap `tea --silent +git...` (could this be a default for symlinks?)
- For now I've `brew install git` and was able to get `tea --sync` to work
- re: shell magic. I did notice this time a helpful message telling me to start a new shell after `tea` insta. 👍

**Comment by mxcl** [comment]
> I have been using a shell script for git to wrap tea --silent +git...

Ah right. Yeah so in that case `tea` cannot know that this `git` will call itself. We could potentially add protections here. I'll give it some thought.

> (could this be a default for symlinks?)

Symlinks to `tea` are equivalent to `tea -- $*`

**Comment by johnallen3d** [comment]
I haven't taken a deep dive into the source but I think I conceptually understand how the symlinks work. What I'm wondering is, if there's any reason for the default behaviour not to be `tea --silent -- $*`?
