### ISSUE TITLE
fish command not found magic gives exit code `127`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#344]
fish doesn't return the exit code of tea, it always returns 127. This is a sub par experience for tea users. Can we work around this? If not, should we propose a change to the fish developers?

**Comment by mxcl** [comment]
Even worse, all output is pushed to stderr, even stdout. :/

**Comment by jhheider** [comment]
Looks like they might be [amenable to a patch](https://github.com/fish-shell/fish-shell/issues/7902), if they can be convinced it won't break every fish thing everywhere.

The fact that zsh/bash don't take such drastic measures should be reassuring. I suppose a very good PR would add an entirely new hook (`command_not_found_handle_noerror()`?) which allow you and the other posters on that thread to do what you need without breaking existing behavior.

**Comment by mxcl** [comment]
Would we be willing to write the patch? I don't have time RN, so really my question is: you wanna? If so we can offer and see if they'll accept.

**Comment by jhheider** [comment]
Doesn't hurt to look.

**Comment by jhheider** [comment]
Submitted to fish for fish. I'll add a patch to our fish, [it's small](https://github.com/jhheider/fish-shell/commit/487c272267f1d2d6a5d3e303ccc5f88da266042a.diff). We might want to add a note in `teaxyz/setup:install.sh` noting the current behavior of fish, and the fact that our version is patched.
