### ISSUE TITLE
Rewrite tea commands (sudo foo -> sudo tea foo, etc)

### ISSUE THREAD

**Issue by lino-levan** [teaxyz/cli#348]
Maybe I'm misunderstanding something, so feel free to let me know if there is reasoning for this. If this isn't desirable, feel free to close.

If I run a command with tea magic enabled (I'm trying to use helix for text editing), it will work magically with no issues. If I run the same command with sudo, it errors out with command not found.

This works
```bash
$ hx
Opening helix...
```

This doesn't work
```bash
$ sudo hx
sudo: hx: command not found
```

**Comment by lino-levan** [comment]
This may be a system configuration issue. Will close after investigation.

**Comment by mxcl** [comment]
so we *could* make this work by making `sudo` a function that changes it to `sudo foo` to `sudo tea foo` I'm considering the same for some other common utilities like `man foo` and `which foo`

**Comment by lino-levan** [comment]
Should I reopen then? That sounds interesting.

**Comment by mxcl** [comment]
Yeah I think we need to do this in order for magic to not be surprising in its failures.

However security considerations exist…

**Comment by mxcl** [comment]
We need to refuse to do this if tea is not installed in a root only place with root only perms

**Comment by lino-levan** [comment]
That makes sense to me

**Comment by mxcl** [comment]
I think this is just too dangerous.

`sudo tea foo` seems like a reasonable requirement. Ultimately tea is a user-level tool and should not jump the sudo barrier automatically.
