### ISSUE TITLE
panic:no bottle available for +npmjs.com^8.1.2

### ISSUE THREAD

**Issue by firstclown** [teaxyz/cli#357]
When attempting to run `tea +nodejs.org^16.13.1 +npmjs.com^8.1.2 npm --version`, I get

```
resolving package graph
{ project: "npmjs.com", constraint: ^8.1.2, version: undefined }

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3Ano+bottle+available

----------------------------------------------------->> attachment begin
Error: no bottle available
    at resolve (file:///opt/tea.xyz/src/v0.22.1/src/prefab/resolve.ts:30:23)
    at async install (file:///opt/tea.xyz/src/v0.22.1/src/hooks/useExec.ts:95:38)
    at async default (file:///opt/tea.xyz/src/v0.22.1/src/hooks/useExec.ts:71:25)
    at async file:///opt/tea.xyz/src/v0.22.1/src/app.ts:37:63
<<----------------------------------------------------- attachment end
```

## Trouble shooting

I looked at the npm github project and there is an 8.1.2 version: https://github.com/npm/cli/releases/tag/v8.1.2
And it does match the format from the package.yml pantry file for the npmjs.com project `https://github.com/npm/cli/archive/refs/tags/v8.1.2.tar.gz`.

I am on Ubuntu WSL. I have neither node nor npm installed locally.

**Comment by firstclown** [comment]
Looks like it's not listed in the versions.txt file: https://dist.tea.xyz/npmjs.com/linux/x86-64/versions.txt

Feels now like a pantry.core issue (I was just following what the cli told me to do.) But I also don't see how the version.txt files are generated. Could I get a point in the direction of where that can be updated?

**Comment by mxcl** [comment]
Just improved this error! I can manually run the build for that for you. /cc @jhheider

**Comment by jhheider** [comment]
So. I can fix the npm build script so ^8 builds ok (requires `--install-links`), but we have a current issue where there's _some kind_ of segfault in node^19 only for linux+x86-64, which means this won't help @firstclown (today). I'm exploring options for node^19, but I might just yank the versions that are statically built which don't seem to fix the issue. That should/might resolve all the open npmjs.com issues. Stay tuned. I'll update as soon as we have a build of npmjs.com^8.1.2 up.

**Comment by jhheider** [comment]
Ok, I've pulled the static-built linux+x86-64 node versions (19.5.0, 19.6.0, and 18.14.0). I'll rebuild any that will rebuild successfully. npmjs.com^8.1.2 (currently 8.19.3) is bottled and uploaded for all arches. So, I consider this resolved (but let me know if it's not) and I'll go back to figuring out what's up with node>=19.3.

**Comment by firstclown** [comment]
Worked beautifully. Thanks so much!
