### ISSUE TITLE
`exec bash` doesn't work.

### ISSUE THREAD

**Issue by rokejulianlockhart** [teaxyz/cli#358]
Per https://github.com/teaxyz/cli#teacli-0222, the correct package should install when I invoke a binary provided by an absent package.

```
rokejulianlockhart@localhost:~> sh <(curl https://tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13558  100 13558    0     0  14385      0 --:--:-- --:--:-- --:--:-- 14377
                                        
  hi 👋 let’s set up tea
  
  • we’ll put it here:  /home/rokejulianlockhart/.tea 
  • everything tea installs goes there
  • (we won’t touch anything else)
  
  │ docs https://github.com/teaxyz/cli#getting-started

  k, we installed  /home/rokejulianlockhart/.tea/tea.xyz/v0.22.1/bin/tea 

  
  may we interest you in some magic?
  
  tea’s shell magic is optional but it’s the way it’s meant to be used.
  
  │ docs https://github.com/teaxyz/cli#magic

  Added:
  
   test -d "$HOME/.tea" && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash --silent) 

  
  you’re all set!
  
  try it out:
  
   exec bash   # or open a new tab
   wget -qO- tea.xyz/white-paper | glow - 

rokejulianlockhart@localhost:~> krita
If 'krita' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf krita
rokejulianlockhart@localhost:~>
```

Is [whatever provides `cnf`](https://forums.opensuse.org/t/why-does-zypper-se-provides-match-exact-not-operate-as-i-expect/164183) preventing this, perhaps?

**Comment by jhheider** [comment]
it doesn't look like you did `exec bash   # or open a new tab`. you have other options to load magic into your running shell: `source ~/.bashrc` or `source <(~/.tea/tea.xyz/v"*"/bin/tea --magic=bash --silent`.

if you _did_ do that, then it *is* possible `cnf` is conflicting. although I also don't see any package in our pantry that provides `krita` at present. so, that would need to be packaged.

**Comment by rokejulianlockhart** [comment]
I chose to add the “bash magic” in the basic graphical installer. That's probably why it's not in the terminal log.

**Comment by rokejulianlockhart** [comment]
I just realized that something might be seriously wrong, per https://github.com/teaxyz/cli#troubleshooting.

```
rokejulianlockhart@localhost:~> tea
If 'tea' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf tea
rokejulianlockhart@localhost:~> sh <(curl -Ssf https://tea.xyz)
  
  hi 👋 let’s set up tea
  
  • we’ll put it here:  /home/rokejulianlockhart/.tea 
  • everything tea installs goes there
  • (we won’t touch anything else)
  
  │ docs https://github.com/teaxyz/cli#getting-started

  
  you’re all set!
  
  try it out:
  
   exec bash   # or open a new tab
   wget -qO- tea.xyz/white-paper | glow - 

rokejulianlockhart@localhost:~> tea
If 'tea' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf tea
rokejulianlockhart@localhost:~>
```

I feel like I've done something stupid. Is `tea` just refusing to install?

**Comment by jhheider** [comment]
Have you started a new shell or otherwise sourced the `tea` magic?
```sh
try it out:
  
   exec bash   # or open a new tab
```

**Comment by rokejulianlockhart** [comment]
@jhheider, `exec bash` does nothing. It doesn't even merely appear to do nothing, since invoking `exit` demonstrates that it didn't spawn a new shell:
```
rokejulianlockhart@localhost:~> exec bash
rokejulianlockhart@localhost:~> exit
exit
Script done.
rokejulianlockhart@localhost:~>
```
(I had previously invoked `script -a`.)

However, invoking a new `bash` shell does allow `tea` to work.

Have you considered automatically invoking a new shell (of the system default, per https://stackoverflow.com/a/16375583/9731176, rather than hardcoding `bash`).

**Comment by jhheider** [comment]
Well, it doesn't quite hardcode bash. It does a bit of work to try and figure out exactly which shell you're running. Using the system default is one of the fallbacks: https://github.com/teaxyz/setup/blob/73a4e8f1ae80a8e0c53bca91d420a7051acefd70/install.sh#L388-L402

**Comment by rokejulianlockhart** [comment]
@jhheider, do you know how I can search the pantry for small packages to test the auto installation capability with? I imagine that this problem was merely a combination of me not spawning a new shell and no package for `krita` existing, but I'd like to verify.

**Comment by jhheider** [comment]
Sure. You can look at https://github.com/teaxyz/pantry.core and pantry.extra, or look in ~/.tea/tea.xyz/var/pantry/projects. Some small stuff might be `bat`, `jq`, or `broot`.

**Comment by rokejulianlockhart** [comment]
Yep, it works, and works gorgeously. Incredible. Thanks loads.

**Comment by jhheider** [comment]
No problem!

**Comment by rokejulianlockhart** [comment]
I've realized that the actual problem is that `exec bash` didn't work, so I've modified the title to reflect that, since this isn't the place for assistance (despite your brilliant help). 

btw, https://github.com/teaxyz/cli/discussions/359#discussion-4822157 😅

**Comment by mxcl** [comment]
`exec` replaces the current process with the parameter to `exec` which is why `exit` appears to not work.

Maybe `exec bash` is no good because it doesn't reload `.bashrc` and thus we should in fact be putting the magic in the other file that bash uses? or doing `exec bash -I`? I'll have to look into this a little more.

**Comment by jhheider** [comment]
`source ~/.bashrc` I believe.

**Comment by rokejulianlockhart** [comment]
I feel rather embarrassed, since some commits appear to have been made regarding this, but the problem appears to be that I invoked `exec bash` rather than `exec bash -i`, as instructed...

I hope that this doesn't invalidate your work. I need to learn to read.

**Comment by mxcl** [comment]
@rokejulianlockhart au contraire! The instructions *were* `exec bash` I only changed it to `exec bash -i` due to your bug report! Thank you so much for helping us to correct this.
