### ISSUE TITLE
Some packages install to `{{prefix}}/sbin`

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#365]
Some have both `/bin` and `/sbin` and some only the latter (unbound.net, by default, for example). Should we support `{{prefix}}/sbin` PATH injection, ignore entirely, or move them to `{{prefix}}/bin` (currently unbound.net).

**Comment by magnusviri** [comment]
As an admin I thought I'd put in my 2 cents that I would rather watch sbin then move something from sbin to bin. sbin is in the PATH, so watching it would be natural.

**Comment by jhheider** [comment]
> As an admin I thought I'd put in my 2 cents that I would rather watch sbin then move something from sbin to bin. sbin is in the PATH, so watching it would be natural.

Does this hold true for `$(tea --prefix)/unbound.net/v\*/sbin/unbound-host` vs. `$(tea --prefix)/unbound.net/v\*/bin/unbound-host`? I'm not certain that nuance is meaningful in a `tea`-style environment.

**Comment by magnusviri** [comment]
There's a 20-year-old [open source project](https://github.com/Radmind/radmind) that is now abandoned and somehow its corpse landed in my 10 acres (I guess since I used it a lot--but not anymore). Anyway, it puts binaries in bin and sbin, and the division is very logical. The bins' are things the admins run, the sbin is the server process, radmind. The server process should be autostarted, but it can also be started manually (like httpd, dhcpd, crond, etc). I've thought about trying to package it up with tea and if I did that, I would want the division between sbin and bin. I think anyone who actually decided to put something in sbin did it for some reason, and I think it would be best to go with what they decided.  Hopefully they knew what they were doing.

**Comment by jhheider** [comment]
I think this is true for OS package managers; do you think it's true for `tea`? Say we do add things to `{{prefix}}/sbin` or both `{{prefix}}/bin` and `{{prefix}}/sbin`. Should `{{prefix}}/sbin` be "considered" by `tea` magic? Maybe the answer is `if(Deno.env.get("PATH").split(":").contains("/sbin")`?

**Comment by magnusviri** [comment]
Yes, something like that. All package managers that I know of respect the division between bin and sbin. Here's [how brew packages dhcpd](https://github.com/Homebrew/homebrew-core/blob/fea3233bc2c2b9cf0b312c9ee42302d461a07599/Formula/isc-dhcp.rb).

**Comment by jhheider** [comment]
Right. That point is clear. I'm just trying to be convinced that the difference is meaningful in a `tea` context. Another question: what if I link something that's in `{{prefix}}/sbin` to `/usr/local/bin`? Caveat emptor?

The reason it's not clear to me at the outset is that `tea`'s methodology is so fundamentally different. Since we inject all the tools into your path contextually, does a difference remain between things packaged into bin vs. sbin that is interesting? We expect the user(s) not to introspect the bottles (unless they need to, of course). I can argue it both ways; perhaps this is just a case of "do as little as possible."

**Comment by magnusviri** [comment]
I don't know. My Unix-y orthodoxy instincts just keep saying to me that putting sbin's in bin is just heresy and should be punished with flogging. It's probably a purist Unix thing. I've got a lot of computer science greybeard idolization going on and I believe a bunch of things and I don't even know why. I think they created it a certain way and so it's oh-so-important to me. But maybe Dennis Richie and Ken Thompson would say go for it. So I'm not really an expert on this issue. I'm an expert at my attitude, which I think is probably shared by a lot of half-informed UNIX purists like me! :D I guess that's the only reason I'm chiming in. Some people will be very opinioned, right or not. So whatever you decide, I'd be prepared to defend the decision against people who can get all uptight over things like this, like maybe the type of people who argued over vi and emacs.

**Comment by magnusviri** [comment]
I guess my point is that I actually don't have a strong argument against it, other than what I think the "elders" intended.

**Comment by jhheider** [comment]
> I've got a lot of computer science greybeard idolization going on and I believe a bunch of things and I don't even know why.

I'm right there with you, which is why "don't rock the boat" is probably the right answer. That said, the distinction is much softer in `tea` than it is in modern linux distros, and it's already pretty soft, imo.

**Comment by mxcl** [comment]
We merged and released this.
