### ISSUE TITLE
Companions are not auto-installed anymore & show versions available if error is no version is available

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#368]
I know pip is packaged separately so I added it to the environment. It's not a huge deal, but it would be cool if the tea magic could add pip. It's probably a bigger problem to solve than is worth the time at this point, and it's not the point of this issue.

```
> tea +pip.pypa.io python -m pip install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

I tried the Brew version and it worked, but it was Python 3.10.9. So I tried using the tea version of 3.10 but I obviously don't know how to do it.

```
> tea +python.org@3.10 python --version
Python 3.11.1
> tea +python.org^3.10 python --version
Python 3.11.1
> tea +python.org=3.10 python --version
resolving package graph
error: not-found: pkg.version (spilt-tea-004)
we haven’t packaged this version. but we will… *if* you open a ticket:

    https://github.com/teaxyz/pantry.core/issues/new
> tea +python.org@3.10.0 python --version
Python 3.11.1
> tea +python.org^3.10.0 python --version
Python 3.11.1
> tea +python.org=3.10.0 python --version
resolving package graph
error: not-found: pkg.version (spilt-tea-004)
we haven’t packaged this version. but we will… *if* you open a ticket:

    https://github.com/teaxyz/pantry.core/issues/new
> tea +python.org=3.10.9 python --version
resolving package graph
error: not-found: pkg.version (spilt-tea-004)
we haven’t packaged this version. but we will… *if* you open a ticket:

    https://github.com/teaxyz/pantry.core/issues/new
> tea +python.org=3.10.8 python --version
Python 3.10.8
```

Here's the real request. Could the error be changed to show how to use the versioning system and include a list of versions that are packaged?

When I specified the correct version it worked. This means torch isn't packaged for python 3.11.

```
tea +python.org=3.10.8 +pip.pypa.io python -m pip install torch
Collecting torch
  Using cached torch-1.13.1-cp310-none-macosx_11_0_arm64.whl (53.2 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.13.1 typing-extensions-4.4.0
```

**Comment by mxcl** [comment]
You're after `~`.

```sh
$ tea +python.org~3.10 python --version
Python 3.10.8
```

We use the symbols defined by semver.org. `@` is not officially recognized, but is common, so we support it. I guess we should interpret `@` as `~` which is what you are looking for. I tried to figure out what `@` means. It's not an official semver spec.

>  it would be cool if the tea magic could add pip

We actually consider pip a “companion” to python and auto add it to the env, but this feature regressed. I'll fix it.

> Here's the real request. Could the error be changed to show how to use the versioning system and include a list of versions that are packaged?

Probably. I don’t consider this kind of DX worth improving pre-1.0 as we may just throw away how everything works.

Certainly excellent error messages are a goal, we just have to get there organically.

----

@jhheider can you please package all versions of things like python (it's twice this week now people are chasing specific versions of things and we do claim we support that).

**Comment by jhheider** [comment]
what do you mean by "all versions" specifically? that could be nearly infinite build time.

**Comment by mxcl** [comment]
> what do you mean by "all versions" specifically? that could be nearly infinite build time.

we need everything released within the last year and then last couple years probs.

Or you could make it so when it fails to find a version it outputs which versions are available.

Your choice.

**Comment by mxcl** [comment]
pip is now (once again) automatically added to the env when using python since 0.24.4

**Comment by jhheider** [comment]
> we need everything released within the last year and then last couple years probs.
> 
> Or you could make it so when it fails to find a version it outputs which versions are available.
> 
> Your choice.

Obviously we should do the second regardless. We should make a plan for the first. Probably a tea-script to analyze each package, check the github api, produce the versions, compare against dist, then we can start feeding them to the new-versions job at a pace that doesn't make us insane.

**Comment by mxcl** [comment]
certainly the second means the first is much less urgent.
