### ISSUE TITLE
I get `bad-yaml` error for real packages that I know to be in the pantry

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#372]
These packages have not been previously installed. Both work correctly with the long-form `tea +pkg pkg`
```sh
$ sl
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.3/src/hooks/usePantry.ts:133:31)
```

```sh
$ xc system
error: Uncaught (in promise) Error: bad-yaml
    if (!isArray(node)) throw new Error("bad-yaml");
                              ^
    at Object.getProvides (file:///opt/tea.xyz/src/v0.22.3/src/hooks/usePantry.ts:133:31)
```

tea v0.22.3

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry.extra/blob/cf6e7089d165c9a07c1091835fe99af04427d92c/projects/github.com/google/brotli/package.yml#L19-L20

not an array; triggering https://github.com/teaxyz/cli/blob/12f482cf8ffaa99f646317513ca1230e113f9391/src/hooks/usePantry.ts#L149-L153

**Comment by jhheider** [comment]
`tea -S`

**Comment by mxcl** [comment]
yeah this was my bad.

However, I have a fix locally that stops it bailing (in this kind of circumstance) for bad YAML.
