### ISSUE TITLE
TopPackages

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#375]
<img width="583" alt="Screenshot 2023-02-11 at 12 26 13 PM" src="https://user-images.githubusercontent.com/7913978/218239796-62b20bc4-86d6-46f1-9be6-6f243d68197b.png">

Put ListAction component inside TopPackages component.
Create TopScripts component too to encapsulate w/ mock scripts

**Comment by getneil** [comment]
Top Package can just be a category for now in Airtable

**Comment by mxcl** [comment]
What repo was this meant for @getneil ?
