### ISSUE TITLE
Codesign Mac binaries

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#376]
Either code sign the binaries here (probs better since less points of failure) or (somehow) extract and re-tar the tea.xyz bottles after they are published for the binaries we provide via `https://tea.xyz/$platform/$arch`.

Edit: in fact, we have to code sign here since we attach the binaries to releases.

A better ordering may be to just use our binaries in the tea.xyz pkg. But that requires some thought if we are going to generally do that. We should always provide a build script for our users to use if they like. And thus we should always test the build script works each release.

Using the vendor’s binaries is good IMO. Provided they sign them.

**Comment by jhheider** [comment]
Can probably extract the signing into a callable workflow: https://github.com/teaxyz/pantry.core/blob/4ab112c592e09cd8f61b2d402f82c6059d3a2062/.github/workflows/bottle.yml#L80-L115

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry.core/blob/61426ebcb160dbf6ae0a34ebc09f9e4ec1b9a5f8/.github/workflows/bottle.yml#L80-L91 makes an action you can use; the only caveat is that it's part of pantry.core, so it looks for libs (*.so and *.dylib) and bins under $path/bin. So, if you build the bins to, say, `out/bin` you should be able to sign with.path = "out".

We can generalize it more, obviously, and move it to its own repo if you want to use it more easily across repos without having to checkout pantry.core.

**Comment by mxcl** [comment]
you can do `- uses: teaxyz/pantry.core/foo/bar@whatever`

**Comment by jhheider** [comment]
> you can do `- uses: teaxyz/pantry.core/foo/bar@whatever`

Ah, I think I tried teaxyz/pantry.core/.github/actions/whatever@main without success.

Of course, I also wasn't on main. Hm. Should be able to simplify.

**Comment by jhheider** [comment]
Hopefully trivial now.

**Comment by jhheider** [comment]
I think https://github.com/teaxyz/cli/blob/sign-binaries/.github/workflows/test-sign.yml will prove it works, but it's gated behind https://github.com/teaxyz/setup/issues/142
