### ISSUE TITLE
`PCRE` has a maintained and unmaintained version with two different repositories but same identifier

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#392]
- PCRE2 starts at semver v10
- PCRE (unmaintained) goes up to 8.45

despite PCRE being unmaintained, most stuff still uses it, lol

We have packaged already `pcre~8.45` here: https://github.com/teaxyz/pantry.core/blob/main/projects/pcre.org/package.yml

However, nginx requires `pcre2^10.40` https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/#sources

## Suggestion

Currently we have `pcre.org/package.yml` for `pcre~8.45`. 

Going forward: 
- move `pcre~8.45` to `pcre.org/pcre/package.yml`
- add `pcre2` to `pcre.org/pcre2/package.yml`

**Comment by mfts** [comment]
somewhat related to #383

**Comment by mfts** [comment]
I think that's a safe way of doing it because the binaries for `pcre2` are prefixed with `pcre2*`

**Comment by mfts** [comment]
made a draft for pcre2 https://github.com/teaxyz/pantry.extra/pull/416

**Comment by mxcl** [comment]
since these have unique release versions, I'd rather a single formula.

however since we can't do that easily yet a separate formula is ok.

**Comment by mxcl** [comment]
we can combine them later

**Comment by mfts** [comment]
https://github.com/teaxyz/pantry.extra/pull/416 passes CI and is complete. However, `nginx` worked with the old / unmaintained version of `pcre` so I actually didn't need this. 

However, it's already built so I also don't wanna waste the package. 

If we merge it I would need to move the current `pcre.org/package.yml` to `pcre.org/pcre/package.yml`, which is on the `pantry.core` branch.   

Should I open a PR on pantry.core to do this? @mxcl

**Comment by mxcl** [comment]
I guess let me do the work to make some kind of versioning inside the yamls.

**Comment by mxcl** [comment]
we merged it as a separate package.yml
