### ISSUE TITLE
question: confusion around install command

### ISSUE THREAD

**Issue by lino-levan** [teaxyz/cli#393]
Currently, tea recommends `sh <(curl https://tea.xyz)`

Does this have any advantages over `sh =(curl https://tea.xyz)` (in zsh)

or `curl https://tea.xyz | sh` (basically universally)?

I'm mainly asking because afaik `curl https://tea.xyz | sh` works in sh, bash, zsh, fish, and nushell (from #273) and I don't see the advantage to the other syntax given that it isn't universal and is the same amount of characters to type.

**Comment by jhheider** [comment]
IIRC, it's because `(curl https://tea.xyz | sh) duf` isn't valid, but `sh <(curl https://tea.xyz) duf` (or any other command) is due to process substitution. There might be other differences I'm not expressly recalling atm.

**Comment by lino-levan** [comment]
Ah okay, thanks for clearing things up. I forgot about that feature of tea.

**Comment by mxcl** [comment]
We certainly could use `=(foo)` but `<(foo)` works in bash as well.

But yeah what we want is an easy to remember install line that is as portable as possible.

```
curl tea.xyz | sh -s duf
# ^^ more portable but not as easy to remember or as readable IMO
```
