### ISSUE TITLE
can't build python package from source

### ISSUE THREAD

**Issue by ddobrinskiy** [teaxyz/cli#396]
When trying to build [virtualenv](https://github.com/pypa/virtualenv) from source, I get the following error:

```markdown
      LookupError: Error getting the version from source `vcs`: setuptools-scm was unable to detect version for /home/david/proj/pkgdev/pantry.extra/tea.out/virtualenv.pypa.io/src-v20.18.0.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

This issue is more of an FYI, rather than me looking for support.

Depending on your vision for tea, this may go on the backlog for extending the build options.

Otherwise there is always the option to fall back on `python-venv.sh` that installs the package from https://pypi.org/, but not from source.

**Comment by ddobrinskiy** [comment]
Steps to reproduce: use `pip install  .` in your build script instead of `python-venv.sh`, example: [3833cf8](https://github.com/ddobrinskiy/pantry.extra/commit/cb5d747e8c434e0722585d99f659a8a7004cd29a#diff-03dad3781494cacbc87a0b6985546f4a25a44aedc676be44f4ebff616986448fR17)

**Comment by mxcl** [comment]
This smells like a pure source tarball vs. a massaged one for building from source. I note brew uses a different URL source for the sources:

https://github.com/Homebrew/homebrew-core/blob/2d11c0ec532057c5ada218a57d086efaa3382a05/Formula/virtualenv.rb

And they still install via a virtual-env so our equivalent would be the venv script

**Comment by mxcl** [comment]
K this is fixed in brewkit itself.
