### ISSUE TITLE
python-venv.sh does not respect the package version

### ISSUE THREAD

**Issue by ddobrinskiy** [teaxyz/cli#397]
https://github.com/teaxyz/brewkit/blob/main/share/brewkit/python-venv.sh#L21

`python-venv.sh` always installs the **latest** version from PyPi, not the version specified for our desired package

Current code:

```bash
./pip install "$CMD_NAME"
```

Correct code: (approximation)

```bash
./pip install "$CMD_NAME=={{version}}"
```

**Comment by mxcl** [comment]
lol, whoops. Easy fix tho.
