### ISSUE TITLE
QoL: ignore blank lines in `versions.txt`

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#398]
Sadly, hand-editing a `versions.txt` file requires using `hexedit` to remove the trailing `\x0a` from the file, otherwise it reports "version too short to be parsed without `v`". It seems like it should ignore the blank line, but only affects us.

**Comment by mxcl** [comment]
I'm afraid I will need more context than “it”

**Comment by jhheider** [comment]
Lol, sorry. If you have a trailing \x0a in, for example, /nodejs.org/darwin/aarch64/versions.txt, then `tea +nodejs.org${any or no version spec}` will report "too short to parse without a \`v\` prefix: ${input}"

**Comment by mxcl** [comment]
where did you see this? I can't see how this line can fail like that:

```js
let versions = releases.split("\n").map(x => new SemVer(x))
```

**Comment by mxcl** [comment]
I guess you're saying you saw it with `tea +nodejs.org${any or no version spec} ` but like… how can this line fail like that?

**Comment by mxcl** [comment]
Oh this is JS split being shit. K fix coming up.
