### ISSUE TITLE
clean up on CTRL-C during installation

### ISSUE THREAD

**Issue by regrowr** [teaxyz/cli#402]
I have a README.md with the following:
```
# Dependencies

| Project             | Version |
|---------------------|---------|
| python.org          | ~3.10   |
| pypa.github.io/pipx | =1.1.0  |
EOF
```

The resulting python version is as expected:
```
$ python --version
Python 3.10.8
```

Running pipx in this dev env fails:
```
$ pipx
/Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/pipx: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/libexec/pipx: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/python: bad interpreter: No such file or directory
/Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/pipx: line 15: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/libexec/pipx: Undefined error: 0
```

The python interpreter referenced above is a link:
```
$ ls -l ~/.tea/pypa.github.io/pipx/v1.1.0/bin/python
lrwxr-xr-x@ 1 robert  staff  43 26 Feb 17:21 /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/python -> /Users/robert/.tea/python.org/v3/bin/python
```

But the python dependency is only found here:
```
/Users/robert/.tea/python.org/v3.10.8/
```

Possibly this is because [pipx](https://github.com/teaxyz/pantry.extra/blob/main/projects/pypa.github.io/pipx/package.yml) is packaged with a dependency on python 3:

```
dependencies:
  python.org: 3
  pip.pypa.io: '*'
```

Note that changing the python dependency in the README.md to match:
```
| python.org          | ~3   |
```

does not rectify the situation as it results in python being found in:
```
/Users/robert/.tea/python.org/v3.11.1
```

**Comment by mxcl** [comment]
Do you not have a symlink at `/Users/robert/.tea/python.org/v3`?

If so then that's curious, and a bug. The solution would be to rm -rf python and have tea re-extract and link it (`tea python` would do)

**Comment by rl-0x000** [comment]
> Do you not have a symlink at `/Users/robert/.tea/python.org/v3`?

No.

> 
> If so then that's curious, and a bug. The solution would be to rm -rf python and have tea re-extract and link it (`tea python` would do)

Interesting. 
After the rm rf python and re-running `tea --env && cd .` it did create additional symlinks:

```
v*      v3      v3.10   v3.10.8
```

Not sure how it got into that state, but I'll see if I can repro.

**Comment by regrowr** [comment]
> Do you not have a symlink at `/Users/robert/.tea/python.org/v3`?

No.

> 
> If so then that's curious, and a bug. The solution would be to rm -rf python and have tea re-extract and link it (`tea python` would do)

Interesting. 
After the rm rf python and re-running `tea --env && cd .` it did create additional symlinks:

```
v*      v3      v3.10   v3.10.8
```

Not sure how it got into that state, but I'll see if I can repro.

**Comment by regrowr** [comment]
After some trial and error I can repro and it reflects what I recall happening at the time.

I required a 3.10x python and added it to the README.md, then I triggered the environment as shown below.

As it started to extract, I noticed tea hadn't picked up the change and was extracting the 3.11.1 version so I Ctrl-C'd.

That left a single v3.11.1 symlink in the .tea/python.org directory (no *, v3, v3.11).

Running pipx again appeared to complete the setup, but tea did not detect that not all the required symlinks existed in .tea/python.org so pipx failed.

```
$ pipx
python.org=3.11.1 extracting
^C

$  ls ~/.tea/python.org
v3.11.1

$ pipx
installed: ~/.tea/pip.pypa.io/v23.0.1
installed: ~/.tea/pypa.github.io/pipx/v1.1.0
/Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/pipx: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/libexec/pipx: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/python: bad interpreter: No such file or directory
/Users/robert/.tea/pypa.github.io/pipx/v1.1.0/bin/pipx: line 15: /Users/robert/.tea/pypa.github.io/pipx/v1.1.0/libexec/pipx: Undefined error: 0
```

Perhaps tea could catch the SIGINT signal and clean up before exiting?

**Comment by mxcl** [comment]
> As it started to extract, I noticed tea hadn't picked up the change and was extracting the 3.11.1 version so I Ctrl-C'd.
>
> That left a single v3.11.1 symlink in the .tea/python.org directory (no *, v3, v3.11).

aah ok. Yes, not cleaning up is a bug.
