### ISSUE TITLE
tea parsing deps incorrectly

### ISSUE THREAD

**Issue by ddobrinskiy** [teaxyz/cli#403]
The following command falls back to an already-installed python 3.11

❯ tea +pipenv.pypa.io +python.org~**3.9** sh

this is a temporary shell containing the following packages:
invisible-island.net/ncurses=6.4.0, curl.se/ca-certs=2022.7.19, gnu.org/readline=8.1.0, zlib.net=1.2.13, sourceware.org/bzip2=1.0.8, openssl.org=1.1.1s, sourceware.org/libffi=3.4.4, libexpat.github.io=2.5.0, bytereef.org/mpdecimal=2.5.1, tukaani.org/xz=5.2.7, sqlite.org=3.40.0, **python.org=3.11.1**, pipenv.pypa.io=2023.2.4

However, if I switch the order of the deps, it all works as expected:

❯ tea +python.org~**3.9** +pipenv.pypa.io sh
installed: ~/.tea/python.org/v3.9.16
this is a temporary shell containing the following packages:
invisible-island.net/ncurses=6.4.0, curl.se/ca-certs=2022.7.19, gnu.org/readline=8.1.0, zlib.net=1.2.13, sourceware.org/bzip2=1.0.8, openssl.org=1.1.1s, sourceware.org/libffi=3.4.4, libexpat.github.io=2.5.0, bytereef.org/mpdecimal=2.5.1, tukaani.org/xz=5.2.7, sqlite.org=3.40.0, pipenv.pypa.io=2023.2.4, **python.org=3.9.16**

## more info:

- this is reproducible in an empty folder
- running on `tea 0.24.3`

**Comment by ddobrinskiy** [comment]
After deleting tea using `rm -rf $HOME/.tea` and installing the newest version `0.24.6`, the bug still persists:

```
❯ tea +pipenv.pypa.io +python.org~3.9 sh
installed: ~/.tea/sourceware.org/libffi/v3.4.4
installed: ~/.tea/libexpat.github.io/v2.5.0
installed: ~/.tea/bytereef.org/mpdecimal/v2.5.1
installed: ~/.tea/tukaani.org/xz/v5.2.7
installed: ~/.tea/sqlite.org/v3.40.0
python.org=3.11.1 downloading 13%
```

**Comment by ddobrinskiy** [comment]
Pipenv deps from the pantry: 

https://github.com/teaxyz/pantry.extra/blob/main/projects/pipenv.pypa.io/package.yml#L9-L10

```
dependencies:
  python.org: '>=3.7'
```

**Comment by mxcl** [comment]
I’ve confirmed that removing pipenv’s dependency on python fixes this, so something is up in `hydrate.ts` here. I'll fix shortly since this is awful :/

**Comment by mxcl** [comment]
k so confusingly I just wrote a new test to verify this:

```ts
it(suite, "hydrates.2", async function() {
  const pkgs = [
    { project: 'python.org', constraint: new semver.Range('~3.9') },
    { project: 'pipenv.pypa.io', constraint: new semver.Range('*') }
  ]

  const rv = await hydrate(pkgs, (pkg: PackageRequirement, _dry: boolean) => {
    if (pkg.project === 'pipenv.pypa.io') {
      return Promise.resolve([
        { project: 'python.org', constraint: new semver.Range('>=3.7') }
      ])
    } else {
      return Promise.resolve([])
    }
  })

  let nodes = 0
  for (const pkg of rv.pkgs) {
    if (pkg.project === 'python.org') {
      assertEquals(pkg.constraint.toString(), '~3.9')
      nodes++
    }
  }

  assertEquals(nodes, 1)
})
```

And this *passes*. So somewhere after the code that determines the pkg env is the problem :/
