### ISSUE TITLE
updating tea fails on fish

### ISSUE THREAD

**Issue by ddobrinskiy** [teaxyz/cli#422]
```
$ sh <(curl https://tea.xyz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13557  100 13557    0     0  36481      0 --:--:-- --:--:-- --:--:-- 37040
fish: Invalid redirection target:
sh <(curl https://tea.xyz)
   **^~~~~~~~~~~~~~~~~~~~~~**

david@Davids-MacBook-Air ~ % which git
/usr/bin/git
david@Davids-MacBook-Air ~ % which curl
/usr/bin/curl
david@Davids-MacBook-Air ~ % curl --version
curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
```

- Running on M2 Air via fish shell.
- Re-running it via zsh shell works successfully
- fish is installed via tea

**Comment by ddobrinskiy** [comment]
Oh ok, seems like this is actually expected behavior, since this syntax is not supported by fish

https://stackoverflow.com/a/48855746

**Comment by mxcl** [comment]
Yeah we did use to say “for fish instead do:” but in the end to keep instructions simpler I decided that if you use fish then you should be aware of the platform differences.

It would be nice to figure out a nice consistent syntax.
