### ISSUE TITLE
how to use a package locally if not yet merged in pantry?

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#427]
I had a discussion with @ddobrinskiy about testing / using a package locally that was built locally with `pkg` but not yet merged in the global pantry.

For example [`git3.sh`](https://github.com/teaxyz/pantry.extra/pull/457)

```sh
$ cd ~/pantry.extra
$ pkg build git3.sh
...
# builds binary successfully to tea.out/git3.sh

# open a new terminal in `cd $HOME`
$ TEA_PREFIX=~/pantry.extra/tea.out tea +git3.sh git3 --help
resolving package graph
error: not-found: pantry (spilt-tea-007)
no pantry: run `tea --sync`
```

### Expectation 
I expect that if I change the `TEA_PREFIX` to something where the package + binary already exists locally, it would work.

Interesting observation on what works:
```sh
$ cd ~/pantry.extra
$ TEA_PREFIX=~/dev/tea/pantry.extra/tea.out tea +git3.sh git3 --help
Usage: git3 [options] [command]

git3 mangement tool
...
```

**Comment by mxcl** [comment]
This isn't really a bug, there literally is no pantry in your `TEA_PREFIX`. You would need to set `TEA_PANTRY_PATH` if you expect it to work which is why stepping into the pantry directory fixes it (its dev-env sets the pantry path).

I understand the pain. Perhaps I will come up with something that eases this. For now you can do:

```sh
TEA_DIR=~/pantry.extra tea +git3.sh git3 --help
```

I will leave it as an exercise for the reader on why this works.

**Comment by mfts** [comment]
> Run `env | grep TEA_` and you will see why it works.
Ok, I understand why it works from the `pantry.extra` directory but not anywhere else. 

So setting these env variables, I expect it to work anywhere else


```sh
$ cd ~
$ TEA_PANTRY_PATH=/Users/mfts/dev/tea/pantry.extra tea git3 --help 
resolving package graph
error: http (spilt-tea-500)
403: https://dist.tea.xyz/git3.sh/darwin/aarch64/versions.txt

$ TEA_DIR=/Users/mfts/dev/tea/pantry.extra tea git3 --help 
tea: command not found: git3
``` 

I also tried it with both `TEA_PREFIX` and `TEA_PANTRY_PATH` 
```sh 
$ TEA_PANTRY_PATH=/Users/mfts/dev/tea/pantry.extra TEA_PREFIX=/Users/mfts/dev/tea/pantry.extra/tea.out tea git3 --help
resolving package graph
error: not found in pantry: nodejs.org (spilt-tea-005)

did you mean `nmap.org`? otherwise… see you on GitHub?

Not in pantry: nodejs.org

https://github.com/teaxyz/pantry.extra#contributing
```
`nodejs.org` is a runtime dep so I guess because it's in `pantry.core` and not pantry.extra, it's not found

but setting the pantry to both `pantry.extra` and the pantry from `.tea` where supposedly the `nodejs.org` should exist, the result is just **not found**
```sh
$ TEA_PANTRY_PATH=/Users/mfts/dev/tea/pantry.extra:/Users/mfts/.tea/tea.xyz/var/pantry TEA_PREFIX=/Users/mfts/dev/tea/pantry.extra/tea.out tea +nodejs.org git3 --help
tea: command not found: git3
``` 

I don't expect this to be a bug, just it would be a nice to have.

**Comment by ddobrinskiy** [comment]
Hmm, does not work with tea environments though:

```bash
❯ TEA_DIR=~/proj/pantry.extra tea +ansible.com ansible --version

resolving package graph
error: not found in pantry: ansible.com (spilt-tea-005)

did you mean `ordinals.com`? otherwise… see you on GitHub?

Not in pantry: ansible.com

https://github.com/teaxyz/pantry.extra#contributing

```

**Comment by mxcl** [comment]
Setting the TEA_DIR should work, otherwise it's a bug.

**Comment by mxcl** [comment]
Quite possibly setting an alternative `TEA_PREFIX` has no benefits. Worth considering. Then supplementing TEA_PANTRY_PATH would be enough to use working checkouts of the pantry and installs go to `~/.tea`

**Comment by mfts** [comment]
> Setting `TEA_DIR` should work, otherwise it's a bug.

Seems like it

```sh
$ TEA_DIR=/Users/mfts/dev/tea/pantry.extra tea git3 --help 
resolving package graph
error: http (spilt-tea-500)
403: https://dist.tea.xyz/git3.sh/darwin/aarch64/versions.txt
```

> you'll find that your solution is setting the same vars as the dev-env does.

Yes, I copied the `env | grep TEA_` pantry.extra's dev-env

**Comment by mxcl** [comment]
K I know why setting `TEA_DIR` doesn't work, it's because it changes `TEA_PREFIX` which the running tea cannot handle.

```
$ TEA_DIR=/Users/mfts/dev/tea/pantry.extra tea tea git3 --help 
# ^^ probably works lol
```

**Comment by mfts** [comment]
Unfortunately, same error

```sh
$ TEA_DIR=/Users/mfts/dev/tea/pantry.extra tea tea git3 --help 
resolving package graph
error: http (spilt-tea-500)
403: https://dist.tea.xyz/git3.sh/darwin/aarch64/versions.txt
```

**Comment by mxcl** [comment]
New brewkit and pantries (not all released), installs everything to your standard TEA_PREFIX with builds in the pantry checkout.

This means `TEA_PANTRY_PATH=pantry tea foo` will work (or `TEA_DIR=pantry tea foo`)

Which is only marginally better, but it is a solution to this anyway.

Potentially we could `cp` the package.yml after builds. I dunno. Smells bad.
