### ISSUE TITLE
Also add https://tea.xyz/ to About section

### ISSUE THREAD

**Issue by shalva97** [teaxyz/cli#432]
I think it would look better!

Also one more question regarding tea scripts. On the website it shows a link of https://github.com/teaxyz/hello-universe.sh, but when I go there, it shows 404

![image](https://user-images.githubusercontent.com/22417494/223823659-e36ee751-7f74-4ae5-aa7d-6acf815f7562.png)

------------

btw this tea tastes very good, thanks for making it.

waiting for Windows build. Currently using `winget` but I dont like it, For example, to install Git I have to write `git.git` or `mozilla.firefox`, why it can not be just `git` or `firefox`

**Comment by mxcl** [comment]
> waiting for Windows build. Currently using winget but I dont like it, For example, to install Git I have to write git.git or mozilla.firefox, why it can not be just git or firefox

Coming soon! We're excited about it too. Winget in our sights 🎯 :)

**Comment by mxcl** [comment]
> Also add https://tea.xyz/ to About section

Sorry, which about section?

**Comment by shalva97** [comment]
This one:
![Screenshot 2023-03-09 at 14 13 50](https://user-images.githubusercontent.com/22417494/223991017-2df4e4fa-2047-42ab-a4d3-256a77190764.png)

**Comment by mxcl** [comment]
Done. The reason it wasn't there is we link to tea.xyz in about 10 other places and it felt over kill to do it again, but whatever.
