### ISSUE TITLE
Error messages should be the same for consistency

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#439]
For consistency, the error messages should be the same

```sh
$ tea pkg inventory python.org
tea: command not found: pkg
```

```sh
$ tea +tea.xyz/brewkit pkg inventory python.org
error: not-found: dev-env (spilt-tea-006)
`/Users/mfts/dev/tea` is not a developer environment.

a developer environment requires the presence of a file or directory
that uniquely identifies package requirements, eg. `package.json`.
```

**Comment by jhheider** [comment]
Those are different errors, though. The first is that no `package.yml` provides `bin/pkg` (though that is likely in the cards for `brewkit`. The second is that you're not in a developer environment (pantry).

**Comment by mxcl** [comment]
First error is from `tea`, the second is from `pkg`, so yeah… why would the errors be the same?

I could just do a grep on the codebase and change all the error message for all error types to “please contact @mfts for details” if you like.
