### ISSUE TITLE
allow package.yml to specify that packages are specific to eg. only darwin

### ISSUE THREAD

**Issue by getneil** [teaxyz/cli#443]
<img width="1202" alt="Screenshot 2023-02-17 at 1 32 19 PM" src="https://user-images.githubusercontent.com/7913978/219557705-50b02647-faa9-4a95-af9b-83c87896360f.png">

I packaged create-dmg and it's suppose to work only in mac but it is being listed as bottled also for linux.
we did add a file in {{prefix}} for linux but probably we should enable a way to skip os/platform.

**Comment by mxcl** [comment]
this was implemented
