### ISSUE TITLE
Error loading magic in Fish

### ISSUE THREAD

**Issue by johnallen3d** [teaxyz/cli#447]
I upgraded to `0.25.1` this morning and when I have magic enabled I see the following error when starting a new Fish shell.

```fish
string: contains: invalid subcommand

- (line 5): 
if not string contains -q -r "^$HOME/.local/bin(:|\$)" $PATH
   ^
from sourcing file -
	called on line 69 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup

(Type 'help string' for related documentation)
```

I tried `rm -rf ~/.tea` and reinstalling.

My `config.fish` has the following:

```fish
test -d "$HOME/.tea" && "$HOME/.tea/tea.xyz/v*/bin/tea" --magic=fish --silent | source
```

**Comment by mxcl** [comment]
@jhheider any clue?

**Comment by jhheider** [comment]
I don't see contains in the docs. Maybe match?

https://fishshell.com/docs/current/cmds/string.html

**Comment by jhheider** [comment]
Quick test would be to change your magic line to

`test -d "$HOME/.tea" && "$HOME/.tea/tea.xyz/v*/bin/tea" --magic=fish --silent | sed -e 's/contains/match/g' | source`

And see if that's a fix.

**Comment by johnallen3d** [comment]
I can confirm @jhheider that this adjustment works. 👍

**Comment by mxcl** [comment]
what's concerning is our test for magic passes even though this error occurs :/
