### ISSUE TITLE
Tools aren't set up with a "sh <(...)" command

### ISSUE THREAD

**Issue by trentlarson** [teaxyz/cli#449]
This command doesn't put me into a shell with python available: `sh <(curl https://tea.xyz) +python.org`

```
$ sh <(curl https://tea.xyz) +python.org
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13557  100 13557    0     0  40920      0 --:--:-- --:--:-- --:--:-- 41585
TERMINFO=/usr/share/terminfo:$/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/share/terminfo
SSL_CERT_FILE=/Users/trent/.tea/openssl.org/v1.1.118/ssl/cert.pem
PATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/bin:/Users/trent/.tea/gnu.org/readline/v8.1.0/bin:/Users/trent/.tea/sourceware.org/bzip2/v1.0.8/bin:/Users/trent/.tea/openssl.org/v1.1.118/bin:/Users/trent/.tea/libexpat.github.io/v2.5.0/bin:/Users/trent/.tea/tukaani.org/xz/v5.2.7/bin:/Users/trent/.tea/sqlite.org/v3.40.0/bin:/Users/trent/.tea/python.org/v3.11.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/trent/Library/Android/sdk/emulator:/Users/trent/Library/Android/sdk/platform-tools
MANPATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/share/man:/Users/trent/.tea/gnu.org/readline/v8.1.0/share/man:/Users/trent/.tea/zlib.net/v1.2.13/share/man:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/share/man:/Users/trent/.tea/tukaani.org/xz/v5.2.7/share/man:/Users/trent/.tea/sqlite.org/v3.40.0/share/man:/Users/trent/.tea/python.org/v3.11.2/share/man:/usr/share/man:/opt/homebrew/share/man
PKG_CONFIG_PATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/lib/pkgconfig:/Users/trent/.tea/gnu.org/readline/v8.1.0/lib/pkgconfig:/Users/trent/.tea/zlib.net/v1.2.13/lib/pkgconfig:/Users/trent/.tea/openssl.org/v1.1.118/lib/pkgconfig:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/lib/pkgconfig:/Users/trent/.tea/libexpat.github.io/v2.5.0/lib/pkgconfig:/Users/trent/.tea/tukaani.org/xz/v5.2.7/lib/pkgconfig:/Users/trent/.tea/sqlite.org/v3.40.0/lib/pkgconfig:/Users/trent/.tea/python.org/v3.11.2/lib/pkgconfig
LIBRARY_PATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/lib:/Users/trent/.tea/gnu.org/readline/v8.1.0/lib:/Users/trent/.tea/zlib.net/v1.2.13/lib:/Users/trent/.tea/sourceware.org/bzip2/v1.0.8/lib:/Users/trent/.tea/openssl.org/v1.1.118/lib:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/lib:/Users/trent/.tea/libexpat.github.io/v2.5.0/lib:/Users/trent/.tea/bytereef.org/mpdecimal/v2.5.1/lib:/Users/trent/.tea/tukaani.org/xz/v5.2.7/lib:/Users/trent/.tea/sqlite.org/v3.40.0/lib:/Users/trent/.tea/python.org/v3.11.2/lib
LD_LIBRARY_PATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/lib:/Users/trent/.tea/gnu.org/readline/v8.1.0/lib:/Users/trent/.tea/zlib.net/v1.2.13/lib:/Users/trent/.tea/sourceware.org/bzip2/v1.0.8/lib:/Users/trent/.tea/openssl.org/v1.1.118/lib:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/lib:/Users/trent/.tea/libexpat.github.io/v2.5.0/lib:/Users/trent/.tea/bytereef.org/mpdecimal/v2.5.1/lib:/Users/trent/.tea/tukaani.org/xz/v5.2.7/lib:/Users/trent/.tea/sqlite.org/v3.40.0/lib:/Users/trent/.tea/python.org/v3.11.2/lib
CPATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/include:/Users/trent/.tea/gnu.org/readline/v8.1.0/include:/Users/trent/.tea/zlib.net/v1.2.13/include:/Users/trent/.tea/sourceware.org/bzip2/v1.0.8/include:/Users/trent/.tea/openssl.org/v1.1.118/include:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/include:/Users/trent/.tea/libexpat.github.io/v2.5.0/include:/Users/trent/.tea/bytereef.org/mpdecimal/v2.5.1/include:/Users/trent/.tea/tukaani.org/xz/v5.2.7/include:/Users/trent/.tea/sqlite.org/v3.40.0/include:/Users/trent/.tea/python.org/v3.11.2/include
XDG_DATA_DIRS=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/share:/Users/trent/.tea/gnu.org/readline/v8.1.0/share:/Users/trent/.tea/zlib.net/v1.2.13/share:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/share:/Users/trent/.tea/libexpat.github.io/v2.5.0/share:/Users/trent/.tea/tukaani.org/xz/v5.2.7/share:/Users/trent/.tea/sqlite.org/v3.40.0/share:/Users/trent/.tea/python.org/v3.11.2/share
DYLD_FALLBACK_LIBRARY_PATH=/Users/trent/.tea/invisible-island.net/ncurses/v6.4.0/lib:/Users/trent/.tea/gnu.org/readline/v8.1.0/lib:/Users/trent/.tea/zlib.net/v1.2.13/lib:/Users/trent/.tea/sourceware.org/bzip2/v1.0.8/lib:/Users/trent/.tea/openssl.org/v1.1.118/lib:/Users/trent/.tea/sourceware.org/libffi/v3.4.4/lib:/Users/trent/.tea/libexpat.github.io/v2.5.0/lib:/Users/trent/.tea/bytereef.org/mpdecimal/v2.5.1/lib:/Users/trent/.tea/tukaani.org/xz/v5.2.7/lib:/Users/trent/.tea/sqlite.org/v3.40.0/lib:/Users/trent/.tea/python.org/v3.11.2/lib
LDFLAGS=-Wl,-rpath,/Users/trent/.tea
TEA_PREFIX=/Users/trent/.tea
```

* The path afterward is still my default path of `/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/trent/Library/Android/sdk/emulator:/Users/trent/Library/Android/sdk/platform-tools`.

* If I paste all that environment variable output then python is available in my path. (However I'm not sure it's entirely correct since some later `pip install` commands fail.)

* It seems like this used to work, and didn't spit out all the environment variables (though I admit I haven't tried this for a few weeks and I'm still not entirely sure how to use this because each time I try for a new project I have issues).

* Special thanks to @sanchitram1 for https://github.com/teaxyz/cli/issues/444 because that's where I learned about `tea python` and `tea +python.org +pip.pypa.io sh`. My symptoms are different because both of those commands work for me.

**Comment by mxcl** [comment]
```
sh <(curl https://tea.xyz) +python.org sh
```

You missed the `sh`

**Comment by mxcl** [comment]
> it's entirely correct since some later pip install commands fail.

We automatically add pip when using magic, but you aren't using magic, you are being explicit, so you need to explicitly add pip:

```
sh <(curl https://tea.xyz) +python.org +pip.pypa.io sh
```

**Comment by trentlarson** [comment]
OK! Good to know, thank you.

**Comment by trentlarson** [comment]
I don't understand magic, obviously... but some of the docs make more sense now. Some of my confusion comes from the simple setup instructions (eg. [here](https://docs.tea.xyz/getting-started/install-tea)) and then the instructions for the pantry (eg. [nodejs.org](https://tea.xyz/+nodejs.org/)) with no "sh" on the end: `sh <(curl https://tea.xyz) +nodejs.org`

Below is my own perspective of usage. I see that this page is blank: https://docs.tea.xyz/getting-started/using-tea ... so give me a :+1: if you like the following, and if so then I'll submit a PR.



# Sandbox Usage

Without any other setup, play with the tools you want temporarily:

`sh <(curl https://tea.xyz) +python.org +pip.pypa.io sh`


# ... or With tea Installed

Same as above, but with 'tea' instead of the "sh <(...)", thus:

`tea +python.org +pip.pypa.io sh`


# ... or With a [Developer Environment](https://docs.tea.xyz/features/developer-environments):

Add those tool dependencies to your dev files and enter a shell with it all available:

`tea -E sh`



# ... and With a [chdir Hook -- need to find the real reference](https://github.com/teaxyz/cli/issues/281)

`cd my-sandboxed-project`

... and everything is just _there_.

**Comment by mxcl** [comment]
Feel free! I've been meaning to fill out that page, and your suggestion is a great start.

Also: oh lord, our instructions at tea.xyz/+nodejs.org are wrong, they are missing the `sh`. Thanks! Will fix 🤦🏻‍♂️

**Comment by trentlarson** [comment]
Any idea where I can find instructions for the `cd` hook? I've got this: `add-zsh-hook -Uz chpwd(){ source <(tea -Eds) }`

... in my .zprofile but I can't find where I got it, and I'd like to put a reference into those "using tea" instructions.

**Comment by mxcl** [comment]
> Any idea where I can find instructions for the cd hook? I've got this: add-zsh-hook -Uz chpwd(){ source <(tea -Eds) }
>
> ... in my .zprofile but I can't find where I got it, and I'd like to put a reference into those "using tea" instructions.

This was added by the installer. But it's the old line we now add `source <(tea --magic=SHELL)` so you should update.

We do document that the installer adds a one liner to your shell rc in several places.
