### ISSUE TITLE
panic:Broken pipe (os error 32)

### ISSUE THREAD

**Issue by dev-jwel** [teaxyz/cli#450]
# tea does not run after installation

## Description

I tried to use tea on MacOS.
I got an error by removing `--silent` flag on tea.

## Environment

MacOS 13.2.1
tea 0.25.1

## Reproduction

`sh <(curl https://tea.xyz) && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash)`

## Result

```
$ sh <(curl https://tea.xyz) && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13557  100 13557    0     0   138k      0 --:--:-- --:--:-- --:--:--  142k

  hi 👋 let’s set up tea

  • we’ll put it here:  /Users/jwel/.tea
  • everything tea installs goes there
  • (we won’t touch anything else)

  │ docs https://github.com/teaxyz/cli#getting-started

grep: /Users/jwel/.bashrc: No such file or directory

  may we interest you in some magic?

  tea’s shell magic is optional but it’s the way it’s meant to be used.

  │ docs https://github.com/teaxyz/cli#magic

  Added:

   test -d "$HOME/.tea" && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash --silent)


  you’re all set!

  try it out:

   exec bash -i   # or open a new tab
   wget -qO- tea.xyz/white-paper | glow -

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3ABroken+pipe+(os+error+32)

----------------------------------------------------->> attachment begin
BrokenPipe: Broken pipe (os error 32)
    at async file:///private/var/folders/8b/n_gmhmk57ks85swq3mrdbrwc0000gp/T/7a834af1/src/app.ts:111:13
<<----------------------------------------------------- attachment end
```

**Comment by mxcl** [comment]
I believe this is the correct error message since literally running:

```
source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=bash --silent)
```

will fail

```
source <("$HOME/.tea/tea.xyz/v\*/bin/tea" --magic=bash --silent)
```

Should succeed.

What are you trying to achieve? Running that command manually is unusual.

**Comment by mxcl** [comment]
k so this syntax doesn’t work with bash…? How’d our tests not pick this up.

**Comment by mxcl** [comment]
K the syntax is ok, it's just that the magic has a syntax error and our magic tests didn't pick it up

**Comment by mxcl** [comment]
@ABevier can you figure out how this is passing and fix it? Same goes for the fish test that also was until recently passing even though it was broken. THanks

**Comment by ABevier** [comment]
It appears that this installation was using bash 3.2 (the default version installed on osx) but tea requires bash 4.0 or higher to run.

In addition to the `command_not_found_handler` not being added until bash 4.0, bash 3.2 also has a bug that prevents sourcing from a process substitution:   https://lists.gnu.org/archive/html/bug-bash/2006-01/msg00018.html

**Comment by mxcl** [comment]
users cannot upgrade bash on macOS due to System Integrity Protection.

I'm not convinced we require bash 4. Ubuntu has had a command not found handler for more 10 years and uses bash as the default.

macOS has defaulted to zsh for shell for years now and tea requires macOS >=11, so I think we can fix the immediate bug (source failed) and ignore the command not found handler not working until we get a concrete report from another user.

Or @dev-jwel can add more context.

**Comment by jhheider** [comment]
Bash 4 is from 2009. But there might be bash 3 hacks. I remember people being super psyched when bash 4 came out, and I feel like that's when I started seeing command not found logic, but the history of package on Ubuntu shouldn't be hard to find.

**Comment by dev-jwel** [comment]
@mxcl I'll add more context for future troubleshooting.
I changed default shell to bash before I trying this.
Its version was 3.2.57.
I tried tea again for both bash 5.2.15, zsh 5.8.1 and It works well.
Thanks for everyone!

**Comment by jhheider** [comment]
Yes, it's very odd that Apple ships a version from 2014 of a major version that was superseded in early 2009. I've never understood that choice.

Source: https://ftp.gnu.org/gnu/bash/
