### ISSUE TITLE
The one-liner doesn't work in fish

### ISSUE THREAD

**Issue by andreiborisov** [teaxyz/cli#453]
I think it makes sense to use something portable across all shells for the one-liner.

Currently I'm getting this in fish:

```console
fish: Invalid redirection target:
sh <(curl https://tea.xyz)
   ^~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by jhheider** [comment]
Fish is the odd man out here, iirc. Its variant is `sh <(curl https://tea.xyz | psub)`.

**Comment by mxcl** [comment]
There isn’t an elegant portable one liner. Hopefully fish will adopt `<()` since it's pretty standard.

The only portable one I've found is:

```
curl tea.xyz | sh -s ARGS
```

Since a bunch of our suggested usage includes ARGS
