### ISSUE TITLE
Document WSL pre-reqs

### ISSUE THREAD

**Issue by nadilas** [teaxyz/cli#470]
Hey guys,

just trying out tea. First test on WSL2 results in:
```
user@machine:/mnt/c/Users/user/project$ node --version
unicode.org=71.1.0 cache: hit

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3ACannot+convert+object+to+primitive+value

----------------------------------------------------->> attachment begin
TypeError: Cannot convert object to primitive value
    at install (file:///tmp/bb7336a2/src/prefab/install.ts:91:55)
    at async install (file:///tmp/bb7336a2/src/hooks/useExec.ts:117:25)
    at async default (file:///tmp/bb7336a2/src/hooks/useExec.ts:79:38)
    at async file:///tmp/bb7336a2/src/app.ts:35:63
<<----------------------------------------------------- attachment end
```

**Comment by ABevier** [comment]
@mxcl - It looks like we could do something with WSLv1, but WSLv2 seems like it requires a self hosted runner currently.  See: https://github.com/Vampire/setup-wsl

**Comment by nadilas** [comment]
Untar exists with the same error. (shocking 😃)

unicode.org/v71.1.0/lib/libicudata.so.71.1

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

I removed it entirely and let it re-download the archive. Which ended up working almost:
user@machine:/mnt/c/Users/user/project$ node --version
installed: ~/.tea/unicode.org/v71.1.0
installed: ~/.tea/python.org/v3.11.2
installed: ~/.tea/nodejs.org/v19.8.1
installed: ~/.tea/python-poetry.org/v1.4.0
installed: ~/.tea/npmjs.com/v9.6.2
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory


Running `apt install libatomic1` finally got it working. Thanks for the quick help. (Was the download of the unicode archive somehow corrupted?)

**Comment by mxcl** [comment]
> @mxcl - It looks like we could do something with WSLv1, but WSLv2 seems like it requires a self hosted runner currently. See: https://github.com/Vampire/setup-wsl

@ABevier try out WSL1, may as well test for it

 @jhheider thoughts on self hosting WSL2?

**Comment by mxcl** [comment]
> node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

ah this one is known but we don’t document it and should.

You need to run one of the apt commands from in this script: https://github.com/teaxyz/setup/blob/main/install-pre-reqs.sh

**Comment by jhheider** [comment]
> @jhheider thoughts on self hosting WSL2?

```text
WSLv2 is not explicitly supported, because as of this writing neither the Windows version running on GitHub hosted runners supports WSLv2, nor is Hyper-V enabled which is also necessary to enable WSLv2. If you use a self-hosted runner on a Windows OS that is new enough with enabled Hyper-V and default WSL version set to 2, this action will probably run just fine, but this setup is untested and not explicitly supported. If you want to provide a self-hosted runner with a sufficient setup for this action to use or need changes for supporting WSLv2 I will happily accept this. With a proper test environment (self-hosted runner) that will stay available, I would also add proper official support where you can select the WSL version in your workflow files.
```

[ref](https://github.com/marketplace/actions/setup-wsl)

Since it's just ubuntu on wsl2, we could probably set up a VM and add it to the test matrix, or, possibly, run the runner directly in wsl2. It doesn't need to be used for builds, just tests.

**Comment by nadilas** [comment]
> > node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
> 
> ah this one is known but we don’t document it and should.
> 
> You need to run one of the apt commands from in this script: https://github.com/teaxyz/setup/blob/main/install-pre-reqs.sh

Awesome, thanks. I don't remember having other issues, but will check tomorrow to be sure.

**Comment by mxcl** [comment]
FFS 
![image](https://github.com/teaxyz/cli/assets/58962/507aee87-3d95-4ee7-95c1-516215e60736)
