### ISSUE TITLE
`pnpm` cannot find global bin directory

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#471]
This is my first time installing a global package with `pnpm` but Vercel has it recommended on their [docs](https://vercel.com/docs/cli).

```sh
$ pnpm i -g vercel
installed: ~/.tea/pnpm.io/v7.30.1
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

However running the setup command copies the binary to a new location...

```sh
$ pnpm setup
Copying pnpm CLI from /Users/mfts/.tea/pnpm.io/v7.30.1/bin/pnpm to /Users/mfts/Library/pnpm/pnpm
Appended new lines to /Users/mfts/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/mfts/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/mfts/.zshrc
```

...thereby breaking the versioning and isolation that comes with `tea` 

```sh
$ which pnpm
/Users/mfts/Library/pnpm/pnpm
```

Perhaps there's a way to setup the `global-dir` for `pnpm` similar to how we've done it for Ruby: https://pnpm.io/npmrc#global-dir

**Comment by mfts** [comment]
Great, I will check how you did it with Ruby.

**Comment by jhheider** [comment]
Quick reading of their docs didn't get me all the way there, but the answer might be something like this:
```yaml
env:
  runtime:
    PNPM_HOME: ${{prefix}}/../node_modules
    PATH: "{{prefix}}/../node_modules/.bin:$PATH"
```

**Comment by mxcl** [comment]
Fixed by https://github.com/teaxyz/pantry/pull/1301
