### ISSUE TITLE
(bug): cannot run tea with tea

### ISSUE THREAD

**Issue by vegerot** [teaxyz/cli#473]
steps to reproduce:
1. install tea
2. check tea version (`tea 0.25.3`) on my machine
3. run `tea "tea^0.21" --version`

Expected: outputs "0.21.?"

Actual: 

```sh
❯ tea "tea^0.21" --version
tea 0.25.3
```

the same problem happens with shells

```sh
❯ tea +"tea.xyz^0.21.2"
PATH=/Users/m0c0j7y/.tea/tea.xyz/v0.25.3/bin:...:
LDFLAGS=-Wl,-rpath,/Users/m0c0j7y/.tea
TEA_PREFIX=/Users/m0c0j7y/.tea
```

It works with other packages

```sh
❯ tea +"nodejs.org^18" node --version
v18.15.0
```

**Comment by mxcl** [comment]
hah fun. I wonder what is wrong. I'll take a look.

**Comment by vegerot** [comment]
thank you!

**Comment by vegerot** [comment]
My guess is that this has to do with tea's update system.  For most packages, `tea x` will not update the package but there might be a special case when x = `tea` in order to facilitate updates

**Comment by vegerot** [comment]
@mxcl same problem with deno 

```sh
❯ tea "deno^1.30" --version
deno 1.32.3 (release, x86_64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3

❯ tea +"deno.land^1.20"
DENO_NO_UPDATE_CHECK=true
PATH=/Users/m0c0j7y/.tea/deno.land/v1.32.3/bin:/Users/m0c0j7y/Library/pnpm:/Users/m0c0j7y/.bun/bin:/Users/m0c0j7y/.cargo/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/m0c0j7y/.cabal/bin:/Users/m0c0j7y/.ghcup/bin:/usr/local/lib:/Users/m0c0j7y/go/bin:/opt/cisco/anyconnect/bin:/Users/m0c0j7y/dotfiles/bin:/Users/m0c0j7y/.mint/bin/:/Users/m0c0j7y/.sledge/bin:.
LDFLAGS=-Wl,-rpath,/Users/m0c0j7y/.tea
TEA_PREFIX=/Users/m0c0j7y/.tea

❯ tea +"deno.land^1.20" sh
this is a temporary shell containing the following packages:
deno.land=1.32.3
when done type: `exit'
tea ~/gecgithub01.walmart.com/ce-orchestration/ce-smartlists deno --version
deno 1.32.3 (release, x86_64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
tea ~/gecgithub01.walmart.com/ce-orchestration/ce-smartlists
```

It's weird this works with Node but not Deno or tea

**Comment by jhheider** [comment]
`^1.30` == `>=1.30.0<2`. Try:
```sh
tea +deno.land~1.27 deno --version
installed: ~/.tea/deno.land/v1.27.1
deno 1.27.1 (release, aarch64-apple-darwin)
v8 10.8.168.4
typescript 4.8.3
```

**Comment by jhheider** [comment]
Works with `tea` as well:
```sh
tea +tea.xyz~0.22 tea --version
installed: ~/.tea/tea.xyz/v0.22.3
tea 0.22.3
```

**Comment by mxcl** [comment]
k right, so this is semver being confusing. `^` usually means up to next major.

However actually for zero ranges it is meant to be one level more restrictive lol. Check the spec.

So strictly a bug, but generally this is actually behaving correctly. We should probs have some docs that reiterate semver somewhere.

Leaving open:

1. fix ^0 ranges per spec even though it's inconsistent and a little gross
2. docs

**Comment by jhheider** [comment]
> 1. fix ^0 ranges per spec even though it's inconsistent and a little gross

I deem the spec wrong about this, even though it's efficient.

**Comment by jhheider** [comment]
Is there a spec for ranges? `semver.org` doesn't seem to discuss them. Is [this](https://github.com/npm/node-semver#caret-ranges-123-025-004), then, considered canonical?

**Comment by mxcl** [comment]
I believe we have settled on https://devhints.io/semver

**Comment by jhheider** [comment]
Got it. And it seems to reference the node semver package. 👍

**Comment by vegerot** [comment]
> 

@jhheider that makes so much sense!!!  Thank you ❤️

**Comment by vegerot** [comment]
actually @jhheider I still have a question.  https://dist.tea.xyz/deno.land/darwin/x86-64/versions.txt shows (among others)

```
...
1.31.3
1.32.0
1.32.1
1.32.2
1.32.3
```

however, running

```sh
tea deno~1.32.2 repl
```

runs deno 1.32.3.  Looking at https://devhints.io/semver it makes sense why, but then I'm confused as to how to specify a correct version!  Obviously

```sh
tea deno1.32.2 repl
```
makes no sense 😁

**Comment by jhheider** [comment]
```sh
jacob@illithid pantry % tea deno~1.32.2 --version
deno 1.32.3 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
jacob@illithid pantry % tea deno=1.32.2 --version
deno 1.32.2 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by vegerot** [comment]
> 2. docs
> 
> > Notably we support `@` syntax which with our learnings here probably is what people want most of the time. We've carefully configured it to behave well. Here it would do what you expected both times.

@mxcl  We currently do not support `@` syntax.  https://github.com/teaxyz/cli/blob/main/src/utils/semver.ts#L136-L155

**Comment by vegerot** [comment]
anyways, the answer to my question is to use `=` in the semver like `tea tea=0.26.2`.  Thanks!! ❤️

**Comment by mxcl** [comment]
> @mxcl We currently do not support @ syntax. https://github.com/teaxyz/cli/blob/main/src/utils/semver.ts#L136-L155

we do. it's handled at a higher level.

**Comment by mxcl** [comment]
k, this broke. wtf
