### ISSUE TITLE
tea magic doesn't play well with pipes (fish)

### ISSUE THREAD

**Issue by davdroman** [teaxyz/cli#474]
In light of recent news about GitHub's key leak/rotation, I ran the suggested commands in their post: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

```sh
$ ssh-keygen -R github.com
$ curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
installed: ~/.tea/github.com/kkos/oniguruma/v6.9.8
installed: ~/.tea/stedolan.github.io/jq/v1.6.0
```

It was great to see tea magic spring into action to install the missing `jq`, however after that it didn't do anything. It just got stuck there. I tried running it again:

```sh
$ curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
```

But same thing, no output, just stuck.

I then ran it with explicit `tea`:

```sh
$ curl -L https://api.github.com/meta | tea jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
```

And it worked as expected.

It was pretty close to a magical experience, but there seems to be something blocking tea from fully doing its magic. I wonder if it's shell related (I'm using fish) or something in tea's magic implementation that doesn't play well with pipes.

**Comment by mxcl** [comment]
Yes this is a bug in fish. We have a ticket about it here: https://github.com/teaxyz/pantry/issues/861

I'd love to get this fixed sooner rather than later, I don't suppose you have the time?

**Comment by davdroman** [comment]
@mxcl I'm afraid not, at the moment. I have work and open source commitments of my own 😅

**Comment by mxcl** [comment]
heh, nps… had to try! hopefully @jhheider is inspired since he uses fish

**Comment by jhheider** [comment]
Fish's interactive friendliness leads to a lot of weird corners when scripting. Might need to do something with a `psub` to make handle pipes correctly. We'll see.

**Comment by mxcl** [comment]
Closing as v1 has removed magic of this form.
