### ISSUE TITLE
`tea -S semverator` should update `semverator`

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#484]

**Comment by jhheider** [comment]
A nice-to-have, but potentially complicated variant of this would be if this worked:
```sh
$ cd pantry
$ pkg --version
brewkit 0.11.8
$ tea -S tea.xyz/brewkit
installed: ~/.tea/tea.xyz/brewkit/v0.12.2
$ pkg --version
brewkit 0.12.2
```
though this requires evaluating the dev-env for reconstruction after (potentially) every invocation.

**Comment by mxcl** [comment]
yeah I consider it a separate bug that the dev-env isn't updated after `tea -S`.

**Comment by mxcl** [comment]
This works, I just tested it.
