### ISSUE TITLE
WSL1

### ISSUE THREAD

**Issue by vladdeSV** [teaxyz/cli#493]
Re-installed my computer and was put back to WSL1. This caused some problems (#490, #491) which were solved by upgrading to WSL2. I believe WSL1 is the [default version](https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-5---set-wsl-2-as-your-default-version).

It seems tea does not play nice with WSL1.

**Comment by vladdeSV** [comment]
Some points that speak for supporting WSL1:
- WSL1 is the default
- WSL2 does not support IPv6, at work I had to use WSL1
    - https://github.com/microsoft/WSL/issues/4518
- WSL2 does [not handle symlinks](https://superuser.com/questions/1695779/symlinks-made-in-the-linux-side-of-wsl2-do-not-appear-in-the-windows-side-under) when browsing files with Explorer.exe
- WSL2 does play nice with hot reload ([one of many issues on SO](https://stackoverflow.com/questions/69276057/wsl-2-react-not-reloading-with-file-changes))

**Comment by mxcl** [comment]
> WSL1 is the default

This is a pretty good reason lol. K we gotta support WSL. Sounds like WSL2 is not mature or recommended yet.

**Comment by jhheider** [comment]
I don't think this is still true:

https://learn.microsoft.com/en-us/windows/wsl/install

```
New Linux installations, installed using the wsl --install command, will be set to WSL 2 by default.

The wsl --set-version command can be used to downgrade from WSL 2 to WSL 1 or to update previously installed Linux distributions from WSL 1 to WSL 2.

To see whether your Linux distribution is set to WSL 1 or WSL 2, use the command: wsl -l -v.

To change versions, use the command: wsl --set-version <distro name> 2 replacing <distro name> with the name of the Linux distribution that you want to update. For example, wsl --set-version Ubuntu-20.04 2 will set your Ubuntu 20.04 distribution to use WSL 2.
```

That said, it's easy to have a WSL 1 install, either on an older Windows, predating the new default, or by "downgrading".

Notably: https://learn.microsoft.com/en-us/windows/wsl/compare-versions#comparing-features

It looks like WSL1 neither has a full Linux kernel, nor the full syscall availability. That _might_ mean it needs to be built as its own binary variant. It [looks like even `rust` has issues with WSL1](https://github.com/rust-lang/rust/issues/88753), which likely means both `deno` and `tea` will as well.

**Comment by mxcl** [comment]
k well if WSL2 is the current default then that needs supporting firstly. Do we work with WSL2? I have a windows machine so I should check this out myself.

**Comment by vladdeSV** [comment]
I've had no problems with tea and WSL2 so far, been using for a month or so.

**Comment by jhheider** [comment]
Yes, we've have no noteworthy bug reports for WSL2, given its reasonable similarity to a dockerized environment.
