### ISSUE TITLE
Magic not working when changing directories

### ISSUE THREAD

**Issue by nickali** [teaxyz/cli#498]
This is almost certainly a user error, but I'm not quite sure what is going on.

I have two directories:
- ~/WIP/tea-test
- ~/WIP/tea-test2

tea-test has a requirements.txt which includes 'urllib3==1.26.15'

tea-test2 has a requirements.txt which includes 'urllib3==1.26.14'

Right after installing tea, I do the following:

```sh

❯ cd ~/WIP/tea-test

~/WIP/tea-test
 ❯ ls
requirements.txt

~/WIP/tea-test
 ❯ pip list
. . .
installed: ~/.tea/python.org/v3.11.2
installed: ~/.tea/pip.pypa.io/v23.0.1
Package    Version

pip        23.0.1
setuptools 65.5.0

~/WIP/tea-test 17s
 ❯ pip install -r requirements.txt
. . .
Collecting urllib3==1.26.15
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2022.12.7 charset-normalizer-3.1.0 idna-3.4 requests-2.28.2 urllib3-1.26.15

~/WIP/tea-test
 ❯ pip list
Package            Version
------------------ ---------
. . .
urllib3            1.26.15

~/WIP/tea-test
 ❯

```

Great, I have urllib3 1.26.15 installed when in the tea-test directory. Then I switch over to tea-test2 and do the same:

```sh
~/WIP/tea-test
 ❯ cd ../tea-test2

~/WIP/tea-test2
 ❯ pip install -r requirements.txt
. . .
Collecting urllib3==1.26.14
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.15
    Uninstalling urllib3-1.26.15:
      Successfully uninstalled urllib3-1.26.15
Successfully installed urllib3-1.26.14

~/WIP/tea-test2
 ❯ pip list
Package            Version
------------------ ---------
. . .
urllib3            1.26.14
```

As expected, urllib3 1.26.14 is in tea-test2.

But when cd back to tea-test, I see this:

```sh
~/WIP/tea-test2
 ❯ cd ../tea-test

~/WIP/tea-test
 ❯ pip list
Package            Version
------------------ ---------
. . .
urllib3            1.26.14
```

Why didn't urllib3 switch to 1.26.15 as defined in requirements.txt?

When I run 'env' in tea-test, I see:

```sh
SRCROOT=/Users/nali/WIP/tea-test
TEA_FILES=/Users/nali/WIP/tea-test/requirements.txt
```

which looks right to me. If I run 'tea -SE && cd .' and then run 'pip list' url3lib3 is still 1.26.14. 

I had assumed when I switched directories, the libraries listed by pip would also change.

What am I doing wrong here?

**Comment by nickali** [comment]
@mxcl Sorry for replying so late, but what do you mean does it work without tea? Like testing it out with venv?

**Comment by mxcl** [comment]
uninstall tea, does it work?

because I'm saying tea has no direct influence over what pip decides to do, but if it works without tea installed then i'm wrong.

**Comment by nickali** [comment]
@mxcl it doesn't work without tea, but it's not supposed to. Pip uses the last version of the library installed without tea, right? If we do a ```pip install -r requirements.txt``` which contains urllib3==1.26.14 and then do a ```pip install -r requirements.txt``` which contains urllib3==1.26.15, pip uses 1.26.15 for the whole user account.

**Comment by mxcl** [comment]
I believe this is not a tea bug since `pip list` is doing its own thing.

We may expand tea’s dev-envs to automatically make python virtual environments too, but at this point we do not.
