### ISSUE TITLE
Disable "resolving package graph" prompt

### ISSUE THREAD

**Issue by jylin** [teaxyz/cli#517]
Is there a way to disable some of these loading messages? The VSCode Data Explorer extension runs the following to detect the pandas version, but it fails because of the loading message.

```info 14:43:01.561: Process Execution: > ~/.local/bin/python -c "import pandas;print(pandas.__version__)"
> ~/.local/bin/python -c "import pandas;print(pandas.__version__)"
info 14:43:01.705: Web view react rendered
warn 14:43:02.120: Failed to get version of Pandas to use the Data Viewer. tea: resolving package graph
[G[1A[0J```

**Comment by jhheider** [comment]
`VERBOSE=-1 python~3.7 -c "import pandas;print(pandas.__version__)"`?

**Comment by jylin** [comment]
Thanks, but the problem is I can't easily control the env or command for these plugins. Was hoping for some kind of global configuration file or something like that to toggle these.

**Comment by mxcl** [comment]
We output this message to stderr. The extension is behaving super strangely if it pulls in the data from both stdout **AND** stderr to get this information.

We certainly could and should add a global configuration system.

However I wouldn’t recommend setting `tea` to be silent globally just to work around one extension.

Personally I’d suggest making `~/.local/bin/python` a shim shell script:

```
#!/bin/sh

tea --silent python "$@"
```

**Comment by mxcl** [comment]
@ABevier can we add a test to verify that these messages go to stderr and not stdout so we ensure this never regresses, since if it did it would break a lot of tools in the manner of above.

I just verified locally that this is still true for my own peace of mind

**Comment by mxcl** [comment]
Perhaps we should disable these messages when we're fd2 is not stdout?

What do other tools do here?

**Comment by jhheider** [comment]
```sh
curl tea.xyz >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13759  100 13759    0     0  71354      0 --:--:-- --:--:-- --:--:-- 73577
curl tea.xyz >/dev/null 2>&1
```

**Comment by jhheider** [comment]
redirecting just stderr is hard; but this lets you play with it in zsh:
```sh
curl tea.xyz >/dev/null 2> >(wc)
       3      54     396
```

**Comment by mxcl** [comment]
so indeed, `curl` outputs to stderr even when piped. That’s a pretty major one.

We are a different kind of tool. I guess an equivalent might be something like `npx`.

**Comment by mxcl** [comment]
Another example of this being problematic here: https://github.com/jesseduffield/lazygit/issues/2716
