### ISSUE TITLE
time `cmd`

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#526]
I just thought of a case where the magic gets messed up, and that's when prepending a command with `time`. Example: `git ...`, tea knows to do +git-scm.org. But if you do `time git ...` then tea looks for the `time` command.

**Comment by jhheider** [comment]
`watch` and `sudo` have the same issue, in that since they're not shell interpreters themselves, they don't call the command not found handler. My _guess_ is that the only way to fix that would be to make them specialized shims, but you'd still have to ignore those already on the system.

**Comment by mxcl** [comment]
Closing in favor of #348 

There are a few ways we could fix this:

* identify common commands we should shim shim them
* be a proxy shell `tsh` and be the user’s shell
* hands up and just educate the user that in some cases they need to prepend tea
