### ISSUE TITLE
Not able to commit using Node developer environment and GitHub Desktop

### ISSUE THREAD

**Issue by ubmit** [teaxyz/cli#531]
First of all, I feel like I'm missing something here. Tried to go through the docs, but wasn't able to find a fix myself. Sorry if this isn't actually an issue.

I tried to commit using a Node developer environment and GitHub Desktop, but I faced this error on GitHub Desktop:

```
env: node: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

![image](https://user-images.githubusercontent.com/8797405/232044495-fd1bbcd6-0721-4d67-9e95-96b9bfda9aee.png)

However, running `git` from the CLI worked just fine. The `husky` pre-commit hook ran and I was able to commit successfully.

I have my Node version set for this project using `.node-version` file:

```sh
cat .node-version
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .node-version
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 16.20.0
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

And running `node -v` returns the correct Node version: 
```sh
node -v
v16.20.0
```

**Comment by mxcl** [comment]
Yeah sorry, I only just added docs for this—this morning!

https://docs.tea.xyz/getting-started/using-tea#other-editors

If you make a symlink for `node` to `tea` in your `PATH` then GitHub Desktop etc. *should* use the dev-env specified `git` because the CWD will be set correctly.

Otherwise `tea` will use the latest `node` installed.

This is an area we are trying to improve until everything just works. I have more ideas up my sleeves.

**Comment by ubmit** [comment]
> Yeah sorry, I only just added docs for this—this morning!
> 
> [docs.tea.xyz/getting-started/using-tea#other-editors](https://docs.tea.xyz/getting-started/using-tea#other-editors)
> 
> If you make a symlink for `node` to `tea` in your `PATH` then GitHub Desktop etc. _should_ use the dev-env specified `git` because the CWD will be set correctly.
> 
> Otherwise `tea` will use the latest `node` installed.
> 
> This is an area we are trying to improve until everything just works. I have more ideas up my sleeves.

Thanks! I'll try it later 🙌
