### ISSUE TITLE
npx complaining about a missing folder in `~/.local`

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#532]
tea v0.27.0

`npx` is complaining about a missing `~/.local/lib` folder . 

```sh
$ npx create-next-app example-app                                   
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /Users/mfts/.local/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/mfts/.local/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /Users/mfts/.npm/_logs/2023-04-14T16_30_11_142Z-debug-0.log
```

resolved with `mkdir ~/.local/lib`, it doesn't actually install anything there tho...

**Comment by mxcl** [comment]
imagine making a tool with millions of users and not doing a mkdir before trying to copy files lol

**Comment by jhheider** [comment]
I wonder how much would break if you modded the kernel to make directories only exist if they have contents, as AWS S3 does. `mkdir` would be fully unneeded. Probably there's a perms issue you'd have to solve.
