### ISSUE TITLE
`tea +cmake.org npm install ...` cannot find npm

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#533]
Something that used to work iirc, breaks for me. 

I tried 

```sh
$ npm install --save-dev opencv-build
# throws error that it needs cmake: command not found

$ tea +cmake.org npm install --save-dev opencv-build
installed: ~/.tea/cmake.org/v3.26.3
tea: command not found: npm
```

Resolved by adding npm explicitly
```sh
$ tea +cmake.org +npmjs.com npm install --save-dev opencv-build
# ^^ this works
```

I expected that tea understand from the command `npm install` that npm is a dependency and adds it magically

---
tea v0.27.0
vscode terminal

**Comment by mxcl** [comment]
This is defined behavior. Magic stops working once you start specifying a pkg env with `+pkg` syntax.

If this used to work then I’d guess you had an `npm` in the `PATH`.

Whether or not this makes sense is up for discussion.
