### ISSUE TITLE
VSCode throws a pantry not-found error with a `tea.yaml` file in the root 

### ISSUE THREAD

**Issue by mfts** [teaxyz/cli#534]
So, I added a tea.yaml with the following contents to the root of a javascript project because a npm package `canvas` requires these packages.

```yaml
dependencies:
  freedesktop.org/pkg-config: 0.29.2
  cairographics.org: 1.16.0
  gnome.org/pango: ^1
  libpng.org: ^1
  libjpeg-turbo.org: ^2
  giflib.sourceforge.io: ^5
  gnome.org/librsvg: ^2
```

However, the vscode terminal throws an error when I try to install the package

```sh
$ npm install canvas
error: not-found: pantry (spilt-tea-009)
pantry entry invalid. please report this bug!

    https://github.com/teaxyz/pantry/issues/new

----------------------------------------------------->> attachment begin
undefined: unknown cause
<<------------------------------------------------------- attachment end
```

I tried to `tea --sync --env ` and `cd .` 

I ended up using the mac Terminal to install canvas. That worked perfectly.

---
tea v0.27.0
vscode 👇
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by mxcl** [comment]
gimme `env`

**Comment by mfts** [comment]
Will try to recreate this

**Comment by mxcl** [comment]
Closing since probs too old to debug now or likely fixed
