### ISSUE TITLE
Flag to prompt to install

### ISSUE THREAD

**Issue by magnusviri** [teaxyz/cli#552]
Can you add a flag that causes tea cli to prompt before installing stuff? I think I might like that behavior more. But even if I decide I want the default behavior, I am sure having the flag will reassure a lot of people who want extra security. Basically, I'd write a second command_not_found_handler after the tea magic and the new handler would specify the flag. Or maybe even if the  --magic flag and the prompt to install flag are specified, the command not found handler would automatically add the prompt to install flag.

**Comment by mxcl** [comment]
yes we should add this for sure. we'll probs start with `TEA_MAGIC=prompt` before moving to some configuration

**Comment by magnusviri** [comment]
An env variable would be perfect!
