### ISSUE TITLE
`--sync` outside a dev-env should update all

### ISSUE THREAD

**Issue by mxcl** [teaxyz/cli#568]
### Discussed in https://github.com/orgs/teaxyz/discussions/567

<div type='discussions-op-text'>

<sup>Originally posted by **nova77** May  3, 2023</sup>
According to the docs it's possible to update specific packages with the `--sync` command, eg. `tea --sync +deno.land`.
However, I could not find any place (besides tea/gui) where I can find a list of packages that can be updated.

In addition to this, is there a way to update all packages at once? Something like `tea --sync all`.</div>

**Comment by mxcl** [comment]
However I think this case should require a prompt or `--yes`. This is fairly typical of other such tools since you don’t know in advance what you are updating.

**Comment by mxcl** [comment]
and `--sync --dryrun` would be like an `outdated` command.

**Comment by mxcl** [comment]
yeah well, with `brew` I was being a bit too yolo with hindsight 🤣

**Comment by jhheider** [comment]
_maybe_. I think running `brew upgrade` usually conforms to my expectation, but it doesn't _bother me_ when `apt` asks me to confirm (especially since I can always `-y` if I remember beforehand).

**Comment by mxcl** [comment]
I changed my mind for now.

the gui is the correct place for this. tea is a highly scoped tool.

The correct way to do this would be, honestly, another tool built on libtea. Perhaps we could call it `teapot`.

**Comment by jhheider** [comment]
> The correct way to do this would be, honestly, another tool built on libtea. Perhaps we could call it `teapot`.

`teaxyz/tui`
