### ISSUE TITLE
`semver.ts` needs tweaks for "short" versions

### ISSUE THREAD

**Issue by jhheider** [teaxyz/cli#574]
https://github.com/teaxyz/pantry/pull/1863

> looks like https://github.com/teaxyz/brewkit/pull/106 needs support in
> `teaxyz/cli:semver.ts`. specifically, around
> https://github.com/teaxyz/cli/blob/31c2fc0bbddc41cbd63d9ee14593efe3f9b09301/src/utils/semver.ts#L29

**Comment by mxcl** [comment]
What is the problem exactly? I went to the pantry ticket and couldn't figure out what is wrong or what you are asking for

**Comment by jhheider** [comment]
```sh
% tea +github.com/tmux/tmux=3.3a tmux
resolving package graph
error: http (spilt-tea-500)
too short to parse without a `v` prefix: 3.3a
```

Interestingly, `ijg.org` works fine:

```sh
% tea +ijg.org=9e sh
this is a temporary shell containing the following packages:
deno.land=1.33.2, gnu.org/bash=5.2.15, tea.xyz=0.31.2, ijg.org=9e, tea.xyz/brewkit=0.27.2
when done type: `exit'
tea ~/tea/pantry 
```

**Comment by jhheider** [comment]
ah, nope:
```sh
% rm -rf ~/.tea/ijg.org ~/.tea/tea.xyz/var/www/ijg.org-9*
% tea +ijg.org sh
resolving package graph
error: http (spilt-tea-500)
too short to parse without a `v` prefix: 9e

**Comment by uesyn** [comment]
When the package was built in local, it looks like that this problem doesn't occur.

**Comment by mxcl** [comment]
aah ok
