### ISSUE TITLE
panic:FORK BOMB KILL SWITCH ACTIVATED

### ISSUE THREAD

**Issue by tekhnus** [teaxyz/cli#610]
Hello:)

I'm having an issue with `tea ld`. Other packages (vim, emacs, python, cmake) work fine.

```
$ tea ld

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3AFORK+BOMB+KILL+SWITCH+ACTIVATED

----------------------------------------------------->> attachment begin
Error: FORK BOMB KILL SWITCH ACTIVATED
    at default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.exec.ts:11:28)
    at run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.main.ts:59:31)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/f0a0633b/src/app.ts:12:5
<<----------------------------------------------------- attachment end
```

**Comment by mxcl** [comment]
can you provide

* `ls -la $(which ld)`
* `realpath $(which tea)`
* `tea -vvvn ld`

**Comment by tekhnus** [comment]
Here you go:
```
% ls -la $(which ld)
lrwxr-xr-x  1 zahaaar  staff  29 Jun  9 15:53 /Users/zahaaar/.local/bin/ld -> /Users/zahaaar/.local/bin/tea
% ls -la $(which tea)  
lrwxr-xr-x  1 zahaaar  staff  43 Jun  9 11:31 /Users/zahaaar/.local/bin/tea -> /Users/zahaaar/.tea/tea.xyz/v0.35.4/bin/tea
% realpath $(which tea)
/Users/zahaaar/.tea/tea.xyz/v0.35.4/bin/tea
% tea -vvvn ld
resolving package graph
{
  hydrating: [
    {
      project: "tea.xyz/gx/cc",
      path: ~/.tea/tea.xyz/var/pantry/projects/tea.xyz/gx/cc/package.yml,
      constraint: *,
      shebang: [ "ld" ]
    }
  ]
/Users/zahaaar/.tea/tea.xyz/gx/cc/v0.1.4/bin/ld
```

**Comment by mxcl** [comment]
k thanks

I cannot reproduce but certainly can see why it happens. Our gx/cc ld tries to avoid this kind of scenario but now we add symlinks to `~/.tea/.local/bin` it is confused.

**Comment by mxcl** [comment]
Rennovating is a more involved task, so I applied a more immediate fix.

`tea -S +tea.xyz/gx/cc` should update the `ld` shim in 20 mins or so.

**Comment by tekhnus** [comment]
Unfortunately, the problem remains. Same stacktrace and same command outputs except it's now /Users/zahaaar/.tea/tea.xyz/gx/cc/v0.1.5/bin/ld instead of v0.1.4

**Comment by mxcl** [comment]
I can no longer reproduce. `tea ld` does not fork bomb. Is that all you need to do? Can you please provide steps and output again anyway in case there's some subtle difference

**Comment by tekhnus** [comment]
It seems to me like you made a fix for `~/.tea/.local/bin`, but it's actually `~/.local/bin` (a very popular location to store executables).

**Comment by mxcl** [comment]
Oh! Interesting! So you made your own symlink of `ld` to `tea` in `~/.local/bin`?

I imagine that indeed this would not be covered. It's kinda tricky to do right but I have ideas.

Anyway pls confirm you made the symlink otherwise we have bigger problems.

**Comment by tekhnus** [comment]
Yes, I manually created the symlink ~/.local/bin/tea -> ~/.tea/tea.xyz/v0.35.4/bin/tea (so that tea executable would be accessible for me), and for each application X I'm creating a symlink ~/.local/bin/X -> ~/.local/bin/tea. I'm not using magic and such workflow seemed to be very natural to me...
