### ISSUE TITLE
global yarn packages fail to be found

### ISSUE THREAD

**Issue by mirshko** [teaxyz/cli#611]
Following up from #582,

after installing the updates as mentioned, and reinstalling node, reinstalling yarn as well and installing any global package, fe: fkill-cli. when invoking the command with `fkill` the command fails to be found. 

running `yarn global list` shows the installed package so it must have something to do with the path, since the `.local/bin` has global packages from npm shown.

**Comment by mxcl** [comment]
it appears the default for yarn installed global binaries is `~/.yarn/bin`

tea’s current pkging behavior is to change such defaults so
* /usr/local/bin is picked if running as root
* ~/.local/bin is picked if not

I'll update the yarn pkg, but feel free to chime in based on your expectations here.
