### ISSUE TITLE
Still download the installed command?

### ISSUE THREAD

**Issue by ChandlerVer5** [teaxyz/cli#613]
If the command 'exa' has been installed on the system and tea pantry has exa  pkg; Then 'tea exa -v' still go to install 'exa', Is that on purpose?

**Comment by mxcl** [comment]
yes if you ask tea for exa it will use its own exa even if its on the system.

This could be made configurable but it was the default we chose.

I agree that it is confusing in that if tea didn't provide exa it would just pass the whole command through to the system and would like to be more idiomatic if possible there.

**Comment by ChandlerVer5** [comment]
yeah, i just dont want to wait for it to be downloaded；if  I accidentally downloaded  the 'exa', How do I uninstall it?

**Comment by ChandlerVer5** [comment]
I don't know how to uninstall it。
These things should be documented on the documentation site；
Thanks for your response;

**Comment by mxcl** [comment]
just delete `~/.tea/crates.io/exa` and it is uninstalled. I agree our documentation is lacking. We're a new project, I'm sure you are familiar with there being 10 million things to do and sometimes you miss important details.

Thanks for trying tea.

I would still be interested to know what you were trying to do and what you expected? If you already had exa installed why did you want to run tea?

**Comment by ChandlerVer5** [comment]
I just played with tea, to see the differences between tea and tea without magic.
yeah, there are a lot of things bother us everyday.
I'll keep using it, it looks good.Thank you for your excellent work.
