### ISSUE TITLE
tldr: libbz2.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by osalbahr** [teaxyz/cli#626]
```console
[zeus@fedora ~]$ tldr tea
installed: ~/.tea/tldr.sh/v1.6.0
installed: ~/.tea/libzip.org/v1.10.0
installed: ~/.tea/lz4.org/v1.9.4
installed: ~/.tea/facebook.com/zstd/v1.5.5
installed: ~/.tea/tukaani.org/xz/v5.4.3
installed: ~/.tea/curl.se/v8.1.2
tldr: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
[zeus@fedora ~]$ find ~/.tea/libzip.org/v1.10.0 -name '*.so*'
/var/home/zeus/.tea/libzip.org/v1.10.0/lib/libzip.so.5.5
/var/home/zeus/.tea/libzip.org/v1.10.0/lib/libzip.so
/var/home/zeus/.tea/libzip.org/v1.10.0/lib/libzip.so.5
[zeus@fedora ~]$ find ~/.tea -name 'libbz2.so.1.0'
[zeus@fedora ~]$ 
```

It looks like a missing (or mismatched) dependency?

**Comment by jhheider** [comment]
Looks like it needs to depend on `sourceware.org/bzip2: '*'`. I don't see that in the `otool` output under darwin. Looks like it depends on it on linux. I'll update the pantry.

**Comment by osalbahr** [comment]
Thx for the prompt fix!

Is there a reason why `tea` requires both libraries to work on Linux? I looked in https://repology.org/project/tldr-c-client/versions and both the AUR and Homebrew have `libzip` as the only `*zip*` dependency.

**Comment by jhheider** [comment]
My guess is that it builds in bz2 support if the library is present, which it likely is on the build machines.

**Comment by mxcl** [comment]
would be nice if we could run tests on something more minimal…
