### ISSUE TITLE
Tea considers that `pyproject.toml` files are handled by poetry, but it is a PEP standard and can be used by many other project management tools

### ISSUE THREAD

**Issue by vemonet** [teaxyz/cli#627]
## The problem

Hi, I noticed that when I try to use tea for a python project with a `pyproject.toml` file it wrongly thinks I will use `poetry`

It is also documented in the documentation: https://docs.tea.xyz/features/developer-environments

> For example, if we’re talking a python poetry project, then you can specify your python version by adding YAML front matter to its pyproject.toml:

As per PEP 621 (https://peps.python.org/pep-0621/) `pyproject.toml` is now the standard way to define a python project, and it is supported by pretty much all python build tools (pip, hatch...)

Many python developers are not using poetry, especially when building packages. In my case I uses `hatch` which is the official project management tool recommended by the PyPA (and it is really good!), a lot of popular python packages are also using hatch/hatchling as their build system: https://hatch.pypa.io/latest/community/users/

Note that it does not impact my ability to use `hatch`: running `tea hatch run python --version` properly install `hatch`. 

But ideally `tea` should not install `poetry` when I don't need it

## A potential solution

You could check in the `pyproject.toml` if the `build-backend` is `poetry.core.masonry.api` and only download poetry in this case:

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

It could also be extended to automatically download the dependencies for other build-backend

## Additional context

The build-system standard is described here: https://peps.python.org/pep-0518/
There are probably around 10 or less popular build-system at the moment (afaik)

Let me know if you are interested in handling this use-case and would like some help with the implementation!

**Comment by mxcl** [comment]
cool, we can parse the build-system stuff for sure. Thanks for the info! This is how we become the best tool thanks to reports like yours.

**Comment by vemonet** [comment]
Regarding the implementation to figure out which backend is used, this project template might help to quickly understand the difference between build-backends in practice (instead of spending hours gathering informations): https://github.com/scientific-python/cookie

They allow to bootstrap a python package choosing one of the 12 backends available:

```
1 - hatch
2 - flit
3 - pdm
4 - trampolim
5 - whey
6 - poetry
7 - setuptools621
8 - setuptools
9 - pybind11
10 - skbuild
11 - mesonpy
12 - maturin
```

**Comment by mxcl** [comment]
> `mesonpy`

is that mesonbuild.com? we have that. The rest we do not (bar setup tools which just means dep on python)
