### ISSUE TITLE
Issue setting up python.org version dependency from `pyproject.toml` and `README.md`

### ISSUE THREAD

**Issue by vemonet** [teaxyz/cli#628]
Hi, I am trying to use `tea` to work with python 3.7 on a python package: https://github.com/MaastrichtU-IDS/trapi-predict-kit on Fedora 38 installed from the one-liner on the homepage, with magic enabled

I followed the instructions at https://docs.tea.xyz/features/developer-environments 

I added the following at the top of my `pyproject.toml`:

```toml
# ---
# dependencies:
#   python.org: ^3.7.17
# ---
```

But if I run `tea python --version` I get `Python 3.11.4` instead of `3.7`

When I run `tea -SE` I get v3.11.4 in the environment variables: `/.tea/python.org/v3.11.4/`

I also tried setting up the dependencies in the `README.md`:

```markdown
# Dependencies
| Project    | Version |
| ---------- | ------- |
| python.org | ^3.7.17    |
```

But it is still setting up 3.11 in the environment

Also, running the command below return 3.11:

```bash
tea +python.org^3.7.17 python --version
```

And I tried with other versions (3.9, 3.10) and still get 3.11

The only way to get 3.7 in the environment is to run `tea +python.org=3.7.17 python --version`

Setting `=3.7.17` or `3.7.17` in the `pyproject.toml` and readme still gives 3.11 though

Why is tea setting up python 3.11 instead of 3.7 as defined in the `pyproject.toml` front matter or `README.md`? Am I missing something like a global config?

**Comment by jhheider** [comment]
That looks correct: https://devhints.io/semver

I believe you want `~3.7.17`.

**Comment by vemonet** [comment]
Oh yes indeed, I thought `=3.7.17` would be working but it does not seems to be valid semver, thanks!

**Comment by jhheider** [comment]
`=3.7.17` should definitely be working:

```sh
% tea-pkg inv python.org
2.7.18
3.7.16
3.7.17
3.8.16
3.8.17
3.9.16
3.9.17
3.10.7
3.10.8
3.10.10
3.10.11
3.10.12
3.11.0
3.11.1
3.11.2
3.11.3
3.11.4
```

so, there might well still be a bug there.

**Comment by vemonet** [comment]
I don't think, because I tried to use = in the toml frontmatter:

```
# ---
# dependencies:
#   python.org: =3.7.17
# ---
```

If the frontmatter only supports semver style (`~`, `^`, etc), then it is normal that using `=` fails

**Comment by jhheider** [comment]
It should support the same frontmatter values as any of our other methods.

This works with both `=` and `^`:
```python
#!/usr/bin/env tea

# ---
# dependencies:
#   python.org: =3.7.17
# ---

import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)
```

```shell
# `=`
$ ./hello.py
Python version
3.11.4 (main, Jun  7 2023, 08:49:21) [Clang 13.1.6 (clang-1316.0.21.2.3)]
Version info.
sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)

# `^`
$ ./hello.py
Python version
3.7.17 (default, Jun  6 2023, 22:04:21) 
[Clang 13.1.6 (clang-1316.0.21.2.3)]
Version info.
sys.version_info(major=3, minor=7, micro=17, releaselevel='final', serial=0)
```
