### ISSUE TITLE
nvim installs Lunarvim

### ISSUE THREAD

**Issue by tnxz** [teaxyz/cli#634]
`nvim` seems to be triggers `lvim` somehow and installs lunarvim

**Comment by mxcl** [comment]
workaround for now:

```sh
rm -rf ~/.tea/lunarvim.org ~/.tea/neovim.io ~/.tea/.local/bin/nvim
tea + neovim.io nvim
```

works because the nvim symlink will be added to tea’s local bin

**Comment by mxcl** [comment]
![image](https://github.com/teaxyz/cli/assets/58962/e20e231f-bf0e-4bdd-af1b-1f268cd95cc3)

**Comment by mxcl** [comment]
hmm in fact this means ambiguous commands always prompt which was not my intention. Will come up with a solution.
