### ISSUE TITLE
Installing npm package `re2` gets failed

### ISSUE THREAD

**Issue by mittalyashu** [teaxyz/cli#640]
I am no quite sure, which package dependency I am missing here for me to get this error.
After running this command `tea +nodejs.org^18 +pnpm.io +python.org~3.10 pnpm i`

```
Progress: resolved 1888, reused 1843, downloaded 2, added 2, done
node_modules/.pnpm/re2@1.17.7/node_modules/re2: Running install script...
 ELIFECYCLE  Command failed.
```

After going though the GH issues on `re2` package, it seems this package require `node-gyp`, which is dependant of python. But even after that, I am getting this same error. Any thoughts what could go wrong here.

**Comment by mittalyashu** [comment]
_I will try to create a minimum repo to reproduce this issue._

**Comment by jhheider** [comment]
```json
    "install": "install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR --skip-path-var RE2_DOWNLOAD_SKIP_PATH --skip-ver-var RE2_DOWNLOAD_SKIP_VER || npm run rebuild",
    "verify-build": "node scripts/verify-build.js",
    "rebuild": "node-gyp rebuild"
```

interestingly, `cd node_modules/re2 && tea pnpm run rebuild` seems to work just fine. so, i'm not sure why install would be failing, since it falls back to running rebuild. probably because it needs `npm`.

Yup. It's because it calls `npm` which isn't in your environment.

```shell
rm -rf node_modules/; tea +npmjs.com +pnpm.io pnpm i re2
Packages: +119
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/jacob/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 119, reused 119, downloaded 0, added 119, done
node_modules/.pnpm/re2@1.19.1/node_modules/re2: Running install script, done in 2m 1.4s

dependencies:
+ re2 1.19.1

Done in 2m 3.8s
```

**Comment by mittalyashu** [comment]
Yeah, you're right.

But I wonder why the install was failing since I had already added `pnpm` CLI to the environment.

**Comment by jhheider** [comment]
Because `re2`'s scripts specifically call `npm`. They assume it'll be present, as it would in most system-wide nodejs installs. Just a quirk of `tea` that it's optional/explicit.

**Comment by mittalyashu** [comment]
Great, thanks for the help.

Add `+npmjs.com` as CLI fixed the issue.
