### ISSUE TITLE
panic:Broken pipe (os error 32)

### ISSUE THREAD

**Issue by leriche03** [teaxyz/cli#642]
----------------------------------------------------->> attachment begin
BrokenPipe: Broken pipe (os error 32)
    at async run (file:///Users/runner/work/cli/cli/src/app.main.ts:129:13)
    at async file:///Users/runner/work/cli/cli/src/app.ts:23:5
<<------------------------------------------------------- attachment end
source <(tea --magic)
bash-3.2$ 
panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3ABroken+pipe+(os+error+32)

----------------------------------------------------->> attachment begin
BrokenPipe: Broken pipe (os error 32)
    at async run (file:///Users/runner/work/cli/cli/src/app.main.ts:129:13)
    at async file:///Users/runner/work/cli/cli/src/app.ts:23:5
<<------------------------------------------------------- attachment end

**Comment by jhheider** [comment]
I believe this is a function of the old (bash 3.2 is 2006) version of bash Apple ships with their OS. The installer script suggests [here](https://github.com/teaxyz/setup/blob/034d006136f423357f17eab90a51c04696582f4a/install.sh#L440) that it's more likely to be
```bash
source /dev/stdin <<<"$(tea --magic=bash)"
```
but even then, I think bash 3 was missing some of the capabilities we rely on. @mxcl is likely to remember to for sure.

Bash 4 was released in 2009, by the way. It's sort of inexplicable why Apple hasn't updated to the version released 14 years ago. But, they _did_ change to `zsh` as a default, so perhaps that's their compromise.

**Comment by leriche03** [comment]
def had to update my bash but it work thanks.
