### ISSUE TITLE
Fish completion does not work with tea installed packages

### ISSUE THREAD

**Issue by maxim092001** [teaxyz/cli#644]
Hey.

Thanks for such an exciting project, I really like it!

I found out that fish completion does not recognize packages installed with tea.

The screenshot shows `wget` which was installed via tea, `ls` and `clear` are standard commands.

<img width="720" alt="Screenshot 2023-07-22 at 09 40 34" src="https://github.com/teaxyz/cli/assets/35135337/88615360-aca1-45e1-928a-fb6af4f12368">

The only line that I have in my `fish.config` is:

```
test -d "$HOME/.tea" && "$HOME/.tea/tea.xyz/v*/bin/tea" --magic=fish --silent | source
```

If I remove the line above then the result for `wget` would be:

<img width="662" alt="Screenshot 2023-07-22 at 09 43 08" src="https://github.com/teaxyz/cli/assets/35135337/92c8dd33-3bdd-424e-8084-4a9af3a82985">

Should I add something to PATH?

**Comment by mxcl** [comment]
I believe we have had a couple tickets that talk about this previously, maybe @jhheider can recall?

**Comment by jhheider** [comment]
Most likely adding `tea` autocomplete to fish command completion is the required fix. Fish knows `wget` isn't in the $PATH, so it's tell you, despite that being confusing. You can `set -Ux fish_user_paths ~/.tea/.local/bin $fish_user_paths` to have it recognize things post-install by `tea`.

The most complete solution is likely to replicate the work done in `app.magic.ts` in the PR https://github.com/teaxyz/cli/pull/608/files for fish. I haven't dug into how much work that would be. `fish` is heavily focused on interactive experience, so it might well be easier than `zsh` was, though there are many things in fish that work against what `tea` tries to do. Always returning a `127` status on command not found, even if we take over and handle it is one of them.

**Comment by maxim092001** [comment]
> Most likely adding `tea` autocomplete to fish command completion is the required fix. Fish knows `wget` isn't in the $PATH, so it's tell you, despite that being confusing. You can `set -Ux fish_user_paths ~/.tea/.local/bin $fish_user_paths` to have it recognize things post-install by `tea`.
> 
> The most complete solution is likely to replicate the work done in `app.magic.ts` in the PR https://github.com/teaxyz/cli/pull/608/files for fish. I haven't dug into how much work that would be. `fish` is heavily focused on interactive experience, so it might well be easier than `zsh` was, though there are many things in fish that work against what `tea` tries to do. Always returning a `127` status on command not found, even if we take over and handle it is one of them.

`set -Ux fish_user_paths ~/.tea/.local/bin $fish_user_paths` helped me, thanks!

I will leave this issue be if someone would like to contribute and in meantime will take a look on the PR + your codebase, maybe I will be able to contribute myself.

**Comment by mxcl** [comment]
Closing in lieu of #704
