### ISSUE TITLE
bug: tea should ignore invalid entries in path

### ISSUE THREAD

**Issue by lino-levan** [teaxyz/cli#645]
repro:
<img width="348" alt="image" src="https://github.com/teaxyz/cli/assets/11367844/1b07b649-3a86-4d05-9786-2ab11753dae2">

system specs:
<img width="543" alt="image" src="https://github.com/teaxyz/cli/assets/11367844/19b6a3f2-7663-4273-a1aa-597854044556">

**Comment by jhheider** [comment]
That should be the same as `tea some_arbitrary_command_that_doesnt_exist`. Does that provide the same response?

**Comment by lino-levan** [comment]
<img width="375" alt="image" src="https://github.com/teaxyz/cli/assets/11367844/5a3f6f3e-b679-417e-9428-0a6a0d4e6d3e">

You're right, sorry I haven't been around tea in a while 😅

**Comment by jhheider** [comment]
Check `echo $PATH`. Suspect you've got a path there that (no longer) exists.

**Comment by lino-levan** [comment]
Not sure what I should be looking for

> $ echo $PATH
/Users/linolevan/.tea/.local/bin:/opt/homebrew/opt/llvm/bin:/Users/linolevan/Downloads/Digital:/Users/linolevan/Library/pnpm:/Users/linolevan/depot_tools:/Users/linolevan/.local/bin:/Users/linolevan/.deno/bin:/Users/linolevan/google-cloud-sdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/linolevan/.deno/bin:/Applications/Little Snitch.app/Contents/Components:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/linolevan/.cargo/bin

**Comment by jhheider** [comment]
Yup, there it is. You can find (and remove) the line that sets it -- probably in your .zshrc. or `mkdir -p ~/.don't/tools`. Regardless, it's a tea bug as well. Non-existent path entries should be ignored.

**Comment by jhheider** [comment]
Interestingly, I'm unable to reproduce that specific fault with my local `tea`:
```shell
$ tea fooo
tea: command not found: fooo
$ PATH=$PATH:~/glarg tea fooo
tea: command not found: fooo
$ export PATH=$PATH:~/glarg
$ tea fooo
tea: command not found: fooo
```

but that still seems like the culprit; unless something _else_ is triggering against your PATH.

**Comment by lino-levan** [comment]
I can't seem to find where `~/.dotnet/tools` is being set. It's not in `~/zshrc`. Investigating.

**Comment by jhheider** [comment]
If you've got enough time, `rg -. dotnet/tools ~` ought to find it. I'm suspicious that I can't reproduce it with a non-existent entry. `DEBUG=1 tea doesnt_exist` might say more.

**Comment by lino-levan** [comment]
> $ DEBUG=1 tea doesnt_exist
{
  tea: "/Users/linolevan/.tea/tea.xyz/v0.38.4/bin/tea",
  deno: "1.35.2",
  v8: "11.6.189.7",
  typescript: "5.1.6"
}
{ hydrating: [] }
{
  cmd: [ "doesnt_exist" ],
  env: {
    LDFLAGS: "-Wl,-rpath,/Users/linolevan/.tea",
    TEA_PREFIX: "/Users/linolevan/.tea",
    PATH: "/opt/homebrew/opt/llvm/bin:/Users/linolevan/Library/pnpm:/Users/linolevan/.local/bin:/Users/linoleva"... 484 more characters,
    TEA_FORK_BOMB_PROTECTOR: "1"
  }
}
error: invalid absolute path: ~/.dotnet/tools
error: {
  "code": 1
}

Doesn't seem too helpful. I'll try ripgrep. I've gone through all of this [stackexchange post](https://unix.stackexchange.com/questions/227989/complete-view-of-where-the-path-variable-is-set-in-bash) and don't see how this could possibly be set.

I'm wary of something like malware in `/usr/libexec/path_helper`, but I think I have bigger problems if someone was able to swap that binary out under my nose.

**Comment by lino-levan** [comment]
Alright, the case gets weirder. I ran your ripgrep query over my entire disk (with `sudo`, though I think I need to be a different user because I hit a lot of permission errors), and only got hits in log files which happened to include my path. I'm really not sure what's going on here.

**Comment by lino-levan** [comment]
> Interestingly, I'm unable to reproduce that specific fault with my local tea:

What OS are you running?

**Comment by jhheider** [comment]
<img width="551" alt="Screenshot 2023-07-24 at 23 27 06" src="https://github.com/teaxyz/cli/assets/13246308/153cc285-b0f1-4639-aa46-0d613b11d513">

**Comment by branchvincent** [comment]
I can reproduce, it's caused by an unexpanded `~` (so `PATH=$PATH:~/glarg tea fooo` won't reproduce but `PATH="$PATH:~/glarg" tea fooo` will)

From tea constructing a `Path`
https://github.com/teaxyz/cli/blob/423d19ff3232e85d581f8a62c969c1c0775d67ad/src/utils/execve.ts#L83, which requires it [start with `/`](https://github.com/teaxyz/lib/blob/bf685cebd7f02714e205a6d49d66eb1abce74105/src/utils/Path.ts#L46)

**Comment by jhheider** [comment]
There you go. Good eye.

**Comment by mxcl** [comment]
oops. sorry about this @lino-levan. new release coming up
