### ISSUE TITLE
Issues with Developer Environments not respecting `.tea.yaml`/`.tea.yml`, and "leaking" dependencies?

### ISSUE THREAD

**Issue by gaggle** [teaxyz/cli#651]
Encountered these two issues with the Developer Environment feature, wondering if they're useful to report?

## .tea.yaml not working
I can get `tea.yaml` and `tea.yml` to work, but not `.tea.yaml` or `.tea.yml` [even though the docs says `.tea.yaml` ought to work](https://docs.tea.xyz/features/developer-environments). Am I missing something?

<details>
<summary>Example</summary>

Invoking `tea -SE` shows it doesn't pick up the tea yaml file in the cases of `.tea*`:

```sh
$ cat tea.yml
dependencies:
  deno.land: 1.33.2
env:
  FOO: bar
$ tea -SE
pantries sync’d ⎷
FOO=bar

$ mv tea.yml tea.yaml
$ tea -SE
pantries sync’d ⎷
FOO=bar

$ mv tea.yaml .tea.yml
$ tea -SE
pantries sync’d ⎷

$ mv .tea.yml .tea.yaml
$ tea -SE
pantries sync’d ⎷

$ mv .tea.yaml tea.yml
$ tea -SE
pantries sync’d ⎷
FOO=bar
```

</details>

## Developer Environments "leak" their dependencies outside their directory?

I have a `tea.yml` file specifying `deno.land`, and Deno is not available on my system. Then I run `tea -SE` and Deno is now available. But then, from that point onwards Deno seems to be globally available, even in a new terminal.

<details>
<summary>Example</summary>

```sh
$ cat tea.yml
dependencies:
  deno.land: =1.33.2
$ which deno
deno not found
$ tea -SE
pantries sync’d ⎷
installed: ~/.tea/deno.land/v1.33.2
...
$ which deno
~/.tea/.local/bin/deno
$ deno --version
deno 1.33.2 (release, x86_64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
$ cd ..
which deno
~/.tea/.local/bin/deno
```

And even in a new terminal:
```sh
which deno
~/.tea/.local/bin/deno
```

</details>

I wasn't expecting Deno to be globally available after running `tea -SE`. Am I just misunderstanding the Developer Environment feature? [The docs says](https://docs.tea.xyz/features/developer-environments) "_Installing those tools globally makes no sense and could even cause subtle bugs during dev._" but is Deno not globally available on my system now?

**Comment by jhheider** [comment]
Did you install `tea` magic? If so, then everything `tea` packages is "available" in and out of dev environments. The dev environment doesn't require magic to work, and allows you to be precise about versions and tools you need.

**Comment by jhheider** [comment]
As for `.tea.yaml`, I felt like that did work, but [code doesn't lie](https://github.com/teaxyz/cli/blob/d43fb04d1f813e24c0d33a0c72198ed99813ab7a/src/hooks/useVirtualEnv.ts#L259-L261)

I'll PR making the code comply with the docs. If @mxcl would rather change the docs, that'll solve it too.

**Comment by gaggle** [comment]
Ah ok, yes I did install magic. Well, if it's expected behavior then that's fine, thanks for the quick reply.

**Comment by gaggle** [comment]
> Did you install `tea` magic? If so, then everything `tea` packages is "available" in and out of dev environments. The dev environment doesn't require magic to work, and allows you to be precise about versions and tools you need.

Ah ok, yes I did install magic. Well, if it's expected behavior then that's fine, thanks for the quick reply.

**Comment by mxcl** [comment]
> I wasn't expecting Deno to be globally available

yeah I've been thinking we need to split magic into 2 and have them be opt in.

1. magic dev-envs
2. magic command not found

As 2. makes our promise of “nothing installs” seem incorrect.
