### ISSUE TITLE
Wrong tea bin PATH for config.fish

### ISSUE THREAD

**Issue by sporkd** [teaxyz/cli#656]
Not sure where to report this, but it seems the TEA_ONE_LINER generated for `config.fish` is not adding `~/.tea/.local/bin` to my path. Instead it adds `~/.tea/tea.xyz/v*/bin`, and therefore none of the symlinks in `.tea/.local/bin` are available. 

### FISH
```fish
test -d "$HOME/.tea" && "$HOME/.tea/tea.xyz/v*/bin/tea" --magic=fish --silent | source

echo $PATH
/Users/peter/.tea/tea.xyz/v*/bin

which tea
/Users/peter/.tea/tea.xyz/v*/bin/tea

which lsd
(not found)
```

Whereas in zsh the symlinks are available: 

### ZSH
```zsh
test -d "$HOME/.tea" && source <("$HOME/.tea/tea.xyz/v*/bin/tea" --magic=zsh --silent)

echo $PATH
/Users/peter/.tea/.local/bin

which tea
/Users/peter/.tea/.local/bin/tea

which lsd
/Users/peter/.tea/.local/bin/lsd
```

I would submit a PR, but not sure 1) if this is intentional, and 2) if this is an issue with the TEA_ONE_LINER script, or the target script being sourced.

**Comment by sporkd** [comment]
Nice catch @jhheider💯 . I just saw in another issue that `which` is not reliable with tea (or was not in the past?). But it seems to work okay as long as the symlink is in the path.

**Comment by jhheider** [comment]
Right, traditionally, `which` _couldn't_ work, since `tea` wasn't installing to the path. Newer iterations use `$TEA_PREFIX/.local/bin/` as above, so `which` will work.
