### ISSUE TITLE
node version mismatch with pnpm, despite package.json engines

### ISSUE THREAD

**Issue by austin-meadows** [teaxyz/cli#660]
Hey guys!
I have the following noted in my `package.json`:
```json
  "engines": {
    "node": "20.5.0",
    "pnpm": "8.6.10"
  },
```

When running `node -v` and `pnpm -v`, the correct versions print:
```sh
pnpm -v
# prints 8.6.10
node -v 
# prints v20.5.0
```

However, when running `pnpm install`, I receive the following warning:
```sh
# WARN  Unsupported engine: wanted: {"node":"20.5.0"} (current: {"node":"v19.9.0","pnpm":"8.6.10"})
```

It seems `pnpm` is using node v19.9.0. Am I missing something, or perhaps does the `pnpm` provided by `tea` only allow up to ^19?

Thanks :)

**Comment by mxcl** [comment]
pnpm has this spec:

```
dependencies:
  nodejs.org: '>=14 <20'
```

for some reason, so yeah. I'll fix that.

-------

I've not seen:

```
"engines": {
    "node": "20.5.0",
    "pnpm": "8.6.10"
  },
```

is that standard? as we can support that and enforce that in the env.

**Comment by mxcl** [comment]
Fixed if you `tea --sync`

**Comment by austin-meadows** [comment]
@mxcl 

Apologies for the late response!

> pnpm has this spec:
> 
> ```
> dependencies:
>   nodejs.org: '>=14 <20'
> ```
> 
> for some reason, so yeah. I'll fix that.
> 
> I've not seen:
> 
> ```
> "engines": {
>     "node": "20.5.0",
>     "pnpm": "8.6.10"
>   },
> ```
> 
> is that standard? as we can support that and enforce that in the env.

I believe so, from https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines 

They note you can note your node version and even npm version (surely any other package manager version too) here if you'd like. :) 

I've also seen
```json
"packageManager": "packagemanager@0.0.0"
```

I thought it was actually pulling from `engines`, but seen that I am using a combination of `engines` and `packageManager` / `.node-version` file. 😂

**Comment by mxcl** [comment]
@austin-meadows thank you! scheduled for 1.0.0-alpha.3
