### ISSUE TITLE
Automatically `--sync` when needed

### ISSUE THREAD

**Issue by felipecrs** [teaxyz/cli#664]
When downloading the tea binary and running it for the first time (or when cleaning up stuff like `rm -rf ~/.tea`), tea no longer works with the following error:

```
error: pantry not found: /home/felipecrs/.tea/tea.xyz/var/pantry/projects
```

Running `tea --sync` solves the issue for subsequent executions, until the tea prefix is cleaned up again.

This is somewhat stated in the documentation though:

> `tea --sync` updates pkgs, but you have to call it *at least once*. Our installer does this for you normally

_At https://docs.tea.xyz/getting-started/install-tea/without-installer_

My use case is to bundle Tea with my [dotfiles](https://github.com/felipecrs/dotfiles), but so long this extra step is necessary, I can't simply drop its binary to my dotfiles using [chezmoi](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/). I have this extra step of calling `tea --sync` at least once.

Tea tries to be very smart when resolving dependencies from the environment. Thus, I believe tea could be smarter in this situation as well, not requiring manual intervention to make it work.

Not to mention the error message is definitely not very helpful for beginners who don't even know what tea's pantry is about.

**Comment by mxcl** [comment]
This is a bug since the current tea/cli should sync pantry itself if the pantry is missing. Will fix

**Comment by mxcl** [comment]
v0.39.5 out
