### ISSUE TITLE
`corepack` doesn't work

### ISSUE THREAD

**Issue by jakobvase** [teaxyz/cli#673]
Yarn/pnpm/etc. recommend using `corepack`, which is normally installed with node.js. When using node from tea, this doesn't work. I've solved it by installing corepack globally (`npm i -g corepack`), but I'm curious what the best/right way to solve this with tea would be? And is there anything I can do to fix it?

Corepack reads the `packageManager` field from any nearby `package.json` and transparently installs the package manager listed there. Sounds a bit like the tea magic, maybe I shouldn't be using corepack at all, and should instead update the tea environment reading to do what it does?

**Comment by mxcl** [comment]
actually, can you offer an example of using it with yarn or pnpm? that'll help me do this correctly

**Comment by jakobvase** [comment]
Sure!

After installing `node` (`brew install node`), you enable it with `corepack enable`, and then it "just works". I think `corepack` is added to the path by node somehow. So I go to a folder that has a `package.json`, and when I run `yarn install` or `pnpm install`, corepack looks up the right version of the right package manager and fetches and installs that. Output like:

```
Jakobs-MacBook-Pro:backend jakob$ yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.36s.
```

In `package.json`, I have this:

```
"packageManager": "yarn@1.22.19",
  "engines": {
    "npm": "please-use-yarn",
    "yarn": ">= 1.22.19",
    "node": "^16.0.0"
  },
```

The yarn documentation has a nice page on it: https://yarnpkg.com/getting-started/install

Let me know if I can help with anything!
