### ISSUE TITLE
tea and osx 14.0 Dev Beta

### ISSUE THREAD

**Issue by agborkowski** [teaxyz/cli#678]

**Comment by mxcl** [comment]
any problems? We think it should be fine.

**Comment by agborkowski** [comment]
I had a problem with nvm + tea cause override nvm (node.js path) config, but I'm sure it's not system specific.

Buti reach the problem with Tea is trying to use some not supported versions eg. for GIT on the Sonoma Dev version its looks like that
```
 ~/Sites/rch/test-software-backend  git -v                                                                                                                                        
Executable requires at least macOS 12.0, but is being run on macOS 10.16, and so is exiting.
```

when I removed TEA and reinstalled it by brew, all returned back to ok...

**Comment by mxcl** [comment]
hmm weird. You sure it was `tea`’s git?
