### ISSUE TITLE
`tea --silent` is broken

### ISSUE THREAD

**Issue by davdroman** [teaxyz/cli#682]
Not sure how many versions ago this broke, but I just noticed both `tea --silent` and `tea -s` now output "resolving package graph".

<img width="1512" alt="Screenshot 2023-08-08 at 11 27 59" src="https://github.com/teaxyz/cli/assets/2538074/b6e26743-724f-4af3-bc4a-b58631881c20">

**Comment by davdroman** [comment]
Fixed in 1.0.0-alpha.1 🎉

**Comment by mxcl** [comment]
Sorry for the bug :/

**Comment by davdroman** [comment]
No woz, that's what v0's are for :)
