### ISSUE TITLE
Multiple `dev` calls create nested environments?

### ISSUE THREAD

**Issue by jakobvase** [teaxyz/cli#711]
tea@1.0.0-alpha.1

```
Jakobs-MacBook-Pro:~ jakob$ cd mono
tea +git-scm.org +nodejs.org^14 +classic.yarnpkg.com@1.22.19
(tea) Jakobs-MacBook-Pro:mono jakob$ dev
tea +git-scm.org +nodejs.org^14 +classic.yarnpkg.com@1.22.19
(tea) (tea) Jakobs-MacBook-Pro:mono jakob$ dev
tea +git-scm.org +nodejs.org^14 +classic.yarnpkg.com@1.22.19
(tea) (tea) (tea) Jakobs-MacBook-Pro:mono jakob$ tea deactivate
```

What's going on here?

(to replicate, go to any folder with packages and type `dev` a few times)

**Comment by mxcl** [comment]
Certainly a bug, we can fix it by prohibiting multiple calls at this time. In the future it would be better I imagine to allow nesting in some manner. That's a 1.1 feature set though I think considering our constraints RN.

**Comment by mxcl** [comment]
I just checked and it’s actually pretty harmless. The only effect is your PS1 gets `(tea)` multiple times. Will fix all the same ofc.
