### ISSUE TITLE
Removing all +pkgs leaves my PS1 as `undefined`

### ISSUE THREAD

**Issue by jakobvase** [teaxyz/cli#712]
tea@1.0.0-alpha.1

```
Jakobs-MacBook-Pro:~ jakob$ node --version
v20.5.1
Jakobs-MacBook-Pro:~ jakob$ tea +node@16
tea: +nodejs.org=16.20.1
(tea) Jakobs-MacBook-Pro:~ jakob$ node --version
v16.20.1
(tea) Jakobs-MacBook-Pro:~ jakob$ tea deactivate
× nothing provides: deactivate
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.tea.xyz/pantry
(tea) Jakobs-MacBook-Pro:~ jakob$ node --version
v16.20.1
```

I would expect it to deactivate the loaded +pkgs

**Comment by jakobvase** [comment]
It also does this weird thing when I remove the package with `-`:

```
(tea) Jakobs-MacBook-Pro:~ jakob$ tea -node
undefinednode --version
v20.5.1
undefined
```

Maybe that's related?

**Comment by mxcl** [comment]
Where are you seeing `tea deactivate` in the docs?

You want `tea -node`, `tea deactivate` was the cmd I was playing with during dev.

**Comment by mxcl** [comment]
> It also does this weird thing when I remove the package with `-`:

This works for me. What shell, OS etc. you got?

**Comment by jakobvase** [comment]
`GNU bash, version 5.2.15(1)-release (x86_64-apple-darwin22.1.0)`

MacOS 13.5.1 on an intel based 2019 16'' macbook pro

**Comment by mxcl** [comment]
oh ok yes, I see. Will fix.
