### ISSUE TITLE
Install via `homebrew` failing

### ISSUE THREAD

**Issue by derrikf-spindance** [teaxyz/cli#718]
When running the install command documented, I am unable to install.

```
❯ brew install teaxyz/pkgs/tea-cli
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Fetching teaxyz/pkgs/tea-cli
Error: tea-cli: Failed to download resource "tea-cli"
Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.11\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/teaxyz/homebrew-pkgs/releases/download/v1.0.0-alpha.2/tea-cli-0.39.6.big_sur.bottle.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
```

**Comment by mxcl** [comment]
Yeah weird, @jhheider: https://github.com/teaxyz/homebrew-pkgs/blob/main/tea-cli.rb#L4

Probs was just my hack to allow pre-releases didn't do everything right?

**Comment by jhheider** [comment]
bad: https://github.com/teaxyz/homebrew-pkgs/releases/download/v1.0.0-alpha.2/tea-cli-0.39.6.big_sur.bottle.tar.gz
good: https://github.com/teaxyz/homebrew-pkgs/releases/download/v1.0.0-alpha.2/tea-cli-1.0.0-alpha.2.big_sur.bottle.tar.gz

the script isn't handling the pr taggings. shouldn't be a hard fix.

**Comment by jhheider** [comment]
give me few

**Comment by jhheider** [comment]
hm. the .rb file looks right (except for the source URL): https://github.com/teaxyz/homebrew-pkgs/blob/main/tea-cli.rb. I think we need to _remove_ the PR decorators from the filename (but not the path), since homebrew is looking for 1.0.0. sigh.

**Comment by jhheider** [comment]
ooook. now I'm really confused. I just "fixed" away the PR tags, now I'm getting this:

`GET https://github.com/teaxyz/homebrew-pkgs/releases/download/v1.0.0-alpha.2/tea-cli-1.0.0-alpha.2.arm64_big_sur.bottle.tar.gz` exited with 22.`

I think the problem might have just been the un-updated base URL. I'll revert a bunch of it.

**Comment by jhheider** [comment]
Ok. working now. @derrikf-spindance you likely need to do the following:

```sh
brew untap teaxyz/pkgs
brew install teaxyz/pkgs/tea-cli
```

Thanks for catching this. `brew` has some magical guts that need to be satisfied. :)

**Comment by mxcl** [comment]
Tested it and it works. Thanks @jhheider !
