### ISSUE TITLE
dev command not found

### ISSUE THREAD

**Issue by haliliceylan** [teaxyz/cli#721]
Hi all,

I Installed tea with `sh <(curl tea.xyz)`.  but `dev` command is not working. I was following this [documentation](https://docs.tea.xyz/using-dev/dev). I am trying to create a tea.yaml for our project so my friend and I can use same version tools without using docker for development (which is great if we can succeed).

tea version: `tea 0.39.6`

System Info:

```
Software:
    System Software Overview:
      System Version: macOS 13.2.1
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

Hardware:
    Hardware Overview:
      Model Name: MacBook Air
      Chip: Apple M2
      Memory: 16 GB
```

**Comment by mxcl** [comment]
Hi, yes. Currently our documentation is inaccurate in that the installer will not install v1, it installs v0 and thus you do not have a `dev` command.

I apologize for this confusion, we are working hard to get everything sync’d.

To install v1 see: https://docs.tea.xyz/run-anywhere/terminals (everything works except the installer lol)

Sorry again. I'll try to get the installer updated today.

**Comment by mxcl** [comment]
`sh <(curl tea.xyz)` now installs the v1 alpha
