### ISSUE TITLE
Confusion about tea magic.

### ISSUE THREAD

**Issue by haliliceylan** [teaxyz/cli#722]
Hi all,

I Installed tea with `sh <(curl tea.xyz)`, I choose to install magic also. Its working magically ! (Its super) But In [documents FAQ Section](https://docs.tea.xyz/appendix/faq#what-happened-to-tea-magic) Its mention magic is removed.

How Is it possible ?

**Comment by mxcl** [comment]
We released 1.0.0-alpha.1 three days ago where we changed how magic works. I think you discovered this project in this in between time where documentation is not fully migrated.

`sh <(curl tea.xyz)` installs v0 which still has magic. We haven't yet migrated the installer as there is a lot of infrastructure to move.

Sorry for the confusion.

tea is still “magical” but it requires an additional step, eg:

```sh
$ node
^^ tea can run that; type `tea`

$ tea
tea +node && node
Welcome to Node.js v20.1.2
>
```

**Comment by mxcl** [comment]
Our blog post here explains in more details the justifications for our changes in v1.

https://tea.xyz/blog/tea-1-0-0-alpha-1/

**Comment by haliliceylan** [comment]
How can I Install new version, because of I am using m2, brew is not working for me.

**Comment by jhheider** [comment]
Interesting. Homebrew works find on my m2 air. Regardless, one of these options will work for you: https://docs.tea.xyz/run-anywhere/terminals

**Comment by haliliceylan** [comment]
I tried again, Its working right now. I just deleted the `~/.tea` directory to clean old version. Is it enough ?

**Comment by jhheider** [comment]
Generally, should be sufficient. You can remove the (old) magic invocations from your .bashrc/.zshrc/etc files if you like, since you can manage that with the new cli.

**Comment by mxcl** [comment]
The installer now works, though if tea is already installed it doesn't do anything. Or the one liner from the docs also now works so maybe do that:

```sh
curl -Ssf https://tea.xyz/$(uname)/$(uname -m).tgz | sudo tar xz -C /usr/local/bin
```
