### ISSUE TITLE
Multiple packages provides same command, but we should have some preferred by default

### ISSUE THREAD

**Issue by felipecrs** [teaxyz/cli#748]
Sorry, I could not find a better title for this issue. Feel free to retitle it.

```console
$ tea go@1.18 version
× multiple projects provide: go@1.18
│ pls be more specific:
│
│     tea +go.dev go@1.18 version
│     tea +encore.dev/go go@1.18 version
│
╰─➤ https://help.tea.xyz/ambiguous-pkgspec
```

Look, I get it. Multiple packages provides the same command and we should allow the user to select it.

However, in some cases, 99% of the users would prefer one package (in this example `go.dev`), so I believe tea should have smarter defaults. The 1% who is actually trying to use `encore.dev/go` will probably know how to handle it (i.e. `tea +encore.dev/go go version`).

Note that for the example above, only go.dev provides an actual version within that specified range `@1.18`, nevertheless, I don't think we should use that as the primary selection algorithm. MAYBE as fallback it would be nice. I'm thinking about an hypothetical situation where openjdk.org would cease having new packages and then `adoptium.net/temurin` starts publishing only newer packages. In this (very corner) case, it would be reasonable to fallback to `openjdk.org` if can't find in `adoptium.net/temurin` (and obviously none was specified by the user).

My suggestion would be to extend the pkg manifest with something like:

```diff
# https://github.com/teaxyz/pantry/blob/main/projects/go.dev/package.yml

provides:
-  - bin/go
-  - bin/gofmt
+  - name: bin/go
+    preferred: true
+  - name: bin/gofmt
+    preferred: true
```

Or maybe `default: true`. False by default. When multiple packages provides that command, but none has set a `preferred: true`, throw error message like today. When multiple packages provides that command, but one of them has set a `preferred: true`, use that without throwing the error.

Backwards compatibility with existing package manifests can be kept. If the `string` form is found, assume `name` to be the string and `preffered` to be unset.

The Pantry CI must have some test to verify that the same command isn't defined as preferred by multiple packages.

Related to https://github.com/teaxyz/cli/issues/744, but this problem isn't limited to `tea install`.

**Comment by mxcl** [comment]
I agree that this is a clear case for a default and the pantry should be extended to handle this. Eventually.

In the meantime I wonder if `encore.dev/go` should have its provides commented out.

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry/commit/c90d3977b73af7f67096829740ac24275239386a
