### ISSUE TITLE
Store etag So Downloads Use Cache

### ISSUE THREAD

**Issue by Xercesblu3** [teaxyz/cli#85]
store and use etag in useDownload() so [github.com](http://github.com/) downloads use cache

**Comment by Xercesblu3** [comment]
@kunalgoyal9 get this one done when you can please.

**Comment by kunalgoyal9** [comment]
Sure,
@Xercesblu3 Can I get more detail on this one please

**Comment by jhheider** [comment]
Downloads from CF _should_ return the etag header, which you can pass back on subsequent queries to see if the response would be different or not.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

If we save this with useCache downloads, we should be able to quickly know if our cache item is valid or not.

**Comment by kunalgoyal9** [comment]
@jhheider right now we are using `If-Modified-since` from header to check for cache... Now should we include `etag` as well.. right?

**Comment by jhheider** [comment]
I wonder if GitHub honors if-modified. Those should be redundant.

**Comment by Xercesblu3** [comment]
Thank you for helping explain @jhheider

**Comment by mxcl** [comment]
GitHub does not provide modified-since for source tarballs for some reason. Hence this request. We already do `If-Modified` in useDownload
