### ISSUE TITLE
S3 Fallback and Backup

### ISSUE THREAD

**Issue by Xercesblu3** [teaxyz/cli#86]
Code useCache.ts, useOffLicense.ts, and prefab/install.ts to use IPFS with an S3 backup

- change useOffLicense type Type = 's3' | 'ipfs', and add appropriate logic to the two functions
- add a useRepository hook and change useCache.ts/install.ts to use its .download() function
- use S3 as a fallback if .ipfs file is not found or if the path errors/404s

**Comment by kunalgoyal9** [comment]
Its done... now need to make IPFS infra more robust

**Comment by Xercesblu3** [comment]
Safe to close then? I assume making IPFS more robust can go on a separate ticket?
