### ISSUE TITLE
Open Terminal on Copy

### ISSUE THREAD

**Issue by Xercesblu3** [teaxyz/cli#97]
We need an app developed/installed to the tea/cli to automatically open the terminal via the user’s web browser (tea www) when they click-to-copy the tea one-liner. The one-liner should be automatically pasted/entered into the terminal upon starting. Currently, the tea/cli asks users if they would like to install tea via a y/n question. If this could be bypassed, that would better ensure an install, but will defer to mxcl. Not giving devs an options may piss them off.

The imperative of this is two fold:
1. we ensure more installs from marketing efforts/page visits
2. we are able to confirm that a btn-click on www equates to an install (this will help Gypsy to determine which ad channels are performing best)

**Comment by tsmitty11** [comment]
@mxcl @Xercesblu3 I opened a draft PR with the necessary UI changes for the 'open in terminal' button. That [PR can be found here](https://github.com/teaxyz/www/pull/176), and here's a Loom video showing the change: 

https://www.loom.com/share/c0b7616789c14a8585f064d9324170b5

**Comment by mxcl** [comment]
Closing in favor of `tea/gui`

**Comment by mxcl** [comment]
A candidate for the “most misleading ticket title” ever IMO.

**Comment by Xercesblu3** [comment]
@mxcl what title would have been better? Want to try and improve there

**Comment by mxcl** [comment]
On Copy what? This is the repo for tea/cli, the fact it was for copying for the website requires a leap of faith and judgement to conclude without reading the body text.

Open Terminal to do what? Typically if you open a terminal you just get a prompt. This is not what was asked in the body text.

And as we discussed, we didn't want it for copy so at that point the title needed to be changed.
